<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php $themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $galleryImages = $block->getGalleryImages(); ?>


<?php $glr_effect = $themeSettingConfig->getStoreConfig('extragallery/general/glr_effect'); ?>
<?php $lbox_image = $glr_effect == 2 ? 1 : 0; ?>

<?php if(count($galleryImages) >= 1): ?>
	<div id="owl-carousel-gallery<?= $_product->getId(); ?>" class="owl-carousel gallery-horizontal">
		<?php foreach($galleryImages as $image): ?>
			<?php $lbImage = $image->getLabel() ? $image->getLabel() : $image->getLabelDefault(); ?>
			<?php $isVideo = $image->getMediaType() == 'external-video' ? true : false; ?>
			<?php $href = $isVideo ? $image->getVideoUrl() : $image->getLargeImageUrl(); ?>

			<div class="product item-image imgzoom<?php if($isVideo): ?> item-image-video<?php endif ?>" data-zoom="<?php echo $image->getLargeImageUrl(); ?>">

				<?php if($isVideo): ?><div class="label-video"><?php echo __('Video') ?></div><?php endif ?>

				<?php if($lbox_image): ?>
					<a class="lb<?php if($isVideo): ?> video-link<?php endif ?>" href="<?php echo $href; ?>">
						<img src="<?php echo $image->getMediumImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
					</a>
				<?php else: ?>
					<img src="<?php echo $image->getMediumImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
					<?php if($isVideo): ?>
						<a target="_blank" class="popup-video" href="<?php echo $image->getVideoUrl(); ?>">
							<span class="ti-video-camera"></span>
						</a>
					<?php endif ?>
				<?php endif ?>
			</div>
		<?php endforeach ?>
	</div>

	<script>
		require([
			'jquery',
			'mgsowlcarousel',
			'magnificPopup'
		], function ($) {
			$('#owl-carousel-gallery<?= $_product->getId(); ?>').owlCarousel({
				items: 1,
				autoplay: false,
				lazyLoad: false,
				nav: false,
				dots: true,
				rtl: $_rtlConfig
			});
			<?php if($lbox_image): ?>
			$('.product.media').magnificPopup({
				delegate: '.imgzoom .lb',
				type: 'image',
				tLoading: 'Loading image #%curr%...',
				mainClass: 'mfp-img-gallery',
				fixedContentPos: true,
				gallery: {
					enabled: true,
					navigateByImgClick: true,
					preload: [0,1]
				},
				iframe: {
					markup: '<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" frameborder="0" allowfullscreen></iframe><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></div>'
				},
				image: {
					tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
				},
				callbacks: {
					elementParse: function(item) {
						if($(item) && $(item.el).hasClass('lb') && $(item.el).hasClass('video-link')) {
							item.type = 'iframe';
						} else {
							item.type = 'image';
						}
					}
				}
			});
			<?php endif ?>
		});
	</script>
<?php else: ?>
	<?php // Product no image ?>
	<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
	<?php $noImage = $_imagehelper->init($_product, 'product_page_image_large')->getUrl() ?>
	<div class="product item-image base-image">
		<img src="<?php echo $noImage; ?>" alt=""/>
	</div>
<?php endif ?>

<?php // Image 360 ?>
<?php $rotateImage = $_product->getData('mgs_j360') ?>
<?php $rotateImages = [] ?>
<?php if($rotateImage): ?>
	<?php $rotateImages = $themeSettingConfig->getRotateImages($_product->getId()) ?>
<?php endif ?>
<?php if($rotateImage && (count($rotateImages)>0)): ?>
	<a class="rotate-image" href="#" onclick="rotate360(); return false"></a>
    <script type="text/javascript">
        function rotate360(){
            require([
                'jquery',
                "mage/translate",
                'mrotateImage'
            ], function ($) {
                $.ajax({
                    url: '<?php echo $this->getUrl('mgsthemesetting/index/rotate') ?>',
                    data: ('&product=<?php echo $_product->getId() ?>'),
                    type: 'get',
                    dataType: 'json',
                    cache: true,
                    showLoader: true
                }).done(function (response) {
                    $('.loading-mask').append(response.html);
                    $('.loading-mask').addClass('j360-container');
                    setTimeout(initImageRotate, 1);

                }).fail(function (error) {
                    alert($.mage.__('Sorry, something went wrong. Please try again later.'));
                });
            });
        }

        function initImageRotate(){
            require([
                'jquery',
                "mage/translate",
                'mrotateImage'
            ], function ($) {
                $('.loading-mask').show();
                $('#mgs_j360').j360();
            });
        }

        function closeRotateContainer(){
            require([
                'jquery',
                "mage/translate",
                'mrotateImage'
            ], function ($) {
                $('.rotate-image-container').remove();
                $('.loading-mask').removeClass('j360-container');
                $('.loading-mask').hide();
                $('.preload_img').parent().remove();
            });
        }
    </script>
<?php endif ?>
