<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
use Magento\Framework\App\Action\Action;

//Create helper

$aHelper = $this->helper('MGS\AjaxCart\Helper\Data');

?>
<?php
    //check cart
    $isCartShow = false;
    if($aHelper->getConfig('ajaxcart/additional/animation_type') == 'showcart') {
        $isCartShow = true;
    }
 ?>
<?php
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$show = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/show_crosssell');
$rtl = $themeSettingConfig->getStoreConfig('themesettings/general/rtl_theme') ? 'true' : 'false';

$exist = $block->getItemCount();
$type = 'crosssell';
$class = $type.'-mini';
$useSlider = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_slider');
if($useSlider){
    $autoPlay = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_autoplay');
    $stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_stop_auto');
    $loop = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_loop');
    $nav = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_navigation');
    $dots = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_pagination');
    $slideBy = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_slide_by');
}
$perRowDefault = 2;
$perRowTablet = 2;
$perRowMobile = 2;
$classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;

$image = 'cart_cross_sell_products';
$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_title');
$title = $titleConfig ? __($titleConfig) : __('More Choices:');
$items = $block->getItems();

$showAddTo = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = false;
$canItemsAddToCart = false;
?>
<?php if ($show):?>
<div id="crosssell-wrap">
    <?php if ($exist):?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <div class="title text-center">
                <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
            </div>
            <div class="block-content content <?php if(!$useSlider): ?><?= $classCol ?><?php endif ?>" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <div class="products wrapper grid products-grid<?php if($useSlider): ?> active-slider carousel-related<?php endif ?> products-<?php /* @escapeNotVerified */ echo $type; ?>">
                    <div id="product-slider-<?= $class ?>" class="products list items product-items<?php if($useSlider): ?> owl-carousel<?php endif ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                        <?php
                                $isSimpleProduct = false;
                                if($_item->getTypeId() == 'simple') {
                                    $isSimpleProduct = true;
                                }
                             ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                            <div class="product-top">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->setData('product',$_item)->toHtml(); ?>
                                </a>
                                <div class="label">
                                    <?php echo $themeSettingConfig->getProductLabel($_item); ?>
                                </div>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" class="action towishlist" title="<?= __('Add to Wish List') ?>" aria-label="<?= __('Save') ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>' data-action="add-to-wishlist" role="button">
                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Add to Compare')) ?>" aria-label="<?= $block->escapeHtml(__('Compare')) ?>" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>' role="button">
                                                <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                </div>
                            </div>
                            <?=($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'mage/url',
        'catalogAddToCart',
        'mlazyload',
        'mgsowlcarousel'
    ], function ($, url, catalogAddToCart) {
        function initOwlCrossSellMini() {
            $("img.lazy").unveil(25, function(){
                var self = $(this);
                setTimeout(function(){
                    self.removeClass('lazy');
                    self.parents('.parent_lazy').addClass('lazy_loaded');
                }, 0);
            });
            
            var widget = $("#product-slider-<?= $class ?> [data-role=tocart-form]").catalogAddToCart({});
            // widget.catalogAddToCart('submitForm', $("#product-slider-<?= $class ?> [data-role=tocart-form]"));

            <?php if($useSlider): ?>
            $('#product-slider-<?= $class ?>').owlCarousel({
                items: <?= $perRowDefault; ?>,
                autoplay: <?= $autoPlay ? 'true' : 'false' ?>,
                autoplayHoverPause: <?= $stopAutoPlayHover ? 'true' : 'false' ?>,
                margin:30,
                nav: <?= $nav ? 'true' : 'false' ?>,
                dots: <?= $dots ? 'true' : 'false' ?>,
                loop: <?= $loop ? 'true' : 'false' ?>,
                navText: ["<span></span>","<span></span>"],
                <?php if($slideBy): ?>
                slideBy: <?= $slideBy ?>,
                <?php endif ?>
                lazyLoad: true,
                rtl: <?= $rtl ?>,
                responsive:{
                    0:{
                        items: <?= $perRowMobile; ?>
                    },
                    768:{
                        items: <?= $perRowTablet; ?>
                    },
                    992:{
                        items: <?= $perRowDefault; ?>
                    }
                }
            });
            <?php endif ?>
        }
        function getCrossSellWrapData(){
            $.ajax({
                url : url.build('vendorextend/index/index'),
                type : 'get',
                success : function (result) {
                    $("#crosssell-wrap").html($('<div>'+result+'</div>').find("#crosssell-wrap").html());
                    initOwlCrossSellMini();
                }
            });
        }
        $(document).ready(initOwlCrossSellMini);
        $(document).on('customer-data-reload', getCrossSellWrapData);
    });
</script>
<?php endif;?>