<style>
    .cms-index-index .page-main {
        max-width: 100%;
    }
    .columns .column.main {
        padding-bottom: 0;
    }
    .porto-u-heading .porto-u-main-heading h1,
    .porto-u-heading .porto-u-main-heading h2,
    .porto-u-heading .porto-u-main-heading h3,
    .porto-u-heading .porto-u-main-heading h4,
    .porto-u-heading .porto-u-main-heading h5,
    .porto-u-heading .porto-u-main-heading h6 {
        margin: 0;
        padding: 0;
        line-height: normal;
    }
    .porto-ibanner-layer {
        text-align: left;
        position: absolute;
        z-index: 10;
    }
    @media (max-width: 575px) {
        .porto-ibanner-layer {
            font-size: 0.65rem;
        }
    }
    .coupon-sale strong {
        margin-left: 8px;
        color: #9a2948;
        font-size: 2.2em;
        vertical-align: top;
        line-height: 0.6;
    }
    .coupon-sale sup {
        font-size: 0.5em;
    }
    .custom-nav-1.owl-carousel .owl-nav .owl-prev::before {
        content: "";
        position: absolute;
        top: 4.7px;
        width: 10px;
        height: 10px;
        border-top: 2px solid #000;
        border-left: 2px solid #000;
        transform: translate3d(-50%, -50%, 0) rotate(-45deg);
        left: auto;
    }
    .custom-nav-1.owl-carousel .owl-nav .owl-prev::after {
        content: "";
        display: block;
        position: absolute;
        left: 23px;
        top: 3.5px;
        width: 33px;
        border-top: 2px solid #000;
        transform: translate3d(-50%, 0, 0);
    }
    .custom-nav-1.owl-carousel .owl-nav .owl-next::before {
        content: "";
        position: absolute;
        top: 4.7px;
        width: 10px;
        height: 10px;
        border-top: 2px solid #000;
        border-left: 2px solid #000;
        transform: translate3d(-50%, -50%, 0) rotate(135deg);
        left: auto;
    }
    .custom-nav-1.owl-carousel .owl-nav .owl-next::after {
        content: "";
        display: block;
        position: absolute;
        right: -11px;
        top: 3.5px;
        width: 33px;
        border-top: 2px solid #000;
        transform: translate3d(-50%, 0, 0);
    }
    .custom-nav-1.owl-carousel.nav-pos-inside .owl-nav .owl-next {
        right: 40px;
    }
    .custom-nav-1.owl-carousel.nav-pos-inside .owl-nav .owl-prev {
        left: 40px;
    }
    .custom-nav-2 .owl-nav .owl-next::before,
    .custom-nav-2 .owl-nav .owl-prev::before {
        content: "\e8cc";
    }
    .custom-nav-2 .owl-nav .owl-prev {
        left: -19px;
        transform: rotateZ(180deg) translateY(50%) !important;
        color: #222529 !important;
    }
    .custom-nav-2 .owl-nav .owl-next {
        right: -19px;
        color: #222529 !important;
    }
</style>
<div class="vc_row wpb_row row top-row no-padding">
    <div class="vc_column_container col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div id="banner-slider-demo-37" class="porto-carousel owl-carousel home-banner-slider intro-carousel custom-nav-1 nav-pos-inside nav-style-1 show-nav-hover">
                <div class="porto-ibanner" style="background: #f4f4f4; min-height: 500px;">
                    <img alt="" width="1903" height="550" class="porto-ibanner-img" src="{{media url=wysiwyg/smartwave/porto/homepage/37/shop37-intro-1.jpg}}" />
                    <div class="porto-ibanner-desc no-padding d-flex">
                        <div class="container">
                            <div class="porto-ibanner-container">
                                <div class="porto-ibanner-layer" style="left: 0%; top: 50%; transform: translateY(-50%);">
                                    <div data-appear-animation="fadeInLeft" data-appear-animation-delay="150">
                                        <div class="porto-u-heading m-l-n-xs mb-1">
                                            <div class="porto-u-main-heading">
                                                <h2 style="font-weight: 700; font-size: 5.3125em; line-height: 1;">Porto wine</h2>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading mb-4" data-appear-animation="fadeInLeft" data-appear-animation-delay="200">
                                            <div class="porto-u-main-heading">
                                                <h3 style="font-weight: 600; font-size: 1.375em; line-height: 1; letter-spacing: 0.2em;">2016 Cabernet Sauvignon</h3>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading mb-4">
                                            <div class="porto-u-main-heading">
                                                <div style="font-weight: 300; color: #777777; font-size: 1.125em; line-height: 1.78; letter-spacing: -0.02em;">
                                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br />
                                                    quam lacus, et suscipit lectus porta efficitur.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading coupon-sale ms-1 m-b-md pb-2">
                                            <div class="porto-u-main-heading">
                                                <h3 style="font-weight: 700; font-size: 1.1em; line-height: 1; letter-spacing: -0.02em;">
                                                    only <strong> <sup>$</sup>39<sup>99</sup> </strong>
                                                </h3>
                                            </div>
                                        </div>
                                        <div class="vc_btn3-container ms-1 m-b-md d-inline">
                                            <a class="vc_btn3 vc_btn3-shape-default text-body btn btn-md btn-light" style="font-size: 0.9375em; font-weight: 600; padding: 1.266em 2.533em;" href="#" title="Shop">SHOP NOW</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="porto-ibanner" style="background: #f4f4f4; min-height: 500px;">
                    <img alt="" width="1903" height="550" class="porto-ibanner-img" src="{{media url=wysiwyg/smartwave/porto/homepage/37/shop37-intro-2.jpg}}" />
                    <div class="porto-ibanner-desc no-padding d-flex">
                        <div class="container">
                            <div class="porto-ibanner-container">
                                <div class="porto-ibanner-layer banner-text-end" style="right: 0%; top: 50%; transform: translateY(-50%);">
                                    <div data-appear-animation="fadeInUp" class="appear-animation">
                                        <div class="porto-u-heading m-l-n-xs mb-1">
                                            <div class="porto-u-main-heading">
                                                <h2 style="font-weight: 700; font-size: 5.3125em; line-height: 1;">Rare Wines</h2>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading mb-4">
                                            <div class="porto-u-main-heading">
                                                <h3 style="font-weight: 600; font-size: 1.375em; line-height: 1; letter-spacing: 0.2em;">The Top Selection</h3>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading mb-4">
                                            <div class="porto-u-main-heading">
                                                <div style="font-weight: 300; color: #777777; font-size: 1.125em; line-height: 1.78; letter-spacing: -0.02em;">
                                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br />
                                                    quam lacus, et suscipit lectus porta efficitur.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="porto-u-heading coupon-sale ms-1 m-b-md pb-2" data-appear-animation="fadeInLeft">
                                            <div class="porto-u-main-heading">
                                                <h3 style="font-weight: 700; font-size: 1.1em; line-height: 1; letter-spacing: -0.02em;">
                                                    Starting at <strong> <sup>$</sup>99<sup>99</sup> </strong>
                                                </h3>
                                            </div>
                                        </div>
                                        <div class="vc_btn3-container ms-1 m-b-md d-inline">
                                            <a class="vc_btn3 vc_btn3-shape-default text-body btn btn-md btn-light" style="font-size: 0.9375em; font-weight: 600; padding: 1.266em 2.533em;" href="#" title="Shop">SHOP NOW</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                    var banner_owl = $("#banner-slider-demo-37");
                    banner_owl.owlCarousel({
                        items: 1,
                        autoplay: false,
                        autoplayTimeout: 7000,
                        autoplayHoverPause: true,
                        dots: false,
                        nav: true,
                        navRewind: true,
                        animateIn: "fadeIn",
                        animateOut: "fadeOut",
                        loop: true,
                        lazyLoad: true,
                    });
                    var portoSlideCarouselInit = function (e) {
                        var $this = $(e.currentTarget);
                        if ($this.find(".owl-item.cloned").length) {
                            $this.find(".appear-animation").themeAnimate();
                        }
                        setTimeout(function () {
                            var $hiddenItems = $this.find(".owl-item:not(.active)");
                            if (window.innerWidth > 767) {
                                $hiddenItems.find(".appear-animation").removeClass("appear-animation-visible");
                                $hiddenItems.find(".appear-animation").each(function () {
                                    var $el = $(this),
                                        delay = Math.abs($el.data("appear-animation-delay") ? $el.data("appear-animation-delay") : 0);
                                    if (delay > 1) {
                                        this.style.animationDelay = delay + "ms";
                                    }

                                    var duration = Math.abs($el.data("appear-animation-duration") ? $el.data("appear-animation-duration") : 1000);
                                    if (1000 != duration) {
                                        this.style.animationDuration = duration + "ms";
                                    }
                                });
                            }
                        }, 300);
                    };
                    var portoCarouselTranslated = function (e) {
                        var $this = $(e.currentTarget);
                        if (window.innerWidth > 767) {
                            if ($this.find(".owl-item.cloned").length && $this.find(".appear-animation:not(.appear-animation-visible)").length) {
                                $(document.body).trigger("appear_refresh");
                            }
                        }
                        var $active = $this.find(".owl-item.active");
                        if ($active.hasClass("translating")) {
                            $active.removeClass("translating");
                            return;
                        }
                        $this.find(".owl-item.translating").removeClass("translating");

                        if (window.innerWidth > 767) {
                            $this.find(".appear-animation").removeClass("appear-animation-visible");
                            $active.find(".appear-animation").each(function () {
                                var $animation_item = $(this),
                                    anim_name = $animation_item.data("appear-animation");
                                $animation_item.addClass(anim_name + " appear-animation-visible");
                            });
                        }
                    };
                    banner_owl.on("initialized.owl.carousel", portoSlideCarouselInit).on("translated.owl.carousel", portoCarouselTranslated);
                });
            </script>
        </div>
    </div>
</div>
<style>
    .tabs {
        margin-bottom: 35px;
    }
    .tabs-center .nav-tabs {
        margin: 0 auto;
        text-align: center;
        justify-content: center;
        padding: 0;
    }
    .custom-filter.tabs .nav-item {
        display: block;
        width: 50%;
        margin: 0;
    }
    .custom-filter .tab-content {
        padding: 10px 30px;
        background: #fff;
        border: 1px solid #9a2948;
        box-shadow: 0 1px 5px 0 rgb(0 0 0 / 4%);
        border-top-width: 0;
    }
    .custom-filter.tabs ul.nav-tabs .nav-link {
        position: relative;
        border: none;
        background: transparent;
        color: #777;
        font-size: 1.25rem;
        letter-spacing: 0.2em;
        font-weight: 700;
        font-family: Spectral SC, sans-serif;
        line-height: 1.8;
        display: block;
        padding: 0.5rem 1rem;
        margin-bottom: -1px;
        margin-right: 1px;
    }
    .custom-filter.tabs ul.nav-tabs .nav-link:hover,
    .custom-filter.tabs ul.nav-tabs li.ui-tabs-active .nav-link {
        color: #9a2948;
    }
    .custom-filter.tabs ul.nav-tabs .nav-link::after {
        content: "";
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        height: 1px;
        border-bottom: 1px solid #e7e7e7;
        transition: border-color 0.3s;
    }
    .custom-filter.tabs ul.nav-tabs .nav-link:hover::after,
    .custom-filter.tabs ul.nav-tabs li.ui-tabs-active .nav-link::after {
        border-color: #9a2948;
    }
    .custom-filter .thumb-info {
        display: flex;
        flex-direction: column;
        padding: 0 !important;
    }
    .custom-filter .thumb-info-title {
        display: flex !important;
        flex-direction: column;
        padding: 20px 0 5px !important;
        text-align: left !important;
        letter-spacing: 0;
    }
    .custom-filter .sub-title {
        margin-bottom: 7px !important;
        text-transform: capitalize;
        letter-spacing: -0.01em;
    }
    li.product-category .sub-categories {
        position: relative;
        font-size: 13px;
        font-weight: 400;
        opacity: 0.7;
    }
    ul.sub-categories::after {
        content: "";
        position: absolute;
        bottom: 0;
        width: 100%;
        box-shadow: 0 -15px 60px 40px rgb(255 255 255);
    }
    .custom-filter .sub-categories li {
        padding: 4px 0;
    }
    .custom-filter .sub-categories {
        order: 1;
    }
    .custom-filter .thumb-info > a {
        position: relative;
        z-index: 1;
        order: 2;
        font-size: 12px;
        font-weight: 700;
        color: #222529;
        text-transform: uppercase;
    }
    .custom-filter .thumb-info > a i {
        font-size: 14px;
    }
</style>
<div class="vc_row wpb_row top-row m-b-xs no-padding porto-inner-container" data-appear-animation="fadeInUp">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading custom-mb-1">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 400; margin-bottom: 10px; font-size: 15px; line-height: 1; letter-spacing: 0.2em;">FILTER BY:</h2>
                        </div>
                    </div>
                    <div class="tabs custom-filter tabs-center">
                        <div id="cat_tab_element">
                            <ul class="nav nav-tabs d-flex flex-wrap align-itmes-center">
                                <li class="nav-item"><a class="nav-link" href="#cattab-1">VARIETAL</a></li>
                                <li class="nav-item"><a class="nav-link" href="#cattab-2">REGION</a></li>
                            </ul>
                        </div>
                        <div id="cat_tab_element_content" class="tab-content">
                            <div id="cattab-1" class="tab-pane">
                                <div class="porto-products wpb_content_element porto-product-category-widget hide-count">
                                    <ul class="products row products-container grid category-pos-outside category-text-center category-color-dark" style="margin-left: -10px; margin-right: -10px;">
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Bordeaux Blends</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Cabernet Sauvignon</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Merlot</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Pinot Noir</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Sangiovese</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">Red Wine</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Chardonnay</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Pinot Gris/grigio</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Riesling</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Sauvignon Blanc</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">White Bordeaux Blends</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">White Wine</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Champagne</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Desert & Fortified</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Rose Wine</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Sake</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Sparkling</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">Other</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">From $100 to $200</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">From $200 to $500</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">From $40 to $60</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">From $60 to $100</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Top Sellers</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">Selection</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div id="cattab-2" class="tab-pane">
                                <div class="porto-products wpb_content_element porto-product-category-widget hide-count">
                                    <ul class="products row products-container grid category-pos-outside category-text-center category-color-dark" style="margin-left: -10px; margin-right: -10px;">
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Bordeaux</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Burgundy</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Champagne</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Rhone</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Woddu</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">France</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Fruili-venezia-giulia</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Piedmont</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Siciliy</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Tuscany</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Veneto</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">Italy</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">California</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Central Coast</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Napa Volley</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Sonoma Country</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Washington</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">USA</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="product-category product-col col-lg-3 col-md-4 col-6">
                                            <div class="thumb-info align-center">
                                                <a href="#" aria-label="category">View All <i class="porto-icon-angle-down"></i></a>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <ul class="sub-categories">
                                                            <li class="cat-item">
                                                                <a href="#">Australia</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Austria</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Germany</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Portugal</a>
                                                            </li>
                                                            <li class="cat-item">
                                                                <a href="#">Spain</a>
                                                            </li>
                                                        </ul>
                                                        <a href="#" aria-label="category">
                                                            <h3 class="sub-title thumb-info-inner">Country</h3>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        require(["jquery", "mage/backend/tabs"], function ($) {
                            $(function () {
                                $("#cat_tab_element").tabs({
                                    active: "cattab-1",
                                    destination: "#cat_tab_element_content",
                                    shadowTabs: [],
                                });
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row porto-inner-container" data-appear-animation="fadeInUp" data-appear-animation-delay="100">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 44px; font-size: 18px; line-height: 1; letter-spacing: 0.2em;">POPULAR WINES</h2>
                        </div>
                    </div>
                    <div id="bestseller-products" class="porto-products wpb_content_element custom-nav-2 m-b-lg theme_option">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="dots-style-1 nav-center-images-only nav-style-1 nav-inside show-nav-hover" product_count="8" aspect_ratio="0"
                            image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#bestseller-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 4,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .custom-cta-1 .vc_column-inner {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 250px;
        padding: 10px 44px !important;
    }
    .custom-cta-1 .coupon-sale strong {
        color: #fff;
    }
    .custom-cta-2 .vc_column-inner {
        display: flex;
        flex-direction: column;
        min-height: 250px;
        padding: 43px 0 20px 33px !important;
    }
    .custom-cta-2 i {
        margin-left: 10px;
        color: #9a2948;
        font-family: Poppins, sans-serif;
        font-weight: 700;
    }
    .custom-cta-2 b {
        margin-left: 6px;
        font-size: 25px;
        font-weight: 600;
        font-family: Poppins, sans-serif;
    }
    .custom-cta-3 .vc_column-inner {
        display: flex;
        justify-content: center;
    }
    .custom-cta-3 em {
        font-weight: 600;
        font-style: normal;
    }
    .text-sm {
        font-size: 0.8125rem !important;
    }
    .font-weight-semibold,
    .text-weight-semibold {
        font-weight: 600;
    }
    @media (min-width: 992px) {
        .text-lg-end {
            text-align: right !important;
        }
        .ms-lg-auto {
            margin-left: auto !important;
        }
    }
</style>
<div class="vc_row wpb_row top-row porto-inner-container" style="margin-bottom: 37px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="custom-cta-1 m-b-md vc_column_container col-md-8">
                <div class="wpb_wrapper vc_column-inner" style="background: #1f1f1f url({{media url=wysiwyg/smartwave/porto/homepage/37/banner-1.jpg}}) center/cover no-repeat;">
                    <div class="porto-u-heading m-t-sm p-t-xs text-start text-lg-end" data-appear-animation="fadeInLeft" data-appear-animation-delay="100">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; color: #ffffff; margin-bottom: 2px; font-size: 2.8125em; line-height: 1; letter-spacing: 0.02em;">RARE WINES</h2>
                        </div>
                        <div class="porto-u-sub-heading" style="font-weight: 600; color: rgba(255, 255, 255, 0.5); font-size: 14.65px; line-height: 1; letter-spacing: 0.21em;">Incredible Discounts</div>
                    </div>
                    <div class="porto-u-heading coupon-sale ms-0 ms-lg-auto mb-0 me-2 text-start text-lg-end" data-appear-animation="fadeInRight" data-appear-animation-delay="200">
                        <div class="porto-u-main-heading">
                            <h3 style="font-weight: 700; color: #ffffff; margin-bottom: 23px; font-size: 17.6px; line-height: 1; letter-spacing: -0.02em;">
                                only<strong><sup>$</sup>39<sup>99</sup></strong>
                            </h3>
                        </div>
                        <div class="porto-u-sub-heading" style="">
                            <a class="btn btn-default btn-md btn-modern text-body font-weight-semibold text-sm" style="padding: 13px 18px;" href="#">Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="custom-cta-2 m-b-md vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner" style="background: #c5c6ca url({{media url=wysiwyg/smartwave/porto/homepage/37/banner-2.jpg}})center/cover no-repeat">
                    <div class="porto-u-heading ms-1 mb-0" data-appear-animation="fadeInRight" data-appear-animation-delay="50">
                        <div class="porto-u-main-heading">
                            <h4 style="font-weight: 800; font-size: 2.5rem; line-height: 1;">Top<i>10+</i></h4>
                        </div>
                    </div>
                    <div class="porto-u-heading ms-1" data-appear-animation="fadeInRight" data-appear-animation-delay="150" style="margin-bottom: 17px;">
                        <div class="porto-u-main-heading">
                            <h4 style="font-weight: 700; font-size: 20px; line-height: 1;">Under<b>$100</b></h4>
                        </div>
                    </div>
                    <div class="vc_btn3-container ms-1 mb-4 pb-1 d-inline">
                        <a
                            data-appear-animation="fadeInUp"
                            data-appear-animation-delay="200"
                            class="vc_btn3 d-inline-block vc_btn3-shape-square btn text-body btn-md btn-light"
                            style="font-size: 0.9375em; font-weight: 600; padding: 13px 19px;"
                            href="#"
                            title="Shop"
                        >
                            SHOP NOW
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row porto-inner-container" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 44px; font-size: 18px; line-height: 1; letter-spacing: 0.2em;">FEATURED WINES</h2>
                        </div>
                    </div>
                    <div id="bestseller-products" class="porto-products wpb_content_element custom-nav-2 m-b-lg theme_option">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="dots-style-1 nav-center-images-only nav-style-1 nav-inside show-nav-hover" product_count="8" aspect_ratio="0"
                            image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#bestseller-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 4,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div
    class="vc_row wpb_row top-row vc_row-has-fill porto-inner-container"
    style="background: #f5f5f5 url({{media url=wysiwyg/smartwave/porto/homepage/37/testimonial.jpg}}) center/cover no-repeat;margin-bottom: 53px;padding-top: 59px;padding-bottom: 35px;"
>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="mx-auto vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <style>
                        .mx-auto {
                            margin-right: auto !important;
                            margin-left: auto !important;
                        }
                        .testimonial {
                            display: flex;
                            flex-direction: column;
                        }
                        .testimonial.testimonial-style-6 blockquote {
                            padding: 0;
                        }
                        .testimonial .testimonial-author {
                            order: 2;
                        }
                        .testimonial.testimonial-with-quotes img {
                            margin: 31px auto 3px;
                            order: 1;
                            width: 74px !important;
                        }
                        .testimonial.testimonial-with-quotes blockquote:before {
                            left: -45px;
                            top: -16px;
                            font-size: 64px;
                        }
                        .testimonial.testimonial-with-quotes blockquote:after {
                            right: -27px;
                            bottom: -0.8em;
                            font-size: 64px;
                        }
                        .testimonial blockquote,
                        .testimonial blockquote p {
                            font-family: Georgia, serif;
                        }
                        .testimonial blockquote:before {
                            font-family: inherit;
                        }
                        .testimonial blockquote p {
                            padding: 0 !important;
                            font-family: Poppins, sans-serif;
                            font-size: 17px !important;
                            font-style: italic;
                            color: #777;
                        }
                        .testimonial .testimonial-author strong {
                            position: relative;
                            font-size: 15px;
                            font-family: "Spectral SC";
                            letter-spacing: 0.05em;
                        }
                        @media (max-width: 991px) {
                            .testimonial.testimonial-with-quotes blockquote:before,
                            .testimonial.testimonial-with-quotes blockquote:after {
                                content: none;
                            }
                        }
                    </style>
                    <div class="porto-carousel porto-testimonial-carousel owl-carousel has-ccols ccols-1 nav-inside custom-nav-2 nav-style-1 show-nav-hover" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                        <div class="porto-testimonial wpb_content_element col-lg-8 mx-auto py-4">
                            <div class="testimonial testimonial-style-6 testimonial-with-quotes">
                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/37/avatar.png}}" alt="MARY DOE" width="74" height="74" />
                                <blockquote class="testimonial-carousel" style="color: #222529;">
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempor tempus rhoncus. Sed et magna quis nisi iaculis consectetur. Nullam molestie sed dui at volutpat. Morbi porta malesuada tortor,
                                        eu hendrerit lectus.
                                    </p>
                                </blockquote>
                                <div class="testimonial-author">
                                    <p>
                                        <strong>MARY DOE</strong>
                                        <span></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="porto-testimonial wpb_content_element col-lg-8 mx-auto py-4">
                            <div class="testimonial testimonial-style-6 testimonial-with-quotes">
                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/37/avatar.png}}" alt="MARY DOE" width="74" height="74" />
                                <blockquote class="testimonial-carousel" style="color: #222529;">
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempor tempus rhoncus. Sed et magna quis nisi iaculis consectetur. Nullam molestie sed dui at volutpat. Morbi porta malesuada tortor,
                                        eu hendrerit lectus.
                                    </p>
                                </blockquote>
                                <div class="testimonial-author">
                                    <p>
                                        <strong>MARY DOE</strong>
                                        <span></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".porto-testimonial-carousel.owl-carousel").owlCarousel({
                                items: 1,
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                dots: false,
                                nav: true,
                                loop: false,
                                navRewind: true,
                                margin: 1,
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row porto-inner-container" data-appear-animation="fadeIn" data-appear-animation-delay="50" style="margin-bottom: 32px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 44px; font-size: 18px; line-height: 1; letter-spacing: 0.2em;">STAFF FAVORITES</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products">
                            {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row m-b-xl p-b-xs no-padding porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row no-padding">
            <div class="custom-cta-3 background-color-primary vc_column_container col-md-12" style="padding: 25px 20px;">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading me-md-3 me-0 text-center text-md-start mb-0" data-appear-animation="fadeInLeft" data-appear-animation-delay="150">
                        <div class="porto-u-main-heading">
                            <h4 style="font-weight: 700; color: #ffffff; font-size: 22.86px; line-height: 1; letter-spacing: 0.22em;">WINE SPECTATOR'S TOP <em>100</em></h4>
                        </div>
                        <div class="porto-u-sub-heading" style="font-weight: 500; color: rgba(255, 255, 255, 0.5); letter-spacing: -0.02em;">Check Now This Year’s List</div>
                    </div>
                    <div class="vc_btn3-container ms-1 mb-0 d-inline">
                        <a
                            data-appear-animation="fadeInLeft"
                            data-appear-animation-delay="200"
                            class="vc_btn3 vc_btn3-shape-square d-inline-block text-body btn btn-md btn-light"
                            style="font-size: 0.9375em; font-weight: 700; padding: 1em 2.533em;"
                            href="#"
                            title="Shop"
                        >
                            SHOP NOW
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row porto-inner-container" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 44px; font-size: 18px; line-height: 1; letter-spacing: 0.2em;">FROM THE BLOG</h2>
                        </div>
                    </div>
                    <div class="porto-recent-posts porto-blog wpb_content_element mb-0 custom-nav-2">
                        <div class="posts-container owl-carousel porto-carousel nav-inside has-ccols nav-style-1 show-nav-hover">
                            {{widget type="Magefan\Blog\Block\Widget\Recent" number_of_posts="4" custom_template="recent_home.phtml"}}
                        </div>
                        <style>
                            .porto-recent-posts .post-item {
                                padding: 0;
                                position: relative;
                                padding: 1.5rem 1.2rem 1.8rem;
                                background: #f4f4f4;
                            }
                            .porto-recent-posts .post-slide {
                                margin-bottom: 30px;
                            }
                            .porto-recent-posts .post-item .post-date {
                                top: 24px;
                                left: 19px;
                            }
                            .porto-recent-posts h4 {
                                margin: 0.7rem 0 0.4rem;
                                font-size: 20px;
                                letter-spacing: -0.025em;
                                line-height: 1.3;
                                font-weight: 600;
                                font-family: Poppins, sans-serif;
                            }
                            .porto-recent-posts .post-item .post-excerpt {
                                font-size: 14px;
                                margin-bottom: 0;
                            }
                            .post-item .read-more,
                            .post-item .read-more-block {
                                display: block;
                                color: #1a1a1a;
                                font-size: 13px;
                                letter-spacing: -0.025em;
                                font-weight: 700;
                                margin-top: 0.9rem;
                                text-transform: uppercase;
                            }
                        </style>
                        <script type="text/javascript">
                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                $(".porto-recent-posts .owl-carousel").owlCarousel({
                                    autoplay: false,
                                    autoplayTimeout: 5000,
                                    autoplayHoverPause: true,
                                    loop: false,
                                    navRewind: true,
                                    lazyLoad: true,
                                    margin: 20,
                                    nav: true,
                                    dots: false,
                                    responsive: {
                                        0: {
                                            items: 1,
                                        },
                                        640: {
                                            items: 1,
                                        },
                                        768: {
                                            items: 2,
                                        },
                                        992: {
                                            items: 2,
                                        },
                                        1200: {
                                            items: 3,
                                        },
                                    },
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row custom-service no-padding porto-inner-container" data-appear-animation="fadeIn" data-appear-animation-delay="50">
    <div class="porto-wrap-container container">
        <div class="row no-padding">
            <div class="vc_column_container col-md-12" style="margin-bottom: 52px; padding-top: 23px; padding-bottom: 23px; border: solid 1px #e7e7e7;">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-carousel home-bar owl-carousel has-ccols ccols-xl-3 ccols-lg-3 ccols-md-2 ccols-1 mb-0">
                        <div class="porto-sicon-box mb-0 justify-content-center style_1 default-icon" style="padding-top: 14px; padding-bottom: 14px; border-right: 1px solid #e7e7e7;">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 39px;">
                                    <i class="porto-icon-shipping"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h4 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 15px; letter-spacing: 0; margin-bottom: 0px;">FREE SHIPPING & RETURN</h4>
                                <p style="font-weight: 300; font-size: 13px; line-height: 22px; letter-spacing: -0.01em;">Free shipping on all orders over $99.</p>
                            </div>
                            <!-- header -->
                        </div>
                        <div class="porto-sicon-box mb-0 justify-content-center style_1 default-icon" style="padding-top: 14px; padding-bottom: 14px; border-right: 1px solid #e7e7e7;">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 39px;">
                                    <i class="porto-icon-money"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h4 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 15px; letter-spacing: 0; margin-bottom: 0px;">MONEY BACK GUARANTEE</h4>
                                <p style="font-weight: 300; font-size: 13px; line-height: 22px; letter-spacing: -0.01em;">100% money back guarantee</p>
                            </div>
                            <!-- header -->
                        </div>
                        <div class="porto-sicon-box mb-0 justify-content-center style_1 default-icon" style="padding-top: 14px; padding-bottom: 14px;">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 39px;">
                                    <i class="porto-icon-support"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h4 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 15px; letter-spacing: 0; margin-bottom: 0px;">ONLINE SUPPORT 24/7</h4>
                                <p style="font-weight: 300; font-size: 13px; line-height: 22px; letter-spacing: -0.01em;">Lorem ipsum dolor sit amet.</p>
                            </div>
                            <!-- header -->
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".home-bar.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 1,
                                    },
                                    640: {
                                        items: 2,
                                    },
                                    768: {
                                        items: 2,
                                    },
                                    992: {
                                        items: 3,
                                    },
                                    1200: {
                                        items: 3,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
            <div class="instagram mb-4 pb-2 vc_column_container col-md-12" data-appear-animation="fadeIn" data-appear-animation-delay="150">
                <style>
                    .photo-instagrams {
                        margin-bottom: 20px !important;
                    }
                    .instagram small {
                        text-decoration: underline;
                        font-size: 14px;
                        letter-spacing: 0.2em;
                        font-weight: 700;
                    }
                </style>
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 44px; font-size: 18px; line-height: 1; letter-spacing: 0.2em;">FROM INSTAGRAM - <small>@PORTOWINESHOP</small></h2>
                        </div>
                    </div>
                    {{block class="Smartwave\Porto\Block\Template" name="instagram" margin="20" template_type="carousel" media_type="album" album_name="Demo37" desktop="4" tablet="3" mobile="2"
                    template="Smartwave_SocialFeed::instagramphotos.phtml"}}
                </div>
            </div>
        </div>
    </div>
</div>
