<style>
    .p-b-md {
        padding-bottom: 20px;
    }
    .p-t-md {
        padding-top: 20px;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .banner-effect,
    .banner-effect-wrapper {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 3;
    }
    .porto-ibanner-layer .btn-modern.btn-lg {
        font-size: 0.875em;
        padding: 1.375em 3.65em;
    }
    .home-banner-slider em,
    .home-banner em {
        color: #b93027;
        font-family: inherit;
        font-style: normal;
        margin-left: 0.375em;
    }
    .home-slider-banner-text {
        transform: translateY(30%);
    }
    .home-slider-banner-text2 {
        transform: translateY(54%);
    }
    .home-banner-slider strong,
    .home-banner strong {
        font-size: 220%;
        vertical-align: text-top;
        line-height: 0.9;
    }
    .owl-carousel.nav-style-4 .owl-nav [class*="owl-"]:before {
        content: "";
        display: block;
        width: 0.9em;
        height: 0.9em;
        border-width: 1.5px 1.5px 0 0;
        border-style: solid;
        border-color: #222529;
        transform: translateX(-50%) rotate(45deg) skew(10deg, 10deg);
    }
    .owl-carousel.nav-style-4 .owl-nav .owl-prev:before {
        transform: translateX(20%) rotate(-135deg) skew(10deg, 10deg);
    }
    .particle-effect {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
    }
    .snowfall {
        background-image: url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/s1.png}}), url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/s2.png}}), url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/s3.png}});
        animation: snow 10s linear infinite;
        z-index: 1;
    }

    @keyframes snow {
        0% {
            background-position: 0 0, 0 0, 0 0;
        }

        50% {
            background-position: 500px 500px, 100px 300px, -200px 250px;
        }

        to {
            background-position: 400px 800px, 300px 600px, -200px 400px;
        }
    }

    .effect-snow {
        background-image: url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/s4.png}}), url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/s5.png}});
        animation: snowsecond 20s linear infinite;
    }

    @keyframes snowsecond {
        0% {
            background-position: 0 0, 0 0, 0 0;
        }

        to {
            background-position: 500px 1000px, 400px 400px, 300px 300px;
        }
    }
    .sparkle {
        background-image: url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/sparkle1.png}}), url({{mediaurl=wysiwyg/smartwave/porto/homepage/32/sparkle2.png}});
        animation: sparkle 60s linear infinite;
    }

    @keyframes sparkle {
        0% {
            background-position: 0 0, 0 0, 0 0;
        }

        to {
            background-position: -500px -1000px, -400px -400px, 300px 300px;
        }
    }
</style>
<div class="vc_row wpb_row row home-banner-slider no-padding">
    <div class="vc_column_container col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div id="banner-slider-demo-32" class="porto-carousel home-banner-slider owl-carousel mb-5 nav-pos-inside nav-style-4 show-nav-hover">
                <div class="porto-ibanner mb-0" style="background: #f7e1e8; min-height: 400px;">
                    <div class="banner-effect-wrapper">
                        <div class="banner-effect"><div class="particle-effect snowfall"></div></div>
                    </div>
                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1.jpg}}" />
                    <div class="porto-ibanner-desc no-padding d-flex">
                        <div class="porto-ibanner-layer pl-2 pb-2" style="width: 10%; left: 0%; bottom: 0%;">
                            <div class="wpb_single_image wpb_content_element vc_align_left mb-0">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1_dots.png}}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="porto-ibanner-layer home-slider-banner-text" style="width: 66.6666%; left: 12%; bottom: 0%;">
                            <div class="wpb_single_image wpb_content_element vc_align_left">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1_text.png}}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="porto-ibanner-layer" style="left: 11.5%; top: 50%; transform: translateY(-50%); max-width: 825px;">
                            <div>
                                <h4 style="font-size: 1.375em; line-height: 1; font-weight: 600; letter-spacing: 0.2em;" class="vc_custom_heading mb-2 align-left">New Amazing Collection</h4>
                                <h2 style="font-size: 5.375em; line-height: 1;" class="vc_custom_heading mb-4 pr-3 align-left">Summer Beauty Sale</h2>
                                <p style="font-size: 1.375em; color: #777777; line-height: 1.5; font-weight: 300; letter-spacing: -0.015em;" class="vc_custom_heading mb-4 pb-xl-1 mw-fit align-left">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ullamcorper quam lacus, et suscipit lectus porta efficitur.
                                </p>
                                <h5 style="font-size: 1.125em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-lg-3 align-left">STARTING AT <em>$<strong>39</strong>99</em></h5>
                                <div class="btn-container d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-light">Shop Now</button></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="porto-ibanner mb-0" style="background: #f7e1e8; min-height: 400px;">
                    <div class="banner-effect-wrapper">
                        <div class="banner-effect"><div class="particle-effect sparkle"></div></div>
                    </div>
                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide2.jpg}}" />
                    <div class="porto-ibanner-desc no-padding d-flex">
                        <div class="porto-ibanner-layer pl-2 pb-2" style="width: 10%; left: 0%; bottom: 0%;">
                            <div class="wpb_single_image wpb_content_element vc_align_left mb-0">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1_dots.png}}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="porto-ibanner-layer home-slider-banner-text2" style="width: 78%; left: 11%; bottom: 0%;">
                            <div class="wpb_single_image wpb_content_element vc_align_left">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide2_text.png}}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="porto-ibanner-layer text-right" style="right: 11.5%; top: 50%; transform: translateY(-50%); max-width: 825px;">
                            <div>
                                <h4 style="font-size: 1.375em; line-height: 1; font-weight: 600; letter-spacing: 0.2em;" class="vc_custom_heading mb-2 align-right">Back In Stock</h4>
                                <h2 style="font-size: 5.375em; line-height: 1;" class="vc_custom_heading mb-4 align-right">Ultimate SkinCare</h2>
                                <p style="font-size: 1.375em; color: #777777; line-height: 1.5; font-weight: 300; letter-spacing: -0.015em;" class="vc_custom_heading mb-4 pb-xl-1 mw-fit align-right">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lori ullamcorper quam lacus, et suscipit lectus porta efficitur.
                                </p>
                                <h5 style="font-size: 1.125em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading d-inline-block mr-4 mr-xl-5 pr-lg-3 align-left">STARTING AT <em>$<strong>39</strong>99</em></h5>
                                <div class="btn-container d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-light">Shop Now</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                    var banner_owl = $("#banner-slider-demo-32");
                    banner_owl.owlCarousel({
                        items: 1,
                        autoplay: false,
                        autoplayTimeout: 5000,
                        autoplayHoverPause: true,
                        dots: false,
                        nav: true,
                        navRewind: true,
                        animateIn: "fadeIn",
                        animateOut: "fadeOut",
                        loop: true,
                        lazyLoad: true,
                    });
                });
            </script>
        </div>
    </div>
</div>
<div class="vc_row wpb_row porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 2.125rem; line-height: 1;" class="vc_custom_heading mb-2 align-left">Shop By Category</h2>
                    <h5 style="font-size: 1rem; color: rgb(119, 119, 119); line-height: 1.2; font-weight: 300; letter-spacing: -0.025em; border-bottom: 1px #e7e7e7 solid;" class="vc_custom_heading m-b-md pb-4">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <style scope="scope">
                        .home-banner-category .grid-creative {
                            opacity: 0;
                        }
                        .home-banner-category .grid-creative {
                            margin-left: -10px;
                            margin-right: -10px;
                            width: calc(100% + 20px);
                            display: flex;
                            flex-wrap: wrap;
                        }
                        .home-banner-category .product-col {
                            padding: 0 10px 20px;
                        }
                        .grid-creative .thumb-info,
                        .grid-creative .thumb-info .thumb-info-wrapper {
                            height: 100%;
                        }
                        .grid-creative .thumb-info img {
                            object-fit: cover;
                            width: 100%;
                            height: 100%;
                            padding: 0;
                        }
                        ul.products li {
                            margin: 0;
                        }
                        ul.products li.product-category .thumb-info h3 {
                            font-size: inherit;
                            letter-spacing: 0.2em;
                            font-weight: 600;
                            text-transform: none;
                        }
                        ul.products li.product-category .thumb-info h3:after {
                            content: "";
                            display: inline-block;
                            width: 0.55em;
                            height: 0.55em;
                            border-width: 1px 1px 0 0;
                            margin-left: 0.3em;
                            transform: rotate(45deg) skew(12deg, 12deg);
                            transition: margin-left 0.3s;
                            border-style: solid;
                        }
                        li.product-category .sub-categories {
                            font-weight: 300;
                            letter-spacing: -0.025em;
                        }
                        li.product-category .thumb-info-title a:hover {
                            color: inherit;
                            text-decoration: underline;
                        }
                        ul.products li.product-category .thumb-info-title {
                            width: auto;
                            padding-right: 0;
                        }
                        ul.products li.product-col h3 {
                            line-height: 1.35;
                        }
                        .home-banner-category .grid-col-1-4 {
                            flex: 0 0 25%;
                            width: 25%;
                        }
                        .home-banner-category .grid-col-1-2 {
                            flex: 0 0 50%;
                            width: 50%;
                        }
                        .home-banner-category .grid-col-sizer {
                            flex: 0 0 25%;
                            width: 25%;
                        }
                        .home-banner-category .grid-height-3-5 {
                            height: 360px;
                        }
                        .home-banner-category .grid-height-1 {
                            height: 600px;
                        }
                        .home-banner-category .grid-height-2-5 {
                            height: 240px;
                        }
                        .thumb-info .thumb-info-title {
                            font-size: 1.25rem;
                        }
                        @media (max-width: 767px) {
                            .home-banner-category .grid-col-md-1-2 {
                                flex: 0 0 50%;
                                width: 50%;
                            }
                            .home-banner-category .grid-col-md-1-2 {
                                flex: 0 0 50%;
                                width: 50%;
                            }
                            .home-banner-category .grid-col-sizer {
                                flex: 0 0 50%;
                                width: 50%;
                            }
                            .home-banner-category .grid-height-3-5 {
                                height: 360px;
                            }
                            .home-banner-category .grid-height-1 {
                                height: 480px;
                            }
                            .home-banner-category .grid-height-2-5 {
                                height: 240px;
                            }
                        }
                        @media (max-width: 480px) {
                            .home-banner-category .product-col {
                                flex: 0 0 100%;
                                width: 100%;
                            }
                        }
                    </style>
                    <style>
                        .home-banner-category ul.products li.product-category .thumb-info-wrapper:after {
                            background-color: rgba(27, 27, 23, 0);
                        }
                        .home-banner-category ul.products li.product-category:hover .thumb-info-wrapper:after {
                            background-color: rgba(27, 27, 23, 0.15);
                        }
                    </style>
                    <div class="home-banner-category porto-products wpb_content_element hide-count">
                        <div class="columns-4">
                            <ul class="products products-container grid-creative category-pos-bottom category-text-left category-color-dark show-nav-middle is-shortcode" style="position: relative; height: 600px;">
                                <li class="product-category product-col grid-col-1-4 grid-col-md-1-2 grid-height-3-5">
                                    <div class="thumb-info align-center">
                                        <a href="#">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_cat1.jpg}}" />
                                            </div>
                                        </a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-23"><a href="#">Bath & Shower</a></li>
                                                    <li class="cat-item cat-item-24"><a href="#">Body Care</a></li>
                                                    <li class="cat-item cat-item-27"><a href="#">Body Sculpting</a></li>
                                                    <li class="cat-item cat-item-26"><a href="#">Foot Care</a></li>
                                                    <li class="cat-item cat-item-25"><a href="#">Handcare</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Body</h3></a><span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col grid-col-1-2 grid-col-md-1-2 grid-height-1">
                                    <div class="thumb-info align-center">
                                        <a href="#">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_cat2.jpg}}" />
                                            </div>
                                        </a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-28"><a href="#">Cleansers</a></li>
                                                    <li class="cat-item cat-item-30"><a href="#">Exfoliators</a></li>
                                                    <li class="cat-item cat-item-33"><a href="#">Eye Care</a></li>
                                                    <li class="cat-item cat-item-32"><a href="#">Face Masks</a></li>
                                                    <li class="cat-item cat-item-34"><a href="#">Lip Care</a></li>
                                                    <li class="cat-item cat-item-31"><a href="#">Serums</a></li>
                                                    <li class="cat-item cat-item-29"><a href="#">Toners</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Skincare</h3></a>
                                                <span class="thumb-info-type"><mark class="count">5</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col grid-col-1-4 grid-col-md-1-2 grid-height-2-5">
                                    <div class="thumb-info align-center">
                                        <a href="#">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_cat3.jpg}}" />
                                            </div>
                                        </a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-35"><a href="#">Complexion</a></li>
                                                    <li class="cat-item cat-item-37"><a href="#">Eyes</a></li>
                                                    <li class="cat-item cat-item-38"><a href="#">Lips</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Makeup</h3></a><span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col grid-col-1-4 grid-col-md-1-2 grid-height-3-5">
                                    <div class="thumb-info align-center">
                                        <a href="#">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_cat4.jpg}}" />
                                            </div>
                                        </a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-43"><a href="#">Body & Hair Mist</a></li>
                                                    <li class="cat-item cat-item-44"><a href="#">Fragrance</a></li>
                                                    <li class="cat-item cat-item-45"><a href="#">Perfume</a></li>
                                                    <li class="cat-item cat-item-46"><a href="#">Soap</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Fragrance</h3></a>
                                                <span class="thumb-info-type"><mark class="count">3</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col grid-col-1-4 grid-col-md-1-2 grid-height-2-5">
                                    <div class="thumb-info align-center">
                                        <a href="#">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_cat3.jpg}}" />
                                            </div>
                                        </a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-49"><a href="#">Conditioner</a></li>
                                                    <li class="cat-item cat-item-48"><a href="#">Shampoo</a></li>
                                                    <li class="cat-item cat-item-51"><a href="#">Styling</a></li>
                                                    <li class="cat-item cat-item-50"><a href="#">Treatments</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Hair</h3></a><span class="thumb-info-type"><mark class="count">3</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="grid-col-sizer"></li>
                            </ul>
                            <script type="text/javascript">
                                require(["jquery", "imagesloaded", "packery"], function ($, imagesLoaded, Packery) {
                                    $.bridget("packery", Packery);
                                    var $container = $(".home-banner-category .grid-creative");
                                    $container.css("opacity", 0);
                                    if ($container.length > 0) {
                                        $container.imagesLoaded(function () {
                                            $container.packery({
                                                itemSelector: ".product-col",
                                                columnWidth: ".grid-col-sizer",
                                                percentPosition: true,
                                            });
                                        });
                                        setTimeout(function () {
                                            $container.animate(
                                                {
                                                    opacity: 1,
                                                },
                                                200
                                            );
                                        }, 500);
                                    }
                                });
                            </script>
                        </div>
                    </div>
                    <h2 style="font-size: 2.125rem; line-height: 1;" class="vc_custom_heading mb-2 align-left">
                        Recommended Products
                    </h2>
                    <h5 style="font-size: 1rem; color: rgb(119, 119, 119); line-height: 1.2; font-weight: 300; letter-spacing: -0.025em; border-bottom: 1px #e7e7e7 solid;" class="vc_custom_heading mb-4 pb-4 align-left">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <style>
                        .product.data.items > .item.title {
                            color: #333;
                            border-bottom-width: 1px;
                            font-size: 0.8125rem;
                            font-weight: 400;
                            letter-spacing: -0.025em;
                            text-transform: uppercase;
                            line-height: 1.5;
                        }
                        .product.data.items > .item.title:hover {
                            border-color: #333;
                            color: #333;
                        }
                        .product.data.items > .item.title > .switch {
                            font-size: inherit;
                        }
                        .product.data.items > .item.title.active {
                            color: #333;
                            border-color: #333;
                        }
                        .tabs.tabs-simple .section-title {
                            text-align: left;
                        }
                        @media (min-width: 1024px) {
                            .tabs.tabs-simple .section-title {
                                margin: 0;
                                margin-bottom: -28px;
                                padding-top: 3px;
                            }
                        }
                        @media (min-width: 768px) {
                            .product.data.items {
                                text-align: center;
                            }
                            .product.data.items > .item.title {
                                float: none;
                                display: inline-block;
                                padding: 0;
                                text-decoration: none;
                                margin: 0 1.5rem 1rem;
                            }
                            .product.data.items > .item.content {
                                border-top: none;
                                margin-top: 1.75rem;
                            }
                        }
                        @media (max-width: 767px) {
                            .tabs.tabs-simple {
                                margin-bottom: 30px;
                            }
                        }
                    </style>
                    <div class="tabs tabs-simple pt-2">
                        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active","collapsible":"true"}}'>
                            <div class="data item title" aria-labeledby="tab-label-tab1-title" data-role="collapsible" id="tab-label-tab1">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab1" id="tab-label-tab1-title">
                                    <span>Kitchen</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab1" data-role="content">
                                <div id="tab1-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab1-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab2-title" data-role="collapsible" id="tab-label-tab2">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2" id="tab-label-tab2-title">
                                    <span>What's New</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab2" data-role="content">
                                <div id="tab2-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab2-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab3-title" data-role="collapsible" id="tab-label-tab3">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab3" id="tab-label-tab3-title">
                                    <span>Best Rating</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab3" data-role="content">
                                <div id="tab3-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab3-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab4-title" data-role="collapsible" id="tab-label-tab4">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab4" id="tab-label-tab4-title">
                                    <span>Body</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab4" data-role="content">
                                <div id="tab4-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab4-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab5-title" data-role="collapsible" id="tab-label-tab5">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab5" id="tab-label-tab5-title">
                                    <span>Fragrance</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab5" data-role="content">
                                <div id="tab5-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab5-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab6-title" data-role="collapsible" id="tab-label-tab6">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab6" id="tab-label-tab6-title">
                                    <span>Hair</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab6" data-role="content">
                                <div id="tab6-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab6-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab7-title" data-role="collapsible" id="tab-label-tab7">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab7" id="tab-label-tab7-title">
                                    <span>Makeup</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab7" data-role="content">
                                <div id="tab7-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab7-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab8-title" data-role="collapsible" id="tab-label-tab8">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab8" id="tab-label-tab8-title">
                                    <span>Skincare</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab8" data-role="content">
                                <div id="tab8-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab8-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 3,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h2 style="font-size: 2.125rem; line-height: 1;" class="vc_custom_heading mb-2 align-left">
                        Shop by Brands
                    </h2>
                    <h5 style="font-size: 1rem; color: rgb(119, 119, 119); line-height: 1.2; font-weight: 300; letter-spacing: -0.025em; border-bottom: 1px #e7e7e7 solid;" class="vc_custom_heading mb-2 pb-4 align-left">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <div class="porto-carousel brand-carousel owl-carousel mb-5">
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand1.png}}" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand2.png}}" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand3.png}}" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand4.png}}" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand5.png}}" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="p-t-md p-b-md" style="border: 4px solid #e7e7e7;">
                                <img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand6.png}}" alt="" />
                            </div>
                        </div>
                    </div>
                    <style>
                        .brand-carousel .owl-stage-outer {
                            padding: 1rem;
                            margin: 0 -1rem !important;
                        }
                    </style>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".brand-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 20,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 3,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 6,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div
    class="vc_row wpb_row section-review vc_row-has-fill porto-inner-container"
    style="background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_review_bg_text.png}}');
            padding-top: 80px;
            padding-bottom: 60px;
            background-color: #f7e1e8;
            background-position: 50% calc(100% + 4.5vw);
            background-repeat: no-repeat;
            background-size: 92% auto;"
>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <style>
                        .owl-carousel.dots-style-1 .owl-dots span,
                        .products-slider.owl-carousel .owl-dot span {
                            border-color: #222529;
                        }
                        .owl-carousel.dots-style-1 .owl-dots span {
                            margin: 2px;
                        }
                        .porto-vc-testimonial blockquote,
                        .testimonial blockquote,
                        .testimonial blockquote p {
                            font-family: Playfair Display, Georgia, serif;
                        }
                        .testimonial blockquote p {
                            font-size: 1.375rem;
                            line-height: 1.4;
                            font-style: italic;
                        }
                        .testimonial blockquote p:before {
                            content: "“";
                            font-size: 250%;
                            margin-right: 0.5rem;
                        }
                        .testimonial.testimonial-style-2 .testimonial-author {
                            margin: 0;
                        }
                        .testimonial.testimonial-style-2 .testimonial-author p {
                            text-align: center;
                            padding: 0;
                            margin: 0;
                        }
                        .testimonial .testimonial-author strong {
                            font-size: 1.125rem;
                            letter-spacing: -0.025em;
                            font-weight: 300;
                            color: #555;
                        }
                        .testimonial .testimonial-author strong:before {
                            content: "-";
                            margin-right: 0.25rem;
                        }
                    </style>
                    <h2 style="font-size: 2.125rem; line-height: 1; text-align: center;" class="vc_custom_heading mb-2">Clients Reviews</h2>
                    <h5 style="font-size: 1rem; color: #777777; line-height: 1.2; text-align: center; font-weight: 300; letter-spacing: -0.025em;" class="vc_custom_heading mb-0">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <div class="testimonial-carousel owl-carousel dots-style-1 stage-margin nav-pos-outside nav-style-4 show-nav-hover">
                        <div class="porto-testimonial wpb_content_element">
                            <div class="testimonial testimonial-style-2 testimonial-no-borders testimonial-transparent-background">
                                <blockquote style="color: #222529;"><p>I really love it. At first it does feel strange and a little sore after! But keep it up (I use morning and night) and my skin feels great.</p></blockquote>
                                <div class="testimonial-author clearfix">
                                    <p><strong>Mary Doe</strong><span></span></p>
                                </div>
                            </div>
                        </div>
                        <div class="porto-testimonial wpb_content_element">
                            <div class="testimonial testimonial-style-2 testimonial-no-borders testimonial-transparent-background">
                                <blockquote style="color: #222529;"><p>I really love it. At first it does feel strange and a little sore after! But keep it up (I use morning and night) and my skin feels great.</p></blockquote>
                                <div class="testimonial-author clearfix">
                                    <p><strong>Mary Doe</strong><span></span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".testimonial-carousel.owl-carousel").owlCarousel({
                                items: 1,
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: true,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                stagePadding: 40,
                                nav: true,
                                dots: true,
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row py-5 porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <style>
                        .home-mid-banner > img {
                            object-position: left;
                        }
                        .porto-ibanner-layer {
                            position: absolute;
                            z-index: 10;
                        }
                        .home-mid-banner small {
                            font-family: Poppins;
                            font-size: 20%;
                            letter-spacing: -0.02em;
                            font-weight: 700;
                            vertical-align: text-bottom;
                            position: relative;
                            top: -0.375em;
                        }
                        sup {
                            top: -0.5em;
                        }
                        .home-mid-banner small sub {
                            bottom: -0.5em;
                        }
                        .porto-ibanner-layer .btn-modern.btn-lg {
                            font-size: 0.875em;
                            padding: 1.375em 3.65em;
                        }
                    </style>
                    <h2 style="font-size: 2.125rem; line-height: 1;" class="vc_custom_heading mb-2 align-left">Best Selling Products</h2>
                    <h5 style="font-size: 1rem; color: #777777; line-height: 1.2; font-weight: 300; letter-spacing: -0.025em; border-bottom: 1px solid #e7e7e7;" class="vc_custom_heading m-b-md pb-4 align-left">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <div class="vc_row wpb_row vc_inner row">
                        <div class="vc_column_container col-md-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ibanner home-mid-banner m-b-md" style="background: #f4f4f4; min-height: 320px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_mid_banner.png}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer" style="right: 12%; top: 50%; transform: translateY(-50%);">
                                            <h3 style="font-size: 1.5em; line-height: 1; font-weight: 600; letter-spacing: 0.2em; margin-right: -0.2em;" class="vc_custom_heading mb-0 align-right">FRAGRANCE OFFERS</h3>
                                            <h4 style="font-size: 9.375em; line-height: 1; font-weight: 700; margin-right: 0.06em;" class="vc_custom_heading custom-font1 mb-0 align-right">
                                                <small><sup>UP</sup><sub>TO</sub></small><i>45%</i>
                                            </h4>
                                            <h6 style="font-size: 2.5em; line-height: 1; font-weight: 700; letter-spacing: -0.02em; margin-top: -0.65em;" class="vc_custom_heading mb-4 pb-2 align-right">OFF</h6>
                                            <div class="btn-container pt-1 text-right"><a class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark" href="#" title="">shop now</a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="vc_column_container col-md-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div id="bestseller-products" class="porto-products wpb_content_element dots-style-1 mb-2">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="dots-style-1" product_type="3" product_count="4" aspect_ratio="0" image_width="350"
                                        image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#bestseller-products .owl-carousel").owlCarousel({
                                                    autoplay: false,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: false,
                                                    dots: true,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 2,
                                                        },
                                                        1200: {
                                                            items: 2,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .home-banner .pc-pos-r-b {
        position: absolute;
        right: 0;
        bottom: 0;
        margin: 0 0.5rem 0.5rem 0;
        transform: scaleX(-1);
        z-index: 1;
        max-width: 20%;
    }
    .home-banner .pc-pos-l-t {
        position: absolute;
        left: 0;
        top: 0;
        margin: 0.5rem 0 0 0.5rem;
        transform: scaleY(-1);
        z-index: 1;
        max-width: 20%;
    }
</style>
<div class="vc_row wpb_row row home-banner no-padding">
    <div class="vc_column_container col-md-12 col-lg-6" style="background: url({{media url=wysiwyg/smartwave/porto/homepage/32/shop32_img1.jpg}}) center no-repeat; padding-top: 15em; padding-bottom: 15em; background-color: #f3f3f2;">
        <div class="wpb_wrapper vc_column-inner">
            <div class="wpb_single_image wpb_content_element vc_align_center pc-pos-r-b">
                <div class="wpb_wrapper">
                    <div class="vc_single_image-wrapper vc_box_border_grey">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1_dots.png}}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="porto-ibanner-layer position-static vc_column_container col-md-12 col-lg-6" style="padding: 6% 6.5%;">
        <div class="wpb_wrapper vc_column-inner">
            <h4 style="font-size: 1.125em; line-height: 1; font-weight: 600; letter-spacing: 0.2em;" class="vc_custom_heading mb-1 align-left">Self Care for You</h4>
            <h2 style="font-size: 4.0625em; line-height: 1;" class="vc_custom_heading mb-4 pr-3 align-left">Stay Beauty at Home</h2>
            <p style="font-size: 1.125em; color: #777777; line-height: 1.7; font-weight: 300; letter-spacing: -0.015em;" class="vc_custom_heading mb-5 pb-xl-1 align-left">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ullamcorper quam lacus, et suscipit lectus porta efficitur.
            </p>
            <h5 style="font-size: 1em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-lg-3 align-left">STARTING AT <em>$<strong>39</strong>99</em></h5>
            <div class="btn-container mb-0 d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark">Shop Now</button></div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row row home-banner no-padding">
    <div
        class="order-lg-2 vc_column_container col-md-12 col-lg-6"
        style="background: url({{media url=wysiwyg/smartwave/porto/homepage/32/shop32_img2.jpg}}) center no-repeat;padding-top: 15em; padding-bottom: 15em; background-color: #f4dde4;"
    >
        <div class="wpb_wrapper vc_column-inner">
            <div class="wpb_single_image wpb_content_element vc_align_center pc-pos-l-t">
                <div class="wpb_wrapper">
                    <div class="vc_single_image-wrapper vc_box_border_grey">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_slide1_dots.png}}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="porto-ibanner-layer position-static vc_column_container col-md-12 col-lg-6" style="padding: 6% 6.5%;">
        <div class="wpb_wrapper vc_column-inner">
            <h4 style="font-size: 1.125em; line-height: 1; font-weight: 600; letter-spacing: 0.2em;" class="vc_custom_heading mb-1 align-left">Clear and Glowing Skin</h4>
            <h2 style="font-size: 4.0625em; line-height: 1;" class="vc_custom_heading mb-4 pr-3 align-left">Best Face Masks</h2>
            <p style="font-size: 1.125em; color: #777777; line-height: 1.7; font-weight: 300; letter-spacing: -0.015em;" class="vc_custom_heading mb-5 pb-xl-1 align-left">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ullamcorper quam lacus, et suscipit lectus porta efficitur.
            </p>
            <h5 style="font-size: 1em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-lg-3 align-left">STARTING AT <em>$<strong>39</strong>99</em></h5>
            <div class="btn-container mb-0 d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark">Shop Now</button></div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row pt-3 pt-lg-5 porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-carousel owl-carousel home-features mt-lg-3 mb-5">
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 37px;"><i class="porto-icon-shipping"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1rem; line-height: 1;">FREE SHIPPING & RETURN</h3>
                                <p style="font-weight: 300; font-size: 0.8125rem; line-height: 1.4; letter-spacing: 0.001em;">Free shipping on all orders over $99.</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 37px;"><i class="porto-icon-money"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1rem; line-height: 1;">MONEY BACK GUARANTEE</h3>
                                <p style="font-weight: 300; font-size: 0.8125rem; line-height: 1.4; letter-spacing: 0.001em;">100% money back guarantee</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 37px;"><i class="porto-icon-support"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1rem; line-height: 1;">ONLINE SUPPORT 24/7</h3>
                                <p style="font-weight: 300; font-size: 0.8125rem; line-height: 1.4; letter-spacing: 0.001em;">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                    </div>
                    <style>
                        .home-features {
                            border: 3px solid #e7e7e7;
                            border-right-width: 2px;
                            padding: 1.5rem 0;
                        }
                        .home-features .porto-sicon-box {
                            justify-content: center;
                            border-right: 1px solid #e7e7e7;
                            padding: 0.75rem;
                            margin-bottom: 0;
                        }
                    </style>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".home-features.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: true,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 1,
                                    },
                                    640: {
                                        items: 2,
                                    },
                                    768: {
                                        items: 2,
                                    },
                                    992: {
                                        items: 3,
                                    },
                                    1200: {
                                        items: 3,
                                    },
                                },
                            });
                        });
                    </script>
                    <h2 style="font-size: 2.125rem; line-height: 1;" class="vc_custom_heading mb-2 align-left">
                        Everyday Essentials Collection
                    </h2>
                    <h5 style="font-size: 1rem; color: rgb(119, 119, 119); line-height: 1.2; font-weight: 300; letter-spacing: -0.025em; border-bottom: 1px solid #e7e7e7;" class="vc_custom_heading m-b-md pb-4">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <div class="porto-products wpb_content_element widget-style mb-5">
                        <style>
                            .widget-style .products li.product-item {
                                margin-bottom: 0.25rem;
                            }
                            .product-item-info.type12 {
                                padding: 0;
                            }
                            .product-item-info.type12 .product-item-photo {
                                margin-bottom: 1rem;
                                min-height: 90px;
                                padding-right: 0;
                                flex: 1;
                                max-width: 90px;
                            }
                            .product-item-info.type12 .product-item-details {
                                flex: 1;
                                padding-left: 1rem;
                                max-width: calc(100% - 90px);
                            }
                        </style>
                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="8" product_type="12" column_count="4" aspect_ratio="0" image_width="250" image_height="250"
                        template="grid.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div
    class="vc_row wpb_row vc_row-has-fill porto-inner-container"
    style="background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/32/shop32_home_banner2_text.png}}');
            padding-top: 80px;
            padding-bottom: 50px;
            background-color: #f7e1e8;
            background-position: center;
            background-repeat: no-repeat;
            background-size: contain;"
>
    <style>
        .porto-recent-posts h4 {
            font-size: 1.5rem;
            letter-spacing: -0.025em;
            margin-bottom: 0.5rem;
            font-weight: 600;
        }
        .porto-recent-posts .post-item .post-excerpt {
            font-size: inherit;
            margin: 0;
        }
        .porto-recent-posts .post-item .read-more {
            display: none;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 2.125rem;" class="vc_custom_heading mb-2 align-left">
                        Beuty Inspiration
                    </h2>
                    <h5 style="font-size: 1rem; color: rgb(119, 119, 119); line-height: 1.2; font-weight: 300; letter-spacing: -0.025em;" class="vc_custom_heading mb-4 align-left">
                        Only the best seller products added recently in our catalog
                    </h5>
                    <div class="porto-recent-posts wpb_content_element mb-0">
                        <div class="row">
                            <div class="post-carousel porto-carousel owl-carousel" style="margin-bottom: 32px;">
                                {{widget type="Magefan\Blog\Block\Widget\Recent" number_of_posts="4" custom_template="recent_home.phtml"}}
                            </div>
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $(".porto-recent-posts .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 1,
                                            },
                                            640: {
                                                items: 1,
                                            },
                                            768: {
                                                items: 1,
                                            },
                                            992: {
                                                items: 2,
                                            },
                                            1200: {
                                                items: 2,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row row no-padding">
    <div class="vc_column_container col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <style>
                .porto-ibanner-layer {
                    position: absolute;
                    z-index: 10;
                }
                @media (min-width: 768px) {
                    .pc-follow-instagram {
                        position: absolute !important;
                        left: 50%;
                        top: 50%;
                        transform: translate3d(-50%, -50%, 0);
                        height: 76%;
                        display: flex !important;
                        flex-direction: column;
                        justify-content: center;
                        z-index: 2;
                        white-space: nowrap;
                    }
                }
            </style>
            <a class="porto-sicon-box-link" href="#">
                <div class="porto-sicon-box mb-0 background-color-dark pc-follow-instagram porto-ibanner-layer position-relative style_3 top-icon" style="padding: 1.5rem 5em;">
                    <div class="porto-sicon-top">
                        <div class="porto-just-icon-wrapper porto-icon none" style="color: #ffffff; font-size: 50px;"><i class="fab fa-instagram"></i></div>
                    </div>
                    <div class="porto-sicon-header">
                        <h2 class="porto-sicon-title" style="font-size: 2.125em; line-height: 1.1; color: #ffffff;">Follow on Instagram</h2>
                        <p style="font-weight: 400; font-size: 0.8125em; line-height: 1.8; letter-spacing: 0.005em; color: rgba(255, 255, 255, 0.7);">@portoecommerce</p>
                    </div>
                </div>
            </a>
            {{block class="Smartwave\Porto\Block\Template" name="instagram" margin="0" template_type="carousel" desktop="6" tablet="4" mobile="2" template="Smartwave_SocialFeed::instagramphotos.phtml"}}
        </div>
    </div>
</div>
