<style>
    body .page-header.type23.sticky-header .nav-sections {
        background-color: inherit;
    }
    .page-header.type23 .navigation:not(.side-megamenu) .level0 .level-top {
        color: inherit;
    }
    .cms-index-index .page-main {
        max-width: 100%;
    }
    .columns .column.main {
        padding-bottom: 0;
    }
    .porto-ibanner-layer {
        text-align: left;
        position: absolute;
        z-index: 10;
    }
    .mw-55 {
        max-width: 55%;
    }
    .text-end {
        text-align: right !important;
    }
    .ms-auto {
        margin-left: auto !important;
    }
    .m-r-sm {
        margin-right: 10px !important;
    }
    .vc_single_image-img {
        width: auto !important;
        display: inline-block !important;
    }
    .sale-text {
        padding: 0.3em 0.8em;
        transform: rotate(-2deg);
    }
    .sale-text strong {
        font-size: 2em;
        vertical-align: text-top;
    }
    @media (max-width: 359px) {
        .porto-ibanner-layer {
            font-size: 10px;
        }
    }
</style>
<div class="mb-4 pb-2">
    <div id="banner-slider-demo-35" class="porto-carousel owl-carousel home-banner-slider nav-pos-inside nav-style-4 show-nav-hover">
        <div class="porto-ibanner mb-0" style="background: #d8dce5; min-height: 36rem;">
            <img class="porto-ibanner-img" src="{{media url=wysiwyg/smartwave/porto/homepage/35/shop35_home_slide1.jpg}}" />
            <div class="porto-ibanner-desc no-padding d-flex">
                <div class="container">
                    <div class="porto-ibanner-container">
                        <div class="porto-ibanner-layer text-end" style="left: 0%; top: 50%; transform: translateY(-50%);">
                            <h4
                                style="font-size: 1.3125em; color: rgba(34, 37, 41, 0.7); line-height: 1; font-weight: 500; letter-spacing: 0.125em;"
                                data-appear-animation="fadeInRight"
                                data-appear-animation-delay="200"
                                class="vc_custom_heading mb-1 align-left"
                            >
                                Find the Boundaries. Push Through!
                            </h4>
                            <h2 style="font-size: 4.5em; line-height: 1; font-weight: 700;" data-appear-animation="fadeInUp" data-appear-animation-delay="200" class="vc_custom_heading mb-0 align-left text-uppercase">Sunglasses</h2>
                            <div class="wpb_single_image wpb_content_element vc_align_left mw-55 ms-auto mb-0" data-appear-animation="fadeInUp" data-appear-animation-delay="400">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img width="260" height="26" src="{{media url=wysiwyg/smartwave/porto/homepage/35/shop35_icon1.png}}" class="vc_single_image-img attachment-full" alt="" title="shop35_icon1" />
                                    </div>
                                </div>
                            </div>
                            <div class="vc_btn3-container pull-left me-3 mb-0 vc_btn3-inline">
                                <button
                                    data-appear-animation="fadeInRight"
                                    data-appear-animation-delay="600"
                                    class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark"
                                    style="font-size: 1em; font-weight: 700; letter-spacing: -0.025em; padding: 1em 3em;"
                                >
                                    Shop Now!
                                </button>
                            </div>
                            <h6
                                style="font-size: 0.8125em; line-height: 1; font-weight: 700; letter-spacing: -0.02em;"
                                data-appear-animation="fadeInRight"
                                data-appear-animation-delay="900"
                                class="vc_custom_heading d-inline-block m-r-sm align-left text-uppercase"
                            >
                                Starting At
                            </h6>
                            <h5
                                style="font-size: 0.875em; line-height: 1; letter-spacing: -0.02em;"
                                data-appear-animation="fadeIn"
                                data-appear-animation-delay="1400"
                                class="vc_custom_heading d-inline-block background-color-secondary mb-0 sale-text align-left heading-light"
                            >
                                $<strong>99</strong>99
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="porto-ibanner mb-0" style="background: #d8dce5; min-height: 36rem;">
            <img class="porto-ibanner-img" src="{{media url=wysiwyg/smartwave/porto/homepage/35/shop35_home_slide2.jpg}}" />
            <div class="porto-ibanner-desc no-padding d-flex">
                <div class="container">
                    <div class="porto-ibanner-container">
                        <div class="porto-ibanner-layer text-end pe-xl-5" style="right: 9%; top: 50%; transform: translateY(-50%);">
                            <h4
                                style="font-size: 1.3125em; color: rgba(34, 37, 41, 0.7); line-height: 1; font-weight: 500; letter-spacing: 0.125em;"
                                data-appear-animation="fadeInUp"
                                data-appear-animation-delay="200"
                                class="vc_custom_heading mb-1 align-left"
                            >
                                Take Your Chill Up a Level
                            </h4>
                            <h2 style="font-size: 3.875em; line-height: 1; font-weight: 700;" data-appear-animation="fadeInRight" data-appear-animation-delay="200" class="vc_custom_heading mb-1 align-left text-uppercase">Casual Wear</h2>
                            <div class="wpb_single_image wpb_content_element vc_align_left mw-55 ms-auto mb-2" data-appear-animation="fadeInUp" data-appear-animation-delay="400">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img width="260" height="26" src="{{media url=wysiwyg/smartwave/porto/homepage/35/shop35_icon1.png}}" class="vc_single_image-img attachment-full" alt="" title="shop35_icon1" />
                                    </div>
                                </div>
                            </div>
                            <div class="vc_btn3-container pull-left me-3 mb-0 vc_btn3-inline">
                                <button
                                    data-appear-animation="fadeInLeft"
                                    data-appear-animation-delay="1200"
                                    class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark"
                                    style="font-size: 1em; font-weight: 700; letter-spacing: -0.025em; padding: 1em 3em;"
                                >
                                    Shop Now!
                                </button>
                            </div>
                            <h6
                                style="font-size: 0.8125em; line-height: 1; font-weight: 700; letter-spacing: -0.02em;"
                                data-appear-animation="fadeInLeft"
                                data-appear-animation-delay="900"
                                class="vc_custom_heading d-inline-block m-r-sm align-left text-uppercase"
                            >
                                Starting At
                            </h6>
                            <h5
                                style="font-size: 0.875em; line-height: 1; letter-spacing: -0.02em;"
                                data-appear-animation="fadeIn"
                                data-appear-animation-delay="600"
                                class="vc_custom_heading d-inline-block background-color-secondary mb-0 sale-text align-left heading-light"
                            >
                                $<strong>99</strong>99
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
            var banner_owl = $("#banner-slider-demo-35");
            banner_owl.owlCarousel({
                items: 1,
                autoplay: true,
                autoplayTimeout: 7000,
                autoplayHoverPause: true,
                dots: false,
                nav: true,
                navRewind: true,
                animateIn: "fadeIn",
                animateOut: "fadeOut",
                loop: true,
                lazyLoad: true,
            });
            var portoSlideCarouselInit = function (e) {
                var $this = $(e.currentTarget);
                if ($this.find(".owl-item.cloned").length) {
                    $this.find(".appear-animation").themeAnimate();
                }
                setTimeout(function () {
                    var $hiddenItems = $this.find(".owl-item:not(.active)");
                    if (window.innerWidth > 767) {
                        $hiddenItems.find(".appear-animation").removeClass("appear-animation-visible");
                        $hiddenItems.find(".appear-animation").each(function () {
                            var $el = $(this),
                                delay = Math.abs($el.data("appear-animation-delay") ? $el.data("appear-animation-delay") : 0);
                            if (delay > 1) {
                                this.style.animationDelay = delay + "ms";
                            }

                            var duration = Math.abs($el.data("appear-animation-duration") ? $el.data("appear-animation-duration") : 1000);
                            if (1000 != duration) {
                                this.style.animationDuration = duration + "ms";
                            }
                        });
                    }
                }, 300);
            };
            var portoCarouselTranslated = function (e) {
                var $this = $(e.currentTarget);
                if (window.innerWidth > 767) {
                    if ($this.find(".owl-item.cloned").length && $this.find(".appear-animation:not(.appear-animation-visible)").length) {
                        $(document.body).trigger("appear_refresh");
                    }
                }
                var $active = $this.find(".owl-item.active");
                if ($active.hasClass("translating")) {
                    $active.removeClass("translating");
                    return;
                }
                $this.find(".owl-item.translating").removeClass("translating");

                if (window.innerWidth > 767) {
                    $this.find(".appear-animation").removeClass("appear-animation-visible");
                    $active.find(".appear-animation").each(function () {
                        var $animation_item = $(this),
                            anim_name = $animation_item.data("appear-animation");
                        $animation_item.addClass(anim_name + " appear-animation-visible");
                    });
                }
            };
            banner_owl.on("initialized.owl.carousel", portoSlideCarouselInit).on("translated.owl.carousel", portoCarouselTranslated);
        });
    </script>
</div>
<div class="vc_row wpb_row top-row home-bar no-padding porto-inner-container" data-appear-animation="fadeIn" data-appear-animation-delay="200" style="margin-top: 20px; margin-bottom: 20px;">
    <style>
        .home-bar .porto-sicon-box {
            justify-content: center;
        }
        .top-ten-products ol.products {
            display: flex;
            flex-wrap: nowrap;
            overflow-x: auto;
            counter-reset: p_count 0;
        }
        .top-ten-products .products-grid.columns4 .product-item {
            flex: 0 0 25%;
            max-width: 25%;
        }
        @media (max-width: 767px) {
            .top-ten-products .products-grid.columns4 .product-item {
                flex: 0 0 50%;
                max-width: 50%;
            }
        }
        .top-ten-products ol.products li.product-item:before {
            counter-increment: p_count;
            content: counter(p_count) "º";
            position: absolute;
            left: 20px;
            top: 10px;
            z-index: 2;
            background: #3d5167;
            width: 2rem;
            height: 2rem;
            border-radius: 1rem;
            text-align: center;
            padding-top: 0.5rem;
            line-height: 1;
            color: #fff;
            font-size: 1rem;
            font-weight: 600;
        }
        .top-ten-products .product-labels {
            top: 3rem;
        }
        .top-ten-products ol.products::-webkit-scrollbar {
            height: 8px;
        }
        .top-ten-products ol.products::-webkit-scrollbar-track {
            background: #f4f4f4;
            border-radius: 8px;
            margin: 8px;
        }
        .top-ten-products ol.products::-webkit-scrollbar-thumb {
            background: #3d5167;
            border-radius: 8px;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="infobox-carousel owl-carousel">
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3d5167; font-size: 32px; margin-right: 0.5rem;">
                                    <i class="porto-icon-shipping"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 1.1;">Free Shipping on Orders Over $99</h3>
                                <p style="font-size: 13px; line-height: 16px;">For more than 100,000 parts!</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3d5167; font-size: 32px; margin-right: 0.5rem;">
                                    <i class="porto-icon-percent-shape"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 1.1;">Up to 40% OFF on Selected Items</h3>
                                <p style="font-size: 13px; line-height: 16px;">Available for all Categories!</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3d5167; font-size: 32px; margin-right: 0.5rem;">
                                    <i class="porto-icon-secure-payment"></i>
                                </div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 1.1;">100% Secure Payment</h3>
                                <p style="font-size: 13px; line-height: 16px;">We ensure secure payment!</p>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".infobox-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 1,
                                    },
                                    640: {
                                        items: 1,
                                    },
                                    768: {
                                        items: 2,
                                    },
                                    992: {
                                        items: 2,
                                    },
                                    1200: {
                                        items: 3,
                                    },
                                },
                            });
                        });
                    </script>
                    <h2 style="font-size: 1.25rem; line-height: 1.2; text-align: center; font-weight: 600; letter-spacing: -0.01em;" class="vc_custom_heading mb-4">Top 10 Products</h2>
                    <div class="porto-products wpb_content_element top-ten-products mb-5 swiper-wrapper theme_option">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="8" aspect_ratio="0" image_width="350" image_height="350" template="grid.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row home-trending vc_row-has-fill porto-inner-container" style="background-color: #d8dce5;">
    <style>
        .porto-u-2971.porto-u-heading {
            text-align: right;
        }
        .z-index-2 {
            z-index: 2;
        }
        .porto-hotspot {
            display: flex;
            align-items: center;
            justify-content: center;
            position: absolute;
            background: #fb7070;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            line-height: 20px;
            font-size: 8px;
            cursor: pointer;
        }
        .porto-hotspot:before {
            content: "";
            position: absolute;
            left: -10px;
            right: -10px;
            top: -10px;
            bottom: -10px;
        }
        .porto-hotspot .porto-products,
        .porto-hotspot ul.products,
        .porto-hotspot .products .product-item {
            margin-bottom: 0;
        }
        .porto-hotspot i {
            color: #fff;
            line-height: inherit;
        }
        .porto-hotspot i:before {
            background: #fff;
            width: 20px;
            height: 20px;
            border-radius: 20px;
        }
        .porto-hotspot .popup-wrap {
            text-align: left;
            cursor: default;
            position: absolute;
            z-index: 29;
            padding: 20px;
            min-width: 250px;
            background: #fff;
            box-shadow: 0 0 30px rgba(0, 0, 0, 0.06);
            opacity: 0;
            visibility: hidden;
            transition: opacity 0.3s, transform 0.3s, visibility 0.3s;
        }
        .porto-hotspot ol.products li.product .product-item-photo {
            box-shadow: none;
        }
        .porto-hotspot .towishlist,
        .porto-hotspot .tocompare {
            display: none !important;
        }
        .porto-hotspot .product-item-info .product-item-details .product-item-actions .tocart {
            width: 100%;
            display: block;
            height: 2.625rem;
            line-height: 2.5rem !important;
            background: #3d5167 !important;
            color: #fff !important;
            margin: 0 0 -0.5em;
        }
        .porto-hotspot .add-links .button:before {
            float: none;
        }
        @media (max-width: 575px) {
            .porto-hotspot .popup-wrap {
                min-width: 160px;
                padding: 10px;
            }
        }
        .porto-hotspot.pos-right .popup-wrap {
            left: calc(100% + 10px);
            transform: translate(-8px, -20%);
        }
        .porto-hotspot.pos-left .popup-wrap {
            right: calc(100% + 10px);
            transform: translate(8px, -20%);
        }
        .porto-hotspot.pos-right:hover .popup-wrap,
        .porto-hotspot.pos-left:hover .popup-wrap {
            transform: translate(0, -20%);
        }
        .porto-hotspot.pos-top .popup-wrap {
            left: 50%;
            bottom: calc(100% + 10px);
            transform: translate(-50%, -8px);
        }
        .porto-hotspot.pos-bottom .popup-wrap {
            left: 50%;
            top: calc(100% + 10px);
            transform: translate(-50%, 8px);
        }
        .porto-hotspot.pos-top:hover .popup-wrap,
        .porto-hotspot.pos-bottom:hover .popup-wrap {
            transform: translate(-50%, 0);
        }
        .porto-hotspot:hover .popup-wrap {
            visibility: visible;
            opacity: 1;
        }
        .elementor-element.elementor-widget-porto_hotspot {
            position: absolute;
            width: auto;
        }
        .elementor-widget-porto_hotspot .porto-hotspot {
            position: static;
        }
        /*--inline-products-*/
        .products-inline .product-item-photo,
        .products-inline .product-reviews-summary,
        .products-inline .towishlist,
        .products-inline .tocompare,
        .products-inline .product-item .tocart:before {
            display: none !important;
        }
        .products-inline ol.products {
            display: flex;
            flex-wrap: wrap;
        }
        .products-inline .product-item-details {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
        }
        .products-inline li.product-item .product-item-name a:before {
            content: "-";
            margin-right: 0.5rem;
        }
        .products-inline .product-item-details > *:not(:last-child) {
            margin-right: 1.25rem;
        }
        .products-inline .product-item-info .product-item-details .product-item-actions .tocart {
            height: auto;
            min-width: auto;
            padding: 0 !important;
            background: none !important;
            line-height: 1.3 !important;
            border-bottom: 1px solid !important;
            color: #3d5167 !important;
            font-size: 0.8125rem;
            letter-spacing: -0.025em;
            font-weight: 700;
            text-transform: capitalize;
            display: block;
        }
        .product-item-info .product-item-details .product-item-actions .actions-primary {
            display: block;
        }
        .products-inline li.product-item {
            margin-bottom: 0 !important;
            flex: 0 0 100%;
            max-width: 100%;
        }
        .products-inline li.product-item .product-item-name {
            height: 35px;
        }
        .products-inline li.product-item .product-item-name a {
            font-size: 0.9375rem !important;
            font-weight: 500 !important;
        }
        .products-inline li.product-item .price-box {
            font-family: "Open Sans", sans-serif;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row align-items-center">
            <div class="porto-ibanner-layer position-static pt-5 pb-lg-5 vc_column_container col-md-12 col-lg-6">
                <div class="wpb_wrapper vc_column-inner">
                    <h4
                        style="font-size: 1.3125em; color: rgba(34, 37, 41, 0.7); line-height: 1; font-weight: 500; letter-spacing: 0.125em;"
                        data-appear-animation="fadeInRight"
                        data-appear-animation-delay="200"
                        class="vc_custom_heading mb-1 align-left"
                    >
                        Super Sale
                    </h4>
                    <div class="porto-u-heading d-inline-block mb-4 pb-2 porto-u-2971" data-appear-animation="fadeInRight" data-appear-animation-delay="600">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 4px; font-size: 4em; line-height: 1.1;">TRENDING LOOKS</h2>
                        </div>
                        <div class="porto-u-sub-heading" style="">
                            <h6 class="d-inline-block m-r-sm" style="font-size: 0.8125em; line-height: 1; font-weight: bold; letter-spacing: -0.02em;">for only</h6>
                            <h5 class="d-inline-block background-color-secondary mb-0 sale-text heading-light" style="font-size: 0.875em; line-height: 1; letter-spacing: -0.02em;">$ <strong>99</strong>99</h5>
                            <p></p>
                        </div>
                    </div>
                    <div class="porto-products wpb_content_element products-inline m-b-n-sm" data-appear-animation="fadeInRight" data-appear-animation-delay="1000">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="1" product_count="6" aspect_ratio="0" image_width="350" image_height="350" template="grid.phtml"}}
                    </div>
                </div>
            </div>
            <div class="z-index-2 vc_column_container col-md-8 col-lg-4" data-appear-animation="fadeIn" data-appear-animation-delay="1200">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_single_image wpb_content_element vc_align_center mb-0 img-block">
                        <div class="wpb_wrapper">
                            <div class="vc_single_image-wrapper vc_box_border_grey">
                                <img width="438" height="583" src="{{media url=wysiwyg/smartwave/porto/homepage/35/shop35_home_banner1.jpg}}" />
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 16%; top: 87%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 56%; top: 82%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 22.5%; top: 62%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 57.5%; top: 54%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 18%; top: 24%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <div class="porto-hotspot pos-right" style="left: 58%; top: 22%;">
                        <i class="porto-hotspot-icon fas fa-circle"></i>
                        <div class="popup-wrap">
                            <div class="porto-products wpb_content_element">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="4" product_count="1" column_count="1" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4 col-lg-2">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_btn3-container mb-3 vc_btn3-center">
                        <a
                            data-appear-animation="fadeInRight"
                            data-appear-animation-delay="600"
                            class="vc_btn3 vc_btn3-shape-default d-block btn btn-modern btn-lg btn-dark"
                            style="font-size: 1rem; font-weight: 700; letter-spacing: -0.025em; padding: 1em;"
                            href="#"
                            title=""
                        >
                            SHOP MEN
                        </a>
                    </div>
                    <div class="vc_btn3-container mb-5 mb-md-0 vc_btn3-center">
                        <a
                            data-appear-animation="fadeInRight"
                            data-appear-animation-delay="600"
                            class="vc_btn3 vc_btn3-shape-default d-block btn btn-modern btn-lg btn-dark"
                            style="font-size: 1rem; font-weight: 700; letter-spacing: -0.025em; padding: 1em;"
                            href="#"
                            title=""
                        >
                            SHOP WOMEN
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row py-5 porto-inner-container">
    <style>
        .pc-label-sale {
            position: relative;
            z-index: 1;
            display: inline-block !important;
        }
        .pc-label-sale:before {
            content: "";
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            transform: rotateZ(-2deg) skew(1deg);
            background-color: #000;
            z-index: -1;
        }
        .me-3 {
            margin-right: 1rem !important;
        }
        @media (min-width: 992px) {
            .text-lg-end {
                text-align: right !important;
            }
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 1.25rem; line-height: 1.2; text-align: center; font-weight: 600; letter-spacing: -0.01em;" data-appear-animation="maskUp" class="vc_custom_heading mt-3 mb-4">Sale Products</h2>
                    <div id="sale-products" class="porto-products wpb_content_element theme_option" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" extra_class="nav-center-images-only nav-style-4 nav-pos-outside show-nav-hover dots-style-1" product_count="8" aspect_ratio="0"
                            image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#sale-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div
                        class="vc_row wpb_row vc_inner row align-items-center no-padding mx-0 mb-5 vc_row-has-fill"
                        style="background-image: url({{media url=wysiwyg/smartwave/porto/homepage/35/shop35_parallax1.jpg}});padding-top: 20px;padding-right: 20px !important;padding-bottom: 6px;padding-left: 30px !important;background-color: #374759;background-position: center;background-repeat: no-repeat;background-size: cover;"
                    >
                        <div class="category-content dir-column text-center-md vc_column_container col-md-12 col-lg-9" data-appear-animation="fadeIn" data-appear-animation-delay="300">
                            <div class="wpb_wrapper vc_column-inner">
                                <h4
                                    style="font-size: 1.3rem; line-height: 1; text-align: center; font-weight: 700; letter-spacing: -0.02em; padding: 0.6rem 0.8rem; margin-right: 1rem;"
                                    class="vc_custom_heading pc-label-sale text-uppercase heading-light"
                                >
                                    <b>BIG SALE</b>
                                </h4>
                                <h4 style="font-size: 1.25rem; color: #ffffff; line-height: 1.2; letter-spacing: -0.02em;" class="vc_custom_heading d-inline-block me-3 align-left text-uppercase">
                                    ALL NEW FASHION BRANDS ITEMS UP TO 70% OFF
                                </h4>
                                <h6 style="font-size: 0.8125rem; color: rgba(255, 255, 255, 0.7); line-height: 1; font-weight: 500; letter-spacing: -0.02em;" class="vc_custom_heading d-inline-block pb-1 align-left">
                                    Online Purchases Only
                                </h6>
                            </div>
                        </div>
                        <div class="text-lg-end vc_column_container col-md-12 col-lg-3" data-appear-animation="fadeIn" data-appear-animation-delay="600">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="vc_btn3-container d-inline-block" style="margin-bottom: 14px; background-color: #ffffff;">
                                    <a class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-light" style="font-weight: 700;" href="#" title="Sale Products">VIEW SALE</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h2 style="font-size: 1.25rem; line-height: 1.2; text-align: center; font-weight: 600; letter-spacing: -0.01em;" data-appear-animation="maskUp" class="vc_custom_heading mb-4">New Arrivals</h2>
                    <div id="latest-products" class="porto-products wpb_content_element mb-5 theme_option" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="nav-center-images-only nav-style-4 nav-pos-outside show-nav-hover dots-style-1" product_count="8"
                            aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#latest-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <h2 style="font-size: 1.25rem; line-height: 1; text-align: center; font-weight: 600; letter-spacing: -0.01em;" class="vc_custom_heading mb-1">Get Special Offers and Savings</h2>
                    <p style="text-align: center; letter-spacing: 0.005em;" class="vc_custom_heading mb-4">Get all the latest information on Events, Sales and Offers.</p>
                    {{block class="Magento\Newsletter\Block\Subscribe" name="home.newsletter" template="subscribe_form.phtml"}}
                    <style>
                        .single-subscribe .newsletter .control {
                            justify-content: center;
                            max-width: 510px;
                            margin: 0 auto;
                            border-bottom: 1px solid #d8dce1;
                            position: relative;
                        }
                        .single-subscribe .newsletter .control:before {
                            content: "\e88e";
                            font-family: "porto-icons";
                            font-size: 1rem;
                            font-weight: 600;
                            color: #3d5167;
                            line-height: 1;
                            position: absolute;
                            left: 0;
                            top: 50%;
                            margin-top: -0.5em;
                            z-index: 1;
                        }
                        @media (min-width: 992px) {
                            .single-subscribe .newsletter .input-text {
                                width: 60%;
                            }
                        }
                        .single-subscribe .newsletter input {
                            height: 40px;
                            padding-left: 1.5rem;
                            padding-right: 15px;
                            color: #777;
                            border: none;
                            margin: 0;
                            font-size: 0.75rem;
                            font-style: italic;
                            box-shadow: none;
                            line-height: 2;
                        }
                        .single-subscribe .newsletter .action {
                            display: table-cell;
                            vertical-align: top;
                            height: auto;
                            padding: 0.5em 0.8em;
                            text-transform: uppercase;
                            font-weight: 700;
                            font-size: 0.75rem;
                            border-radius: 0;
                            background: #3d5167;
                        }
                    </style>
                </div>
            </div>
        </div>
    </div>
</div>
