<style>
    .cms-index-index .page-main,
    .layout-1220.cms-index-index .page-main {
        max-width: 100%;
        padding: 0;
    }
    .columns .column.main {
        padding: 0;
    }
    .m-l-n-lg {
        margin-left: -30px !important;
    }
    .text-color-primary > .btn,
    .text-color-dark > .btn {
        color: inherit;
    }
    .porto-ultimate-content-box {
        height: 100%;
        position: relative;
        font-size: inherit;
    }
    .porto-ultimate-content-box:before {
        content: "";
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.1);
        opacity: 0;
        transition: opacity 0.25s;
    }
    .porto-ultimate-content-box:after {
        content: "";
        display: block;
        clear: both;
    }
    .porto-ultimate-content-box:hover:before {
        opacity: 1;
    }
    .porto-ultimate-content-box > * {
        position: relative;
        z-index: 1;
    }
    .content-align-start .porto-ultimate-content-box > * {
        align-self: flex-start;
    }
    .coupon-text {
        transform: rotate(-2.5deg);
        padding: 13px;
        letter-spacing: 0.01em;
    }
    .coupon-text-sale i {
        font-style: normal;
        position: absolute;
        left: -2.25em;
        top: 50%;
        transform: translateY(-50%) rotate(-90deg);
        font-size: 0.65em;
        opacity: 0.6;
        letter-spacing: 0;
    }
    .coupon-text-sale b {
        display: inline-block;
        background: #222529;
        color: #fff;
        font-size: 1.6em;
        padding: 5px 12px;
    }
    .coupon-text-sale {
        transform: rotate(-2deg);
        letter-spacing: 0.01em;
        position: relative;
    }
    .col-md-2-5,
    .col-md-3-5 {
        padding-left: 10px;
        padding-right: 10px;
        width: 100%;
    }
    @media (min-width: 768px) {
        .col-md-2-5 {
            flex: 0 0 40%;
            width: 40%;
        }
        .col-md-3-5 {
            flex: 0 0 60%;
            width: 60%;
        }
    }
</style>
<div class="porto-inner-container" style="margin-top: 20px;">
    <div class="container">
        <div class="row">
            <div class="mb-3 mb-lg-0 col-md-12 col-lg-5">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-ultimate-content-box-container">
                        <div
                            class="porto-ultimate-content-box porto-lazyload lazy-load-loaded"
                            style="background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/27/shop27_home_banner1.jpg}}');
                        margin-bottom: 20px;
                        padding-top: 17%;
                        padding-right: 27px;
                        padding-bottom: 30px;
                        background-color: #f0f5f9;"
                        >
                            <h2 style="font-size: 34px; line-height: 1.2; font-weight: 700;" class="vc_custom_heading mb-0 align-right text-uppercase">Black</h2>
                            <h3 style="font-size: 28px; line-height: 1.2; font-weight: 700;" class="vc_custom_heading mb-3 align-right">Armchairs</h3>
                            <h4 style="font-size: 15px; line-height: 1.2; font-weight: 600;" class="vc_custom_heading mb-4 align-right text-uppercase heading-secondary">STARTING FROM $399</h4>
                            <div class="btn-container mb-0 text-color-primary text-right">
                                <button class="btn btn-borders btn-xs btn-default">SHOP NOW <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-3 mb-md-0 col-md-2-5">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ultimate-content-box-container h-100">
                                    <div
                                        class="porto-ultimate-content-box porto-lazyload lazy-load-loaded"
                                        style="background-size: cover;
                              background-repeat: no-repeat;
                              background-position: center center;
                              min-height: 315px;
                              background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/27/shop27_home_banner2.jpg}}');
                              padding-top: 35px;
                              padding-right: 0px;
                              padding-left: 0px;
                              background-color: #222529;"
                                    >
                                        <h5 style="font-size: 12px; color: rgba(255, 255, 255, 0.4); line-height: 1.5; text-align: center; font-weight: 500;" class="vc_custom_heading mb-0 ls-25em text-uppercase">CHECK NEW ARRIVALS</h5>
                                        <h3 style="font-size: 25px; line-height: 1.2; text-align: center; font-weight: 700;" class="vc_custom_heading text-uppercase heading-light">COOL LAMPS</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3-5">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ultimate-content-box-container h-100">
                                    <div
                                        class="porto-ultimate-content-box has-content-pos justify-content-end porto-lazyload lazy-load-loaded"
                                        style="background-size: cover;
                              background-repeat: no-repeat;
                              background-position: center center;
                              min-height: 315px;
                              background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/27/shop27_home_banner3.jpg}}');
                              padding-right: 20px;
                              padding-bottom: 35px;
                              padding-left: 20px;
                              background-color: #606da6;"
                                    >
                                        <h6 style="color: rgba(255, 255, 255, 0.4); text-align: center; font-weight: 500;" class="vc_custom_heading ls-25em mb-0 text-uppercase">exclusive new collection</h6>
                                        <h3 style="font-size: 28px; line-height: 1.2; text-align: center; font-weight: 700;" class="vc_custom_heading mb-0 text-uppercase heading-light">Luxurious Jacuzzi</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-7">
                <div class="wpb_wrapper vc_column-inner h-100">
                    <div class="porto-ultimate-content-box-container h-100 content-align-start">
                        <div
                            class="porto-ultimate-content-box has-content-pos justify-content-center porto-lazyload lazy-load-loaded"
                            style="background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/27/shop27_home_banner4.jpg}}');
                        padding-top: 10%;
                        padding-bottom: 10%;
                        padding-left: 9%;
                        background-color: #f4f4f4;
                        "
                        >
                            <h2 style="font-size: 45px; line-height: 1.2; font-weight: 700;" class="vc_custom_heading m-l-n-lg align-right">
                                WOODEN<br />
                                Black Chair
                            </h2>
                            <div style="font-size: 24px; line-height: 1; font-weight: 700;" class="vc_custom_heading coupon-text background-color-dark m-b-sm align-left text-uppercase heading-light">GO COUPON</div>
                            <div style="font-size: 21px; line-height: 1; font-weight: 700;" class="vc_custom_heading coupon-text-sale m-b-xl align-left text-uppercase heading-dark"><i>Up To</i><b>$100</b> OFF</div>
                            <h4 style="font-size: 20px; line-height: 1.2; font-weight: 600;" class="vc_custom_heading m-b-lg align-left text-uppercase heading-secondary">STARTING FROM $199</h4>
                            <div class="btn-container mb-0 text-color-primary text-left">
                                <button class="btn btn-borders btn-lg btn-default">SHOP NOW <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="home-features porto-inner-container" style="padding-top: 40px; padding-bottom: 20px;">
    <style>
        @media (min-width: 768px) {
            .home-features .column_container > .column-inner {
                display: flex;
                justify-content: center;
            }
        }
    </style>
    <div class="container">
        <div class="row align-items-center">
            <div class="column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #222529; font-size: 35px; display: inline-block;"><i class="porto-icon-shipping"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h6 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 14px;">FREE SHIPPING & RETURN</h6>
                            <p style="font-size: 13px; line-height: 15px;">Free shipping on all orders over $99.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #222529; font-size: 35px; display: inline-block;"><i class="porto-icon-money"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h6 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 14px;">MONEY BACK GUARANTEE</h6>
                            <p style="font-size: 13px; line-height: 15px;">100% money back guarantee</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #222529; font-size: 35px; display: inline-block;"><i class="porto-icon-support"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h6 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 14px;">ONLINE SUPPORT 24/7</h6>
                            <p style="font-size: 13px; line-height: 15px;">Lorem ipsum dolor sit amet.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #222529; font-size: 35px; display: inline-block;"><i class="porto-icon-secure-payment"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h6 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 14px;">SECURE PAYMENT</h6>
                            <p style="font-size: 13px; line-height: 15px;">Lorem ipsum dolor sit amet.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-separator short"><hr class="separator-line align_center solid" style="margin-bottom: 42px;" /></div>
                    <style>
                        .product.data.items > .item.title {
                            color: inherit;
                            border-bottom-width: 3px;
                            font-size: inherit;
                            font-weight: 500;
                            text-transform: uppercase;
                            letter-spacing: 0.15em;
                        }
                        .product.data.items > .item.title:hover {
                            border-color: #606da6;
                            color: #606da6;
                        }
                        .product.data.items > .item.title > .switch {
                            font-size: inherit;
                        }
                        .product.data.items > .item.title.active {
                            color: #606da6;
                            border-color: #606da6;
                        }
                        .tabs.tabs-simple .section-title {
                            text-align: left;
                        }
                        @media (min-width: 1024px) {
                            .tabs.tabs-simple .section-title {
                                margin: 0;
                                margin-bottom: -28px;
                                padding-top: 3px;
                            }
                        }
                        @media (min-width: 768px) {
                            .product.data.items {
                                text-align: right;
                            }
                            .product.data.items > .item.title {
                                margin: 2px 27px 0.5rem 0;
                                color: inherit;
                                padding: 0;
                                padding-top: 2px;
                                font-size: inherit;
                                display: inline-block;
                                float: none;
                            }
                            .product.data.items > .item.content {
                                border-top: none;
                                margin-top: 2.16rem;
                            }
                        }
                    </style>
                    <div class="tabs tabs-simple">
                        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active","collapsible":"true"}}'>
                            <h2 class="section-title slider-title"><span class="inline-title">Featured Products</span><span class="line"></span></h2>
                            <div class="data item title" aria-labeledby="tab-label-tab1-title" data-role="collapsible" id="tab-label-tab1">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab1" id="tab-label-tab1-title">
                                    <span>Kitchen</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab1" data-role="content">
                                <div id="tab1-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab1-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab2-title" data-role="collapsible" id="tab-label-tab2">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2" id="tab-label-tab2-title">
                                    <span>Dining</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab2" data-role="content">
                                <div id="tab2-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab2-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab3-title" data-role="collapsible" id="tab-label-tab3">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab3" id="tab-label-tab3-title">
                                    <span>Bedroom</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab3" data-role="content">
                                <div id="tab3-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab3-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab4-title" data-role="collapsible" id="tab-label-tab4">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab4" id="tab-label-tab4-title">
                                    <span>Living</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab4" data-role="content">
                                <div id="tab4-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab4-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab5-title" data-role="collapsible" id="tab-label-tab5">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab5" id="tab-label-tab5-title">
                                    <span>Office</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab5" data-role="content">
                                <div id="tab5-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab5-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab6-title" data-role="collapsible" id="tab-label-tab6">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab6" id="tab-label-tab6-title">
                                    <span>Outdoor</span>
                                </a>
                            </div>
                            <div class="data item content" id="tab6" data-role="content">
                                <div id="tab6-products" class="porto-products wpb_content_element">
                                    <div class="slider-wrapper">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="tab1_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="6"
                                        product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab6-products .owl-carousel").owlCarousel({
                                                    autoplay: true,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 3,
                                                        },
                                                        1200: {
                                                            items: 5,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="background: url({{media url=wysiwyg/smartwave/porto/homepage/27/shop27_home_parallax.jpg}}) center no-repeat; padding-top: 100px; padding-bottom: 100px;" class="porto-inner-container">
    <div class="container">
        <style>
            .coupon-text-primary b {
                background: #606da6;
            }
        </style>
        <div class="row align-items-center">
            <div class="d-flex justify-content-center justify-content-md-start mb-5 mb-md-0 vc_column_container col-md-6">
                <div class="wpb_wrapper vc_column-inner">
                    <p style="font-size: 16px; color: rgba(255, 255, 255, 0.4); line-height: 1.2; font-weight: 700;" class="vc_custom_heading mb-0 ls-25em align-left text-uppercase">IT IS TIME FOR A</p>
                    <h2 style="font-size: 50px; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-2 align-left heading-light">Modern Bathroom</h2>
                    <div class="btn-container mb-0 text-right">
                        <a class="btn btn-borders btn-lg btn-light" href="#" title="Shop"> SHOW NOW <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i> </a>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-center justify-content-md-end vc_column_container col-md-6 col-xl-5">
                <div class="wpb_wrapper vc_column-inner">
                    <div style="font-size: 1.875rem; line-height: 1.2; font-weight: 700;" class="vc_custom_heading coupon-text background-color-light m-b-sm align-left heading-dark">Exclusive COUPON</div>
                    <div style="font-size: 1.625rem; line-height: 1; font-weight: 700;" class="vc_custom_heading coupon-text-sale coupon-text-primary align-left text-uppercase heading-light"><i>up to</i><b>$200</b> OFF</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="porto-inner-container" style="padding-top: 80px; padding-bottom: 40px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-products wpb_content_element mb-0">
                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="" product_count="12" column_count="6" product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="grid.phtml"}}
                    </div>
                    <div class="btn-container mb-0 text-color-dark text-center" style="margin-top: 1em;">
                        <a class="btn btn-borders btn-lg btn-default" href="#" title="Shop"> BROWSE ALL <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i> </a>
                    </div>
                    <div class="porto-separator"><hr class="separator-line align_center solid" style="margin-top: 40px; margin-bottom: 45px;" /></div>
                    <style>
                        .flex-style .vc_column-inner {
                            display: flex;
                            flex-wrap: wrap;
                            align-items: center;
                        }
                        .flex-style .vc_custom_heading {
                            padding-right: 25px;
                            margin-right: 25px;
                            border-right: 1px solid #e7e7e7;
                        }
                        .ls-150em,
                        .ls-150em .porto-sicon-title {
                            letter-spacing: 0.15em;
                        }
                        .porto-recent-posts img {
                            display: block;
                        }
                        .porto-recent-posts .post-item {
                            padding: 0;
                            position: relative;
                            display: flex;
                            align-items: center;
                            flex-wrap: wrap;
                            margin-left: -10px;
                            margin-right: -10px;
                        }
                        .porto-recent-posts .post-item > a {
                            flex: 0 0 50%;
                            max-width: 100%;
                            padding-left: 10px;
                            padding-right: 10px;
                        }
                        .porto-recent-posts .post-item > .post-content {
                            flex: 0 0 50%;
                            max-width: 100%;
                            padding-left: 10px;
                            padding-right: 10px;
                        }
                        .porto-recent-posts .post-item .post-date {
                            position: absolute;
                            top: 10px;
                            left: 20px;
                            background: #606da6;
                            letter-spacing: 0;
                            width: auto;
                            padding: 15px;
                            font-size: 2em;
                        }
                        .porto-recent-posts .post-date .day {
                            font-size: 2em;
                            text-transform: uppercase;
                            padding: 0;
                            font-size: inherit;
                        }
                        .porto-recent-posts .post-date .month {
                            margin-top: 0.25rem;
                            font-weight: 300;
                            opacity: 0.5;
                            font-size: 0.428em;
                            padding: 0;
                        }
                        .porto-recent-posts h4 {
                            font-size: 1.4em;
                            font-weight: 700;
                            margin-bottom: 0.75rem;
                            white-space: nowrap;
                            overflow: hidden;
                            text-overflow: ellipsis;
                        }
                        .porto-recent-posts .post-item .post-excerpt {
                            display: -webkit-box;
                            -webkit-line-clamp: 3;
                            -webkit-box-orient: vertical;
                            overflow: hidden;
                            font-size: 13px;
                            display: flex;
                            flex-wrap: wrap;
                            margin-bottom: 0;
                        }
                        .post-item .read-more {
                            display: inline-block;
                            font-size: 11px;
                            margin-bottom: 1rem;
                            padding: 8px 20px;
                            color: #222529;
                            border: 2px solid #e7e7e7;
                            line-height: 1.3333;
                            text-transform: uppercase;
                            font-weight: 700;
                            letter-spacing: 0.15em;
                            font-family: "Poppins";
                            margin-top: 20px;
                            margin-bottom: 1rem;
                        }
                        .post-item .read-more i {
                            display: none;
                        }
                        @media (max-width: 767px) {
                            .porto-recent-posts .post-item > a {
                                flex: 0 0 100%;
                            }
                            .porto-recent-posts .post-item > .post-content {
                                flex: 0 0 100%;
                            }
                        }
                    </style>
                    <div class="row flex-style">
                        <div class="mb-4 mb-lg-0 col-md-12 col-lg-6">
                            <div class="wpb_wrapper vc_column-inner d-flex align-items-center flex-wrap">
                                <h2 style="font-size: 22px; line-height: 1; font-weight: 700;" class="vc_custom_heading ls-150em m-b-md align-left text-uppercase">RECENT ARTICLE</h2>
                                <a class="porto-sicon-box-link" href="#" title="Blog">
                                    <div class="porto-sicon-box ls-150em style_1 heading-right-icon">
                                        <div class="porto-sicon-header"><h5 class="porto-sicon-title" style="font-weight: 700; color: #606da6;">VIEW BLOG</h5></div>

                                        <div class="porto-sicon-heading-right">
                                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                                <div class="porto-icon none" style="color: #606da6; font-size: 14px; display: inline-block;"><i class="fas fa-long-arrow-alt-right"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <div class="porto-recent-posts porto-blog wpb_content_element mb-0" style="padding-bottom: 1rem;">
                                    {{widget type="Magefan\Blog\Block\Widget\Recent" number_of_posts="1" custom_template="recent_home.phtml"}}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="wpb_wrapper vc_column-inner d-flex align-items-center flex-wrap">
                                <h2 style="font-size: 22px; line-height: 1; font-weight: 700;" class="vc_custom_heading ls-150em m-b-md align-left text-uppercase">from instagram</h2>
                                <a class="porto-sicon-box-link" href="#" title="Blog">
                                    <div class="porto-sicon-box ls-150em style_1 heading-right-icon">
                                        <div class="porto-sicon-header"><h5 class="porto-sicon-title" style="font-weight: 700; color: #606da6;">@PORTODECOR</h5></div>

                                        <div class="porto-sicon-heading-right">
                                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                                <div class="porto-icon none" style="color: #606da6; font-size: 14px; display: inline-block;"><i class="fas fa-long-arrow-alt-right"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <div class="wpb_text_column wpb_content_element mb-0" style="overflow: hidden;">
                                    <div class="wpb_wrapper">
                                        {{block class="Smartwave\Porto\Block\Template" name="instagram" margin="20" template_type="carousel" desktop="3" tablet="3" mobile="2" template="Smartwave_SocialFeed::instagramphotos.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
