<style>
    .columns .column.main {
        max-width: 100%;
        padding-bottom: 0;
    }
    .layout-fullwidth .page-main {
        padding-left: 0;
        padding-right: 0;
    }
    .fullscreen-carousel {
        height: 100vh;
        position: relative;
    }
    .fullscreen-carousel,
    .fullscreen-carousel .owl-carousel:not(.owl-loaded) > *,
    .fullscreen-carousel .owl-item > * {
        max-height: 80vw;
    }
    .fullscreen-carousel .porto-ibanner > img {
        height: 100%;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .porto-ibanner .btn-modern.btn-md {
        font-size: 0.75em;
        padding: 1.3em 3.25em;
    }
    .scene {
        list-style: none;
    }
    .scene .layer img {
        width: auto;
    }
    .home-banner-thumb {
        position: absolute !important;
        bottom: 2.6vw;
        right: 0;
        width: 24% !important;
        z-index: 3;
    }
    .home-banner-thumb img {
        border: 3px solid rgba(255, 255, 255, 0.5);
    }
    .home-banner-thumb .synced img {
        border-color: #fff;
    }
    sup {
        font-size: 54%;
    }
    .porto-ibanner .btn-modern.btn-xl {
        font-size: 1.05em;
    }
    .ls-200 > .btn {
        letter-spacing: 0.2em;
    }
    @media (max-width: 480px) {
        .porto-ibanner-layer {
            font-size: 0.6rem;
        }
    }
</style>
<div class="row no-padding home-banner">
    <div class="col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div class="fullscreen-carousel">
                <div id="banner-slider-demo-18" class="porto-carousel owl-carousel home-banner-slider mb-0 home-banner">
                    <div class="porto-ibanner mb-0" style="background: #222529;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/01n.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer layer" style="width: 100%; left: 0%; top: 50%; transform: translateY(-50%);">
                                <div class="wpb_text_column wpb_content_element">
                                    <div class="wpb_wrapper">
                                        <ul class="scene" style="width: 100%; position: relative; transform: translate3d(0px, 0px, 0px); transform-style: preserve-3d; backface-visibility: hidden;">
                                            <li class="layer" data-depth="0.05">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/white-shoes.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.06">
                                                <img style="position: absolute; top: 31%; left: 46.5%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake1.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.07">
                                                <img class="animation-spin" style="position: absolute; top: 25%; left: 66%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake2.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.10">
                                                <img class="animation-wave" style="position: absolute; top: 50%; left: 80%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake3.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.15">
                                                <img style="position: absolute; top: 70%; left: 55%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake4.png}}" alt="" />
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-ibanner-layer" style="left: 11%; top: 50%; transform: translateY(-50%);">
                                <h2 style="font-size: 2.625em; line-height: 1; font-weight: 200; letter-spacing: 0.008em;" class="vc_custom_heading mb-2 align-left heading-light">Spring / Summer Season</h2>
                                <h4 style="font-size: 2.875em; line-height: 1; text-align: center;" class="vc_custom_heading d-inline-block mr-2 heading-light">
                                    up<br />
                                    to
                                </h4>
                                <h4 style="font-size: 6.125em; line-height: 1; letter-spacing: 0.035em;" class="vc_custom_heading d-inline-block mb-3 align-left heading-light">50% OFF</h4>
                                <div class="vc_custom_heading align-left"></div>
                                <h6 style="font-size: 1.125em; line-height: 1; font-weight: 700; letter-spacing: -0.02em;" class="vc_custom_heading pull-left mx-2 align-left text-uppercase heading-light">Starting at</h6>
                                <h6 style="font-size: 2.1em; line-height: 1; font-weight: 700; letter-spacing: -0.02em; margin-top: -0.1em;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-xl-4 align-left heading-secondary">
                                    <sup>$</sup>19<sup>99</sup>
                                </h6>
                                <div class="btn-container ls-200 d-inline-block"><button class="btn btn-modern btn-xl btn-light">Shop now</button></div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ibanner mb-0" style="background: #222529;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/02n.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer layer" style="width: 100%; left: 0%; top: 50%; transform: translateY(-50%);">
                                <div class="wpb_text_column wpb_content_element">
                                    <div class="wpb_wrapper">
                                        <ul class="scene" style="width: 100%; position: relative; transform: translate3d(0px, 0px, 0px); transform-style: preserve-3d; backface-visibility: hidden;">
                                            <li class="layer" data-depth="0.05">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/ball2.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.06">
                                                <img style="position: absolute; top: 70%; left: 42%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake1.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.07">
                                                <img class="animation-spin" style="position: absolute; top: 25%; left: 45%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake2.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.10">
                                                <img class="animation-wave" style="position: absolute; top: 49%; left: 21%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake3.png}}" alt="" />
                                            </li>
                                            <li class="layer" data-depth="0.15">
                                                <img style="position: absolute; top: 25%; left: 23%;" src="{{media url=wysiwyg/smartwave/porto/homepage/18/blurflake4.png}}" alt="" />
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-ibanner-layer right-0-mobile" style="right: 20%; top: 50%; transform: translateY(-50%);">
                                <h2 style="font-size: 2.625em; line-height: 1; font-weight: 200; letter-spacing: 0.008em;" class="vc_custom_heading mb-2 align-left heading-light">Spring / Summer Season</h2>
                                <h4 style="font-size: 2.875em; line-height: 1; text-align: center;" class="vc_custom_heading d-inline-block mr-2 heading-light">
                                    up<br />
                                    to
                                </h4>
                                <h4 style="font-size: 6.125em; line-height: 1; letter-spacing: 0.035em;" class="vc_custom_heading d-inline-block mb-3 align-left heading-light">50% OFF</h4>
                                <div class="vc_custom_heading align-left"></div>
                                <h6 style="font-size: 1.125em; line-height: 1; font-weight: 700; letter-spacing: -0.02em;" class="vc_custom_heading pull-left mx-2 align-left text-uppercase heading-light">Starting at</h6>
                                <h6 style="font-size: 2.1em; line-height: 1; font-weight: 700; letter-spacing: -0.02em; margin-top: -0.1em;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-xl-4 align-left heading-secondary">
                                    <sup>$</sup>19<sup>99</sup>
                                </h6>
                                <div class="btn-container ls-200 d-inline-block"><button class="btn btn-modern btn-xl btn-light">Shop now</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="porto-carousel owl-carousel home-banner-thumb">
                <div class="wpb_single_image wpb_content_element vc_align_left mb-0">
                    <div class="wpb_wrapper">
                        <div class="vc_single_image-wrapper vc_box_border_grey">
                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_thumb1.jpg}}" />
                        </div>
                    </div>
                </div>
                <div class="wpb_single_image wpb_content_element vc_align_left mb-0">
                    <div class="wpb_wrapper">
                        <div class="vc_single_image-wrapper vc_box_border_grey">
                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_thumb2.jpg}}" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
            var owl_18 = $("#banner-slider-demo-18").owlCarousel({
                items: 1,
                autoplay: false,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                dots: false,
                navRewind: true,
                animateIn: "fadeIn",
                animateOut: "fadeOut",
                loop: true,
                nav: false,
            });
            var owl_thumb_18 = $(".home-banner-thumb.owl-carousel").owlCarousel({
                items: 3,
                autoplay: false,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                dots: false,
                navRewind: true,
                animateIn: "fadeIn",
                animateOut: "fadeOut",
                loop: false,
                nav: false,
                margin: 10,
            });
            owl_18.on("translate.owl.carousel", syncPosition);
            owl_thumb_18.find(".owl-item").eq(0).addClass("synced");
            function syncPosition(event) {
                var current = event.item.index;
                current = current % event.item.count;
                owl_thumb_18.find(".owl-item").removeClass("synced").eq(current).addClass("synced");
                if (owl_thumb_18.data("owlCarousel") !== undefined) {
                    center(current);
                }
            }
            owl_thumb_18.on("click", ".owl-item", function (e) {
                e.preventDefault();
                var number = $(this).index();
                owl_18.trigger("to.owl.carousel", [number, 300, true]);
            });
            function center(number) {
                var sync2visible = sync2.data("owlCarousel").owl.visibleItems;
                var num = number;
                var found = false;
                for (var i in sync2visible) {
                    if (num === sync2visible[i]) {
                        var found = true;
                    }
                }

                if (found === false) {
                    if (num > sync2visible[sync2visible.length - 1]) {
                        sync2.trigger("owl.goTo", num - sync2visible.length + 2);
                    } else {
                        if (num - 1 === -1) {
                            num = 0;
                        }
                        sync2.trigger("owl.goTo", num);
                    }
                } else if (num === sync2visible[sync2visible.length - 1]) {
                    sync2.trigger("owl.goTo", sync2visible[1]);
                } else if (num === sync2visible[0]) {
                    sync2.trigger("owl.goTo", num - 1);
                }
            }
        });
        require(["jquery", "parallax"], function ($) {
            $(document).ready(function () {
                $(".scene").parallax();
            });
        });
    </script>
</div>
<div class="porto-inner-container" style="padding-top: 80px; padding-bottom: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-products wpb_content_element show-category filter-vertical archive-products mb-0">
                        {{block class="Smartwave\Porto\Block\Template" product_type="3" aspect_ratio="0" product_count="10" columns="5" image_width="300" image_height="300" template="ajaxproducts/ajaxproducts.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row no-padding">
    <div class="col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-ibanner mb-0" style="min-height: 300px;">
                <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_banner4.jpg}}" />
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="container">
                        <div class="porto-ibanner-container">
                            <div class="porto-ibanner-layer pl-1" style="left: 49%; top: 50%; transform: translateY(-50%);">
                                <h2 style="font-size: 2.5em; line-height: 1.2; letter-spacing: -0.025em;" class="vc_custom_heading mb-4 pb-xl-1 align-left text-uppercase heading-light">
                                    Ultra Boost
                                </h2>
                                <div class="wpb_single_image wpb_content_element vc_align_left mb-4 pb-xl-3">
                                    <div class="wpb_wrapper">
                                        <div class="vc_single_image-wrapper vc_box_border_grey">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shoes.png}}" class="d-block" />
                                        </div>
                                    </div>
                                </div>
                                <div class="btn-container mb-0 ls-200 d-inline-block">
                                    <button class="btn btn-modern btn-md btn-light">
                                        Shop Now
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="porto-inner-container" style="padding-top: 5rem; padding-bottom: 3.5rem;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div id="featured-products" class="porto-products wpb_content_element">
                        <h2 class="section-title text-center slider-title"><span class="inline-title">Featured Products</span><span class="line"></span></h2>
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="8"
                            product_type="3" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#featured-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 3,
                                            },
                                            768: {
                                                items: 3,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 6,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="vc_row wpb_row vc_inner row">
                        <div class="col-md-12 col-lg-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ibanner" style="min-height: 150px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_banner1.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer" style="left: 6%; top: 50%; transform: translateY(-50%);">
                                            <h4 style="font-size: 2.0625em; line-height: 1; font-weight: 200; letter-spacing: 0.075em;" class="vc_custom_heading mb-0 align-left">Summer Sale</h4>
                                            <h5 style="font-size: 3.0625em; line-height: 1;" class="vc_custom_heading mb-0 align-left">20% OFF</h5>
                                        </div>
                                        <div class="porto-ibanner-layer" style="right: 6%; top: 50%; transform: translateY(-50%);">
                                            <div class="btn-container ls-200 d-inline-block"><button class="btn btn-modern btn-md btn-dark">SHOP NOW</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ibanner" style="background: #222529; min-height: 150px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_banner2.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer" style="left: 6%; top: 50%; transform: translateY(-50%);">
                                            <h4 style="font-size: 2.0625em; line-height: 1; font-weight: 200; letter-spacing: 0.075em;" class="vc_custom_heading mb-0 align-left heading-light">Flash Sale</h4>
                                            <h5 style="font-size: 3.0625em; line-height: 1;" class="vc_custom_heading mb-0 align-left heading-light">30% OFF</h5>
                                        </div>
                                        <div class="porto-ibanner-layer" style="right: 6%; top: 50%; transform: translateY(-50%);">
                                            <div class="btn-container ls-200 d-inline-block"><button class="btn btn-modern btn-md btn-light">SHOP NOW</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row no-padding">
    <div class="col-md-12">
        <style>
            .porto-ibanner.has-parallax-bg > img {
                width: 58%;
                opacity: 0;
            }
        </style>
        <div class="wpb_wrapper vc_column-inner">
            <div
                class="porto-ibanner mb-0 has-parallax-bg"
                style="background: rgb(17, 17, 17);
                  min-height: 200px;
                  position: relative;
                  overflow: hidden;
                  background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_banner3.jpg}}');
                  background-size: cover;
                  background-position: 50% 0%;"
            >
                <img src="{{media url=wysiwyg/smartwave/porto/homepage/18/shop18_home_banner3.jpg}}" />
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="porto-ibanner-layer" style="width: 80%; left: 50%; top: 50%; transform: translate(-50%, -50%);">
                        <div>
                            <h2 style="font-size: 2.5em; line-height: 1; text-align: center; letter-spacing: -0.025em;" class="vc_custom_heading mb-4 pb-lg-3 text-uppercase heading-light">Explore the best of you</h2>
                            <div class="btn-container mb-0 ls-200 text-center"><button class="btn btn-modern btn-md btn-light">Shop Now</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="porto-inner-container" style="padding-top: 4.5rem; padding-bottom: 2.5rem; background-color: #111111;">
    <style>
        .wpb_wrapper .top-icon .porto-just-icon-wrapper {
            margin-bottom: 2rem;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row no-padding">
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box px-3 px-xl-4 style_1 top-icon">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #ffffff; font-size: 35px; display: inline-block;"><i class="Simple-Line-Icons-earphones-alt"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1.25rem; line-height: 1.2; color: #ffffff;">CUSTOMER SUPPORT</h3>
                            <p style="font-weight: 600; font-size: 0.875rem; line-height: 1; color: rgba(255, 255, 255, 0.7);">Need Assistence?</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 0.8125rem; line-height: 1.85;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec vestibulum magna, et dapib.</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box px-3 px-xl-4 style_1 top-icon">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #ffffff; font-size: 35px; display: inline-block;"><i class="Simple-Line-Icons-credit-card"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1.25rem; line-height: 1.2; color: #ffffff;">SECURED PAYMENT</h3>
                            <p style="font-weight: 600; font-size: 0.875rem; line-height: 1; color: rgba(255, 255, 255, 0.7);">Safe & Fast</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 0.8125rem; line-height: 1.85;">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec vestibulum magna, et dapibus lacus. Lorem ipsum dolor sit amet.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box px-3 px-xl-4 style_1 top-icon">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #ffffff; font-size: 35px; display: inline-block;"><i class="Simple-Line-Icons-action-undo"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1.25rem; line-height: 1.2; color: #ffffff;">Free Returns</h3>
                            <p style="font-weight: 600; font-size: 0.875rem; line-height: 1; color: rgba(255, 255, 255, 0.7);">Easy & Free</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 0.8125rem; line-height: 1.85;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec vestibulum magna, et dapib.</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box px-3 px-xl-4 style_1 top-icon">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #ffffff; font-size: 35px; display: inline-block;"><i class="porto-icon-shipping"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1.25rem; line-height: 1.2; color: #ffffff;">FREE SHIPPING</h3>
                            <p style="font-weight: 600; font-size: 0.875rem; line-height: 1; color: rgba(255, 255, 255, 0.7);">Orders Over $99</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 0.8125rem; line-height: 1.85;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec vestibulum magna, et dapib.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" style="background-color: #111111;">
    <div class="row">
        <div class="vc_column_container col-md-12">
            <div class="wpb_wrapper vc_column-inner">
                <div class="porto-separator mb-0"><hr class="separator-line align_center solid" style="background-color: #222222;" /></div>
            </div>
        </div>
    </div>
</div>
