<style>
    .cms-index-index .page-main {
        max-width: 100%;
    }
    .columns .column.main {
        padding-bottom: 0;
    }
    .custom-banner-1 {
        max-height: 843px;
        min-height: 843px;
        font-size: 1rem;
    }
    .custom-banner-1 .row {
        margin-right: 0;
        margin-left: 0;
    }
    .custom-banner-1 .row > [class*="col-"] {
        padding-right: 0;
        padding-left: 0;
    }
    .custom-layer-img {
        left: 606.781px;
        top: 88.5px;
    }
    .opacity-7 {
        opacity: 0.7;
    }
    .vc_btn3-container {
        margin-bottom: 20px;
    }
    .porto-u-heading {
        margin-bottom: 17px;
    }
    .porto-u-heading .porto-u-main-heading h1,
    .porto-u-heading .porto-u-main-heading h2,
    .porto-u-heading .porto-u-main-heading h3,
    .porto-u-heading .porto-u-main-heading h4,
    .porto-u-heading .porto-u-main-heading h5,
    .porto-u-heading .porto-u-main-heading h6 {
        margin: 0;
        padding: 0;
        line-height: normal;
    }
    .custom-list-1 {
        margin-left: -4px;
        list-style: none;
        font-size: 0.875em;
        padding-left: 0;
    }
    .custom-list-1 li {
        padding: 7px 0;
        letter-spacing: -0.035em;
        margin: 0;
    }
    .custom-list-1 li i {
        margin-right: 5.5px;
    }
    .coupon-sale-text {
        position: relative;
        padding: 0 13px;
    }
    .coupon-sale-text sup {
        font-size: 0.5em;
    }
    .coupon-sale-text::before {
        content: "";
        display: block;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        transform: rotate(-2deg);
        z-index: 0;
        background-color: #ff5b5b;
    }
    .coupon-sale-text h2 {
        position: relative;
    }
    .custom-pos-1 {
        margin-right: 6px;
        vertical-align: 7px;
        text-indent: -2px;
    }
    .custom-indent-1 {
        text-indent: -1px;
    }
    .custom-triangle::before,
    .custom-triangle > .container::before {
        content: "";
        position: absolute;
        bottom: -1px;
        left: 0;
        right: 0;
        border-bottom: 5.209vw solid #fff;
        z-index: 2;
        border-left: 50vw solid transparent;
        border-right: 50vw solid transparent;
    }
    .banner-effect,
    .banner-effect-wrapper {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
    .porto-ibanner .porto-ibanner-desc .porto-ibanner-container {
        position: relative;
        height: 100%;
    }
    .porto-ibanner-layer {
        text-align: left;
        font-size: 1rem;
        position: absolute;
        z-index: 10;
    }
    .owl-carousel.nav-inside .owl-dots {
        bottom: 2px;
        margin-top: 10px;
        position: absolute;
        right: 6px;
        left: 6px;
        z-index: 1;
    }
    .custom-dots-pos-1 .owl-nav.disabled + .owl-dots {
        bottom: 27%;
    }
    .dots-style-1.owl-carousel .owl-dot span {
        width: 20px;
        height: 20px;
        border-radius: 50%;
    }
    .products-slider.dots-style-1.owl-carousel .owl-dot span {
        width: 14px;
        height: 14px;
    }
    .products-slider.owl-carousel.dots-style-1 .owl-dot.active span:after,
    .products-slider.owl-carousel.dots-style-1 .owl-dot:hover span:after {
        left: 3px;
        right: 3px;
        top: 3px;
        bottom: 3px;
    }
    .dots-style-1.owl-carousel .owl-dot.active span:after,
    .dots-style-1.owl-carousel .owl-dot:hover span:after {
        left: 4px;
        right: 4px;
        bottom: 4px;
        top: 4px;
        background-color: #222529;
        color: #222529;
    }
    .custom-dot-black .owl-carousel.dots-style-1 .owl-dot span {
        border-color: #8e9092;
    }
    .custom-dot-black .owl-carousel.dots-style-1 .owl-dot.active span,
    .custom-dot-black .owl-carousel.dots-style-1 .owl-dot:hover span {
        border-color: #222529;
    }
    .z-index-1 {
        z-index: 1;
    }
    .custom-service .row {
        justify-content: center;
    }
    .custom-service .porto-sicon-box {
        box-shadow: 0 0 50px 0 rgba(0, 0, 0, 0.07);
    }
    .custom-sale {
        display: inline-block;
        position: relative;
        z-index: 1;
        padding: 0.7em 1em;
        margin-left: 44px;
        margin-right: 26px;
        color: #fff;
    }
    .custom-sale::before {
        content: "";
        display: block;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        transform: rotate(-2deg);
        z-index: -1;
        background: linear-gradient(-139deg, #222529, #000);
    }
    .custom-cta .vc_row-has-fill {
        align-items: center;
    }
    .custom-cta-left .wpb_wrapper {
        display: flex;
        align-items: center;
    }
    @media (max-width: 1279px) {
        .ps-m-xl {
            padding-left: 0.5rem !important;
        }
    }
    @media (max-width: 991px) {
        .custom-banner-1 {
            max-height: 680px;
            min-height: 680px;
            padding: 50px 0 50px !important;
            font-size: 0.8rem;
        }
        .custom-banner-2 {
            min-height: 680px !important;
        }
        .custom-cta .vc_row-has-fill,
        .custom-cta .wpb_wrapper {
            flex-direction: column;
        }
        .custom-padding-category {
            padding-bottom: 85px !important;
        }
        .custom-sale {
            margin: 0 20px;
        }
        .custom-service {
            margin-top: 0 !important;
        }
    }
    @media (max-width: 767px) {
        .custom-dots-pos-1 .owl-nav.disabled + .owl-dots {
            bottom: 10%;
        }
        .ps-m-xl {
            padding-left: 5px !important;
        }
        .text-desc-center .porto-u-heading,
        .text-desc-center .vc_column-inner {
            text-align: center !important;
        }
    }
    @media (max-width: 767px) and (min-width: 576px) {
        .of-md-20 {
            margin-left: 20%;
        }
    }
    @media (max-width: 575px) {
        .custom-banner-1 {
            font-size: 0.65rem;
        }
        .of-md-20 {
            width: 50%;
            flex: 0 0 50%;
            max-width: 50%;
        }
    }
    @media (min-width: 992px) {
        .text-lg-start {
            text-align: left !important;
        }
    }
    ul.products li.product-category .thumb-info-wrapper:after {
        background: rgba(27, 27, 23, 0);
    }
    ul.products li.product-category:hover .thumb-info-wrapper:after {
        background: rgba(27, 27, 23, 0.15);
    }
    .custom-dot-white .owl-carousel.dots-style-1 .owl-dot span {
        border-color: #fff;
        opacity: 0.5;
    }
    .custom-dot-white .owl-carousel.dots-style-1 .owl-dot.active span,
    .custom-dot-white .owl-carousel.dots-style-1 .owl-dot:hover span {
        border-color: #fff;
        opacity: 1;
    }
    .custom-dot-white .owl-carousel.dots-style-1 .owl-dot.active span:after,
    .custom-dot-white .owl-carousel.dots-style-1 .owl-dot:hover span:after {
        background-color: #fff;
        color: #fff;
    }
    .porto-recent-posts {
        display: flex;
        flex-wrap: wrap;
        margin-left: -10px;
        margin-right: -10px;
    }
    .porto-recent-posts .post-slide {
        flex: 0 0 33.333%;
        max-width: 33.333%;
        padding: 0 10px;
        margin-bottom: 30px;
    }
    @media (max-width: 991px) {
        .porto-recent-posts .post-slide {
            flex: 0 0 50%;
            max-width: 50%;
        }
    }
    @media (max-width: 767px) {
        .porto-recent-posts .post-slide {
            flex: 0 0 100%;
            max-width: 100%;
        }
    }
    .porto-recent-posts .post-item {
        box-shadow: 0 0 50px rgb(0 0 0 / 7%);
        padding: 1.5rem 1.2rem 2.4rem;
    }
    .porto-recent-posts .post-item .post-date {
        top: 35px;
        left: 30px;
    }
    .porto-recent-posts h4 {
        font-size: 20px;
        font-weight: 600;
        letter-spacing: -0.025em;
        margin-top: 1rem;
        margin-bottom: 20px;
    }
    .porto-recent-posts .post-item .post-excerpt {
        font-size: inherit;
        margin-bottom: 0;
        line-height: 25px;
        letter-spacing: -0.028em;
    }
    .post-item .read-more,
    .post-item .read-more-block {
        font-size: inherit;
        font-weight: 700;
        color: #3467ef;
        display: block;
        margin-top: 12px;
        text-transform: uppercase;
    }
</style>
<div class="custom-dot-black">
    <div id="banner-slider-demo-36" class="porto-carousel owl-carousel home-banner-slider nav-inside nav-style-4 show-nav-hover custom-dots-pos-1 dots-style-1 nav-inside-center">
        <div
            class="vc_row wpb_row vc_inner custom-triangle custom-banner-1 vc_row-has-fill vc_row-o-content-middle vc_row-flex mx-0"
            style="background-image: url({{media url=wysiwyg/smartwave/porto/homepage/36/intro-1.jpg}});padding-top: 105px;padding-bottom: 290px;background-color: #f4f4f4;background-position: center;background-repeat: no-repeat;background-size: cover;"
        >
            <div class="porto-wrap-container container">
                <div class="row align-items-center">
                    <div class="text-desc-center vc_column_container col-md-6 col-xl-6 col-lg-6" data-appear-animation="fadeInUp" data-appear-animation-delay="150">
                        <div class="wpb_wrapper vc_column-inner">
                            <div class="porto-u-heading opacity-7 m-b-sm p-b-xs">
                                <div class="porto-u-main-heading">
                                    <h2 class="mb-0" style="font-weight: 500; font-size: 1.188125em; letter-spacing: 0.076em;">Shop for our products at exclusive prices</h2>
                                </div>
                            </div>
                            <div class="porto-u-heading mb-1 porto-u-9480">
                                <div class="porto-u-main-heading">
                                    <h2 class="mb-0" style="font-weight: 700; font-size: 3em; line-height: 1; letter-spacing: -0.021em;">Infrared Thermometers</h2>
                                </div>
                            </div>
                            <div class="porto-u-heading m-b-sm">
                                <div class="porto-u-main-heading">
                                    <h2 class="mb-0" style="font-weight: 700; font-size: 5.879375em; line-height: 1.074;">70% OFF</h2>
                                </div>
                            </div>
                            <div class="vc_btn3-container vc_btn3-inline">
                                <a
                                    data-appear-animation="fadeInUp"
                                    data-appear-animation-delay="200"
                                    class="vc_btn3 vc_btn3-shape-square btn btn-md btn-primary"
                                    style="font-size: 0.955em; font-weight: 700; letter-spacing: 0.01em; padding: 1.2em 2.9em;"
                                    href="#"
                                    title="Shop"
                                >
                                    SHOP NOW!
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="of-md-20 vc_column_container col-md-3 col-xl-3 col-lg-3 col-3">
                        <div class="wpb_wrapper vc_column-inner">
                            <div class="wpb_single_image wpb_content_element vc_align_left" data-plugin-float-element="" data-plugin-options="{"startPos":"top","speed":"6","transition":true,"horizontal":false,"transitionDuration":1000}"
                            style="top: 0px; transition: transform 1000ms ease-out 0ms; transform: translate3d(0px, 5.59856%, 0px);">
                            <div class="wpb_wrapper">
                                <div class="vc_single_image-wrapper vc_box_border_grey">
                                    <img
                                        width="299"
                                        height="451"
                                        src="{{media url=wysiwyg/smartwave/porto/homepage/36/thermometer.png}}"
                                        style="width: auto;"
                                        class="vc_single_image-img attachment-full"
                                        alt="thermometer"
                                        title="thermometer"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ps-m-xl vc_column_container col-md-3 col-xl-3 col-lg-3 col-6" style="margin-bottom: 32px; padding-left: 43.2px;">
                    <div class="wpb_wrapper vc_column-inner">
                        <div class="porto-image-frame w-auto m-b-md" data-appear-animation="fadeInRight" data-appear-animation-delay="200">
                            <img alt="fda" src="{{media url=wysiwyg/smartwave/porto/homepage/36/fda.png}}" style="width: auto;" class="img-responsive img-rounded" width="102" height="61" />
                        </div>
                        <div class="porto-u-heading mb-0 pb-2" data-appear-animation="fadeInRight" data-appear-animation-delay="280">
                            <div class="porto-u-sub-heading" style="">
                                <ul class="opacity-7 text-body custom-list-1 ps-0 m-b-md">
                                    <li><i class="fa fa-check"></i>Non-Contact Temperature Taking</li>
                                    <li><i class="fa fa-check"></i>Get Readings in Only 1 Second</li>
                                    <li><i class="fa fa-check"></i>Fever Alarm at 100°F</li>
                                </ul>
                                <p></p>
                            </div>
                        </div>
                        <div class="porto-u-heading mb-2 pb-1 custom-indent-1" data-appear-animation="fadeInRight" data-appear-animation-delay="330">
                            <div class="porto-u-sub-heading" style="font-weight: 700; color: #222529; font-size: 15.72px; line-height: 1; letter-spacing: -0.025em;">from <del>$299.99</del></div>
                        </div>
                        <div class="porto-u-heading d-inline-block custom-pos-1" data-appear-animation="fadeInRight" data-appear-animation-delay="330">
                            <div class="porto-u-main-heading">
                                <h2 class="mb-0" style="font-weight: 700; font-size: 1.25em; line-height: 1; letter-spacing: -0.025em;">to</h2>
                            </div>
                        </div>
                        <div class="porto-u-heading coupon-sale-text d-inline-block" data-appear-animation="fadeInRight" data-appear-animation-delay="330">
                            <div class="porto-u-main-heading">
                                <h2 class="mb-0" style="font-weight: 700; color: #ffffff; font-size: 2.5em; line-height: 1.2; letter-spacing: -0.02em;"><sup>$</sup>199<sup>99</sup></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="porto-ibanner custom-triangle custom-banner-2 mb-0" style="min-height: 843px;">
        <div class="banner-effect-wrapper">
            <div class="banner-effect kenBurnsToRight" style="background-image: url({{media url=wysiwyg/smartwave/porto/homepage/36/intro-2.jpg}}); background-size: cover;background-position: center;animation-duration: 30s;"></div>
        </div>
        <img alt="intro slider" width="1903" height="843" class="porto-ibanner-img" src="{{media url=wysiwyg/smartwave/porto/homepage/36/intro-2.jpg}}" />
        <div class="porto-ibanner-desc no-padding d-flex">
            <div class="container">
                <div class="porto-ibanner-container">
                    <div class="porto-ibanner-layer" data-appear-animation="fadeInUp" data-appear-animation-delay="50" style="right: 10%; top: 22.1%;">
                        <div class="porto-u-heading opacity-7 m-b-sm p-b-xs">
                            <div class="porto-u-main-heading">
                                <h2 style="font-weight: 500; font-size: 1.188125em; letter-spacing: 0.076em;">Shop for our products at exclusive prices</h2>
                            </div>
                        </div>
                        <div class="porto-u-heading mb-1">
                            <div class="porto-u-main-heading">
                                <h2 style="font-weight: 700; font-size: 3em; line-height: 1; letter-spacing: -0.021em;">Pro Respirator Mask</h2>
                            </div>
                        </div>
                        <div class="porto-u-heading m-b-sm custom-text-indent">
                            <div class="porto-u-main-heading">
                                <h2 style="font-weight: 700; font-size: 5.879375em; line-height: 1.074;">50% OFF</h2>
                            </div>
                        </div>
                        <div class="vc_btn3-container vc_btn3-inline">
                            <a
                                data-appear-animation="fadeInUp"
                                data-appear-animation-delay="150"
                                class="vc_btn3 vc_btn3-shape-square btn btn-md btn-primary"
                                style="font-size: 0.955em; font-weight: 700; letter-spacing: 0.01em; padding: 1.2em 2.9em;"
                                href="#"
                                title="Shop"
                            >
                                SHOP NOW!
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
        var banner_owl = $("#banner-slider-demo-36");
        banner_owl.owlCarousel({
            items: 1,
            autoplay: false,
            autoplayTimeout: 7000,
            autoplayHoverPause: true,
            dots: true,
            nav: false,
            navRewind: true,
            animateIn: "fadeIn",
            animateOut: "fadeOut",
            loop: true,
            lazyLoad: true,
        });
        var portoSlideCarouselInit = function (e) {
            var $this = $(e.currentTarget);
            if ($this.find(".owl-item.cloned").length) {
                $this.find(".appear-animation").themeAnimate();
            }
            setTimeout(function () {
                var $hiddenItems = $this.find(".owl-item:not(.active)");
                if (window.innerWidth > 767) {
                    $hiddenItems.find(".appear-animation").removeClass("appear-animation-visible");
                    $hiddenItems.find(".appear-animation").each(function () {
                        var $el = $(this),
                            delay = Math.abs($el.data("appear-animation-delay") ? $el.data("appear-animation-delay") : 0);
                        if (delay > 1) {
                            this.style.animationDelay = delay + "ms";
                        }

                        var duration = Math.abs($el.data("appear-animation-duration") ? $el.data("appear-animation-duration") : 1000);
                        if (1000 != duration) {
                            this.style.animationDuration = duration + "ms";
                        }
                    });
                }
            }, 300);
        };
        var portoCarouselTranslated = function (e) {
            var $this = $(e.currentTarget);
            if (window.innerWidth > 767) {
                if ($this.find(".owl-item.cloned").length && $this.find(".appear-animation:not(.appear-animation-visible)").length) {
                    $(document.body).trigger("appear_refresh");
                }
            }
            var $active = $this.find(".owl-item.active");
            if ($active.hasClass("translating")) {
                $active.removeClass("translating");
                return;
            }
            $this.find(".owl-item.translating").removeClass("translating");

            if (window.innerWidth > 767) {
                $this.find(".appear-animation").removeClass("appear-animation-visible");
                $active.find(".appear-animation").each(function () {
                    var $animation_item = $(this),
                        anim_name = $animation_item.data("appear-animation");
                    $animation_item.addClass(anim_name + " appear-animation-visible");
                });
            }
        };
        banner_owl.on("initialized.owl.carousel", portoSlideCarouselInit).on("translated.owl.carousel", portoCarouselTranslated);
    });
</script>
<div class="vc_row wpb_row top-row custom-service position-relative z-index-1 porto-inner-container" style="margin-top: -234px; margin-bottom: 3.2rem;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-6 col-xl-4 col-lg-4" data-appear-animation="fadeInRight" data-appear-animation-delay="500">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box style_1 top-icon" style="padding: 50px 30px 52px 30px; background-color: #ffffff;">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 50px; margin-bottom: 22px;">
                                <i class="porto-icon-earphones-alt"></i>
                            </div>
                        </div>
                        <div class="porto-sicon-header" style="margin-bottom: 13px;">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: 0; margin-bottom: 5px;">Customer Support</h3>
                            <p style="font-weight: 400; font-size: 14px; line-height: 1.57; color: #555555;">NEED ASSISTENCE?</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 14px; line-height: 25px; letter-spacing: -0.04em;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-6 col-xl-4 col-lg-4" data-appear-animation="zoomIn" data-appear-animation-delay="0200">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box style_1 top-icon" style="padding: 50px 30px 52px 30px; background-color: #ffffff;">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 53px; margin-bottom: 20px;">
                                <i class="porto-icon-credit-card"></i>
                            </div>
                        </div>
                        <div class="porto-sicon-header" style="margin-bottom: 11px;">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: 0; margin-bottom: 5px;">Secure Payment</h3>
                            <p style="font-weight: 400; font-size: 14px; line-height: 1.57; color: #555555;">SAFE & FAST</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 14px; line-height: 25px; letter-spacing: -0.04em;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-6 col-xl-4 col-lg-4" data-appear-animation="fadeInLeft" data-appear-animation-delay="500">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box style_1 top-icon" style="padding: 50px 30px 52px 30px; background-color: #ffffff;">
                        <div class="porto-sicon-top">
                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 53px; margin-bottom: 21px;">
                                <i class="porto-icon-action-undo"></i>
                            </div>
                        </div>
                        <div class="porto-sicon-header" style="margin-bottom: 13px;">
                            <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: 0; margin-bottom: 2px;">Free Returns</h3>
                            <p style="font-weight: 400; font-size: 14px; line-height: 1.57; color: #555555;">EASY & FREE</p>
                        </div>
                        <div class="porto-sicon-description" style="font-size: 14px; line-height: 25px; letter-spacing: -0.04em;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row m-b-sm porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-0 text-center" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
                        <div class="porto-u-main-heading">
                            <h6 style="color: #777777; margin-bottom: 6px; font-size: 14px; line-height: 1; letter-spacing: -0.025em;">EXCLUSIVE SELECTION</h6>
                        </div>
                    </div>
                    <div class="porto-u-heading mb-0 text-center" data-appear-animation="fadeInUp" data-appear-animation-delay="300">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 31px; font-size: 28px; line-height: 1; letter-spacing: -0.025em;">Featured Products</h2>
                        </div>
                    </div>
                    <div id="featured-products" class="porto-products wpb_content_element custom-dots-pos-2 custom-dot-black theme_option" data-appear-animation="fadeIn" data-appear-animation-delay="400">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="dots-style-1" product_count="8" aspect_ratio="0" image_width="350" image_height="350"
                            template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#featured-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: true,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 4,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row custom-cta no-padding vc_row-has-fill porto-inner-container" style="padding-bottom: 60px;">
    <div class="porto-wrap-container container">
        <div class="row align-items-center">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div
                        class="vc_row wpb_row vc_inner row mx-0 vc_row-has-fill"
                        style="background-image: url({{media url=wysiwyg/smartwave/porto/homepage/36/cta.jpg}});padding-top: 55px !important;padding-bottom: 55px;background-color: #f4f4f4;background-position: center;background-repeat: no-repeat; background-size: cover;"
                    >
                        <div class="custom-cta-left vc_column_container col-md-9">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-u-heading d-inline-block mb-lg-0 mb-3 custom-sale" data-appear-animation="fadeInRight" data-appear-animation-delay="200">
                                    <div class="porto-u-main-heading">
                                        <h2 style="font-weight: 700; color: #ffffff; font-size: 20.57px; line-height: 1; letter-spacing: -0.025em;">BIG SALE</h2>
                                    </div>
                                </div>
                                <div class="porto-u-heading d-inline-block mb-lg-0 text-lg-start text-center" data-appear-animation="fadeInRight" data-appear-animation-delay="300">
                                    <div class="porto-u-main-heading">
                                        <h2 style="font-weight: 700; margin-bottom: 9px; font-size: 32px; line-height: 1.1; letter-spacing: -0.025em;">Delivering Covid19 Essentials</h2>
                                    </div>
                                    <div class="porto-u-sub-heading" style="font-size: 16px; line-height: 1.1; letter-spacing: -0.025em;">HAND SANITIZER, INFRARED THERMOMETERS AND MORE…</div>
                                </div>
                            </div>
                        </div>
                        <div class="vc_column_container col-md-3">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="vc_btn3-container mb-0 text-center">
                                    <a
                                        data-appear-animation="fadeInUp"
                                        data-appear-animation-delay="150"
                                        class="vc_btn3 vc_btn3-shape-square btn btn-md btn-primary"
                                        style="font-size: 13.5px; font-weight: 700; letter-spacing: 0.01em; padding: 1.2rem 3.8rem;"
                                        href="#"
                                        title="Shop"
                                    >
                                        SHOP NOW
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row vc_row-has-fill porto-inner-container" style="padding-top: 60px; padding-bottom: 27px; background-color: #fbfbfb;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-0 text-center" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
                        <div class="porto-u-main-heading">
                            <h6 style="color: #777777; margin-bottom: 6px; font-size: 14px; line-height: 1; letter-spacing: -0.025em;">RECENTLY ARRIVED</h6>
                        </div>
                    </div>
                    <div class="porto-u-heading mb-0 text-center" data-appear-animation="fadeInUp" data-appear-animation-delay="300">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 31px; font-size: 28px; line-height: 1; letter-spacing: -0.025em;">New Arrivals</h2>
                        </div>
                    </div>
                    <div id="new-products" class="porto-products wpb_content_element custom-dots-pos-2 custom-dot-black theme_option" data-appear-animation="fadeIn" data-appear-animation-delay="500">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="dots-style-1" product_count="8" aspect_ratio="0" image_width="350" image_height="350"
                            template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#new-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: true,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 4,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div
    class="vc_row wpb_row top-row custom-triangle position-relative custom-padding-category vc_row-has-fill porto-inner-container"
    style="background-image: url({{media url=wysiwyg/smartwave/porto/homepage/36/parallax-1.jpg}});padding-top: 85px !important;padding-bottom: 160px !important;background-color: #3467ef;background-position: center;background-repeat: no-repeat;background-size: cover;"
>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12 appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp" data-appear-animation-delay="200" style="animation-delay: 200ms;">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-0 text-center">
                        <div class="porto-u-main-heading">
                            <h6 style="color: #ffffff; margin-bottom: 6px; font-size: 14px; line-height: 1; letter-spacing: -0.025em;">DEPARTMENTS</h6>
                        </div>
                    </div>
                    <div class="porto-u-heading mb-0 text-center">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; color: #ffffff; margin-bottom: 36px; font-size: 28px; line-height: 1; letter-spacing: -0.025em;">Browse Our Categories</h2>
                        </div>
                    </div>
                    <div class="category-slider porto-products wpb_content_element custom-category custom-dot-white porto-product-category-widget hide-count">
                        <div class="slider-wrapper">
                            <div class="woocommerce columns-6">
                                <ul class="products products-container products-slider owl-carousel category-pos-bottom category-text-center category-color-dark dots-style-1">
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-1.jpg}}" alt="Cardiology" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Cardiology</h3>
                                                        <span class="thumb-info-type"> <mark class="count">4</mark> products </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-2.jpg}}" alt="Gastroenterology" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Gastroenterology</h3>
                                                        <span class="thumb-info-type"> <mark class="count">4</mark> products </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="https://www.portotheme.com/wordpress/porto/shop38/product-category/pulmonology/" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-3.jpg}}" alt="Pulmonology" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Pulmonology</h3>
                                                        <span class="thumb-info-type"> <mark class="count">1</mark> product </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-4.jpg}}" alt="Dental Care" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Dental Care</h3>
                                                        <span class="thumb-info-type"> <mark class="count">1</mark> product </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-4.jpg}}" alt="Gynecology" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Gynecology</h3>
                                                        <span class="thumb-info-type"> <mark class="count">1</mark> product </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-6.jpg}}" alt="Hepatology" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Hepatology</h3>
                                                        <span class="thumb-info-type"> <mark class="count">4</mark> products </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="product-category product-col">
                                        <a href="#" aria-label="category">
                                            <div class="thumb-info align-center">
                                                <div class="thumb-info-wrapper tf-none">
                                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/36/cat-3.jpg}}" alt="Respiratory" width="300" height="300" />
                                                </div>
                                                <div class="thumb-info-wrap">
                                                    <div class="thumb-info-title">
                                                        <h3 class="sub-title thumb-info-inner">Respiratory</h3>
                                                        <span class="thumb-info-type"> <mark class="count">1</mark> product </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                                <script type="text/javascript">
                                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                        $(".category-slider .owl-carousel").owlCarousel({
                                            autoplay: false,
                                            autoplayTimeout: 5000,
                                            autoplayHoverPause: true,
                                            loop: false,
                                            navRewind: true,
                                            lazyLoad: true,
                                            margin: 0,
                                            nav: false,
                                            dots: true,
                                            responsive: {
                                                0: {
                                                    items: 2,
                                                },
                                                640: {
                                                    items: 2,
                                                },
                                                768: {
                                                    items: 3,
                                                },
                                                992: {
                                                    items: 4,
                                                },
                                                1200: {
                                                    items: 6,
                                                },
                                            },
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row mb-5 porto-inner-container" style="margin-top: 48px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-6 col-xl-3 col-lg-3" data-appear-animation="fadeInLeft" data-appear-animation-delay="400">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading m-b-md">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: -0.025em;">Featured</h2>
                        </div>
                    </div>
                    <div class="wpb_content_element">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-6 col-xl-3 col-lg-3" data-appear-animation="fadeInLeft" data-appear-animation-delay="200">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading m-b-md">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: -0.025em;">Best Selling</h2>
                        </div>
                    </div>
                    <div class="wpb_content_element">
                        {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-6 col-xl-3 col-lg-3" data-appear-animation="fadeInRight" data-appear-animation-delay="200">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading m-b-md">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: -0.025em;">Latest</h2>
                        </div>
                    </div>
                    <div class="wpb_content_element">
                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-6 col-xl-3 col-lg-3" data-appear-animation="fadeInRight" data-appear-animation-delay="300">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading m-b-md">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; font-size: 22px; line-height: 1; letter-spacing: -0.025em;">Top Rated</h2>
                        </div>
                    </div>
                    <div class="wpb_content_element">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row no-padding porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12" data-appear-animation="fadeInUp" style="padding-top: 80px; padding-bottom: 35px; border-top: #e7e7e7 solid 1px; border-bottom: #e7e7e7 solid 1px;">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-0 text-center">
                        <div class="porto-u-main-heading">
                            <h6 style="color: #777777; margin-bottom: 6px; font-size: 14px; line-height: 1; letter-spacing: -0.025em;">OUR BLOG</h6>
                        </div>
                    </div>
                    <div class="porto-u-heading mb-0 text-center">
                        <div class="porto-u-main-heading">
                            <h2 style="font-weight: 700; margin-bottom: 9px; font-size: 28px; line-height: 1; letter-spacing: -0.025em;">Recent Articles and News</h2>
                        </div>
                        <div class="porto-u-sub-heading" style="font-weight: 300; margin-bottom: 27px; font-size: 14px; line-height: 28px; letter-spacing: -0.03em;">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed imperdiet libero idnisl euis
                        </div>
                    </div>
                    <div class="porto-recent-posts porto-blog wpb_content_element">
                        {{widget type="Magefan\Blog\Block\Widget\Recent" number_of_posts="4" custom_template="recent_home.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row top-row porto-inner-container" data-appear-animation="fadeInUp" data-appear-animation-delay="250" style="margin-top: 56px; margin-bottom: 40px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-carousel brand-carousel owl-carousel">
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo1.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo2.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo3.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo4.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo5.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/homepage/36/logo6.png}}" alt="" /></div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".brand-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 3,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 6,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
