<style>
    .cms-index-index .page-main {
        margin-top: 0;
    }
    .porto-menu-links > .column-inner {
        border: 1px solid #e7e7e7;
    }
    .porto-menu-links .porto-links-block {
        border: none;
        font-weight: 600;
    }
    .porto-links-block .links-title {
        background: #f6f7f9;
        border-bottom: none;
        font-family: Poppins;
        line-height: 1.4;
        color: #222529;
    }
    .porto-links-block .links-content ul {
        padding-top: 0;
    }
    .porto-links-block li.porto-links-item > a {
        padding: 13px 0;
        margin: 0 20px;
        border-top-color: #e7e7e7;
        color: #555;
    }
    .porto-menu-links .btn {
        font-size: 1em;
        font-weight: 700;
        padding: 15px 0 15px;
        border-radius: 0;
    }
    .coupon-sale-text {
        transform: rotate(-2deg);
        letter-spacing: -0.01em;
        position: relative;
        font-weight: 700;
    }
    .coupon-sale-text b {
        display: inline-block;
        font-size: 1.6em;
        padding: 5px 8px;
        background: #fff;
    }
    .owl-carousel.nav-inside-left .owl-dots {
        left: 7.25%;
        bottom: 25px;
    }
    .home-banner-slider .owl-dots .owl-dot span {
        border-color: #fff;
    }
    .home-banner-slider .owl-dots .owl-dot.active span,
    .home-banner-slider .owl-dots .owl-dot:hover span {
        color: #222529;
    }
    .home-bar .porto-sicon-box {
        justify-content: center;
        padding: 12px 0;
        margin: 12px 0;
        border-right: 1px solid #e7e7e7;
    }
    .home-bar .col-lg-4:last-child .porto-sicon-box {
        border: none;
    }
    @media (max-width: 991px) {
        .home-bar .col-lg-4:not(:last-child) {
            border-bottom: 1px solid #e7e7e7;
        }
        .home-bar .porto-sicon-box {
            border-right: none;
            justify-content: flex-start;
            padding: 12px 30px;
        }
    }
    @media (min-width: 768px) and (max-width: 991px) {
        .home-banners .porto-ultimate-content-box {
            font-size: 8px;
        }
    }
    @media (max-width: 767px) {
        .porto-ultimate-content-box {
            font-size: 8px;
        }
    }
</style>
<div class="container" style="padding-top: 20px;">
    <div class="row">
        <div class="col-lg-3">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block8')->toHtml() ?>
        </div>
        <div class="order-2 home-banner-slider col-lg-9">
            <div id="banner-slider-demo-2" class="porto-carousel home-banner-slider owl-carousel dots-style-1 mb-0 nav-inside nav-inside-left">
                <div class="porto-ultimate-content-box-container">
                    <div
                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                        style="padding-top: 20px;
                      padding-bottom: 20px;
                      padding-left: 7.25%;
                      background-color: #6cb2d9;
                      background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center center;
                      background-color: rgba(0, 0, 0, 0);
                      min-height: 415px;
                      background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/02/shop2_home_slider1.jpg}}');
                      "
                    >
                        <h4 style="font-size: 1.6em; color: rgba(255, 255, 255, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 align-left">Find the Boundaries. Push Through!</h4>
                        <h2 style="font-size: 4.6em; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading mb-0 align-left heading-light">Summer Sale</h2>
                        <h3 style="font-size: 8em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left heading-light">30% OFF</h3>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="column-inner">
                                    <h4 style="font-size: 1.2em; line-height: 1; font-weight: 400;" class="vc_custom_heading mr-3 pull-left p-t-sm align-left text-uppercase heading-light">Starting At</h4>
                                    <h4 style="font-size: 1.6em; color: #ff7272; line-height: 1;" class="vc_custom_heading coupon-sale-text d-inline-block mr-2 align-left">
                                        <b><sup>$</sup>199<sup>99</sup></b>
                                    </h4>
                                    <div class="btn-container mb-0 d-inline-block" style="margin-left: -3px;"><button class="btn btn-modern btn-lg btn-dark">Get Yours!</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="porto-ultimate-content-box-container">
                    <div
                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                        style="padding-top: 20px;
                      padding-bottom: 20px;
                      padding-left: 7.25%;
                      background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center center;
                      background-color: rgba(0, 0, 0, 0);
                      min-height: 415px;
                      background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/02/shop2_home_slider2.jpg}}');
                      "
                    >
                        <h4 style="font-size: 1.6em; color: rgba(119, 119, 119, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 mb-2 align-left">OVER 200 PRODUCTS WITH DISCOUNTS</h4>
                        <h3 style="font-size: 5.5em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left heading-dark">GREAT DEALS</h3>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="column-inner">
                                    <h4 style="font-size: 1.4em; line-height: 1.5; font-weight: 700;" class="vc_custom_heading mr-2 pull-left align-left text-uppercase heading-dark">Starting At</h4>
                                    <h4 style="font-size: 2.6em; line-height: 1;" class="vc_custom_heading pull-left m-r-lg align-left heading-dark">
                                        <b><sup>$</sup>299<sup>99</sup></b>
                                    </h4>
                                    <div class="btn-container mb-0 d-inline-block"><button class="btn btn-modern btn-lg btn-dark">Get Yours!</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="porto-ultimate-content-box-container">
                    <div
                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                        style="padding-top: 20px;
                      padding-bottom: 20px;
                      padding-left: 7.25%;
                      background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center center;
                      background-color: rgba(0, 0, 0, 0);
                      min-height: 415px;
                      background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/02/shop2_home_slider3.jpg}}');
                      "
                    >
                        <h4 style="font-size: 1.6em; color: rgba(119, 119, 119, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 mb-2 align-left">UP TO 70% OFF</h4>
                        <h3 style="font-size: 4.8em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left heading-dark">NEW ARRIVALS</h3>
                        <div class="vc_row wpb_row vc_inner row">
                            <div class="vc_column_container col-md-12">
                                <div class="wpb_wrapper vc_column-inner">
                                    <h4 style="font-size: 1.4em; line-height: 1.5; font-weight: 700;" class="vc_custom_heading mr-2 pull-left align-left text-uppercase heading-dark">Starting At</h4>
                                    <h4 style="font-size: 2.6em; line-height: 1;" class="vc_custom_heading pull-left m-r-lg align-left heading-dark">
                                        <b><sup>$</sup>299<sup>99</sup></b>
                                    </h4>
                                    <div class="btn-container mb-0 d-inline-block"><button class="btn btn-modern btn-lg btn-dark">Get Yours!</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                    $("#banner-slider-demo-2").owlCarousel({
                        items: 1,
                        autoplay: false,
                        autoplayTimeout: 5000,
                        autoplayHoverPause: true,
                        dots: true,
                        navRewind: true,
                        animateIn: "fadeIn",
                        animateOut: "fadeOut",
                        loop: true,
                        nav: false,
                    });
                });
            </script>
        </div>
    </div>
</div>
<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block7')->toHtml() ?>
<div class="container">
    <div class="row home-banners">
        <div class="col-md-12">
            <div class="wpb_wrapper vc_column-inner">
                <div class="porto-grid-container">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block9')->toHtml() ?>
                    <style>
                        #banner-masonry-2 {
                            opacity: 0;
                        }
                        #banner-masonry-2 .porto-grid-item {
                            padding: 10px;
                        }
                        #banner-masonry-2 {
                            margin: -10px -10px 10px;
                        }
                        .coupon-sale-circle {
                            display: inline-flex;
                            align-items: center;
                            justify-content: center;
                            width: 96px;
                            height: 96px;
                            border-radius: 48px;
                        }
                        .coupon-sale-circle sup {
                            line-height: 1;
                            top: 0;
                            font-size: 55%;
                        }
                        .coupon-sale-circle small {
                            display: block;
                            font-size: 10px;
                            opacity: 0.5;
                            letter-spacing: -0.025em;
                        }
                        .coupon-sale-text i {
                            font-style: normal;
                            position: absolute;
                            left: -2.25em;
                            top: 50%;
                            transform: translateY(-50%) rotate(-90deg);
                            font-size: 0.65em;
                            opacity: 0.6;
                            letter-spacing: 0;
                        }
                        .coupon-sale-bg-gray b {
                            background-color: #e8e3e1;
                            color: #222529;
                        }
                        .ls-negative-20 {
                            letter-spacing: -0.02em;
                        }
                        @media (max-width: 767px) {
                            #banner-masonry-2 {
                                height: auto !important;
                            }
                            #banner-masonry-2 .porto-grid-item:first-child {
                                margin-top: 0;
                            }
                            #banner-masonry-2 .porto-grid-item {
                                width: 100% !important;
                                position: static !important;
                                float: none;
                            }
                        }
                    </style>
                    <script type="text/javascript">
                        require(["jquery", "packery"], function ($, Packery) {
                            $.bridget("packery", Packery);
                            var $container = $("#banner-masonry-2");
                            $container.css("opacity", 0);
                            if ($container.length > 0) {
                                $container.imagesLoaded(function () {
                                    $container.packery({
                                        itemSelector: ".porto-grid-item",
                                        columnWidth: ".grid-col-sizer",
                                        percentPosition: true,
                                    });
                                });
                                setTimeout(function () {
                                    $container.animate(
                                        {
                                            opacity: 1,
                                        },
                                        200
                                    );
                                }, 500);
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="background-color: #fbfbfb; padding: 50px 0;">
    <div class="container">
        <div id="featured-products" class="porto-products title-border-bottom">
            <h2 class="section-title slider-title"><span class="inline-title"><?= __('Featured Products') ?></span><span class="line"></span></h2>
            <div class="slider-wrapper">
                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="show-dots-title-right dots-style-1" product_count="8" aspect_ratio="0" image_width="350" image_height="350"
                template="owl_list.phtml"}}
                <script type="text/javascript">
                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                        $("#featured-products .owl-carousel").owlCarousel({
                            autoplay: false,
                            autoplayTimeout: 5000,
                            autoplayHoverPause: true,
                            loop: true,
                            navRewind: true,
                            lazyLoad: true,
                            margin: 0,
                            nav: false,
                            dots: true,
                            responsive: {
                                0: {
                                    items: 2,
                                },
                                640: {
                                    items: 2,
                                },
                                768: {
                                    items: 2,
                                },
                                992: {
                                    items: 3,
                                },
                                1200: {
                                    items: 4,
                                },
                            },
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
<div class="container" style="padding-top: 46px; padding-bottom: 15px;">
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block10')->toHtml() ?>
    <script type="text/javascript">
        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
            $(".brand-carousel.owl-carousel").owlCarousel({
                autoplay: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                nav: false,
                dots: false,
                loop: true,
                responsive: {
                    0: {
                        items: 2,
                    },
                    640: {
                        items: 3,
                    },
                    768: {
                        items: 4,
                    },
                    992: {
                        items: 5,
                    },
                    1200: {
                        items: 5,
                    },
                },
            });
        });
    </script>
</div>
