<style>
    .page-wrapper {
        background-color: #f4f4f4;
    }
    .cms-index-index .page-main {
        max-width: 100%;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .bg-gray {
        background: #e7e7e7;
    }
    .coupon-sale-text {
        position: relative;
        display: inline-block;
        padding-left: 0.3em;
        padding-right: 0.3em;
        transform: none;
    }
    .coupon-sale-text:before {
        content: "";
        display: block;
        background-color: #ee8379;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        transform: rotate(-2deg);
        z-index: -1;
    }
    sup {
        font-size: 52%;
    }

    .text-shadow-1 {
        font-style: italic;
        text-shadow: 0 0 4px rgb(0 0 0 / 10%);
    }
    .custom-font1 {
        font-family: Open Sans, sans-serif;
    }
    .owl-carousel.nav-style-1 .owl-nav [class*="owl-"] {
        width: 3.75rem;
        height: 3.75rem;
        border-radius: 2rem;
        background: #f4f4f4 !important;
        font-size: 1.75rem;
        color: #3250ff;
    }
    .owl-carousel.nav-style-1 .owl-nav .owl-prev {
        left: -1.875rem;
    }
    .owl-carousel.nav-style-1 .owl-nav .owl-next {
        right: -1.875rem;
    }
    .owl-carousel .owl-nav button[class*="owl-"]:hover {
        color: #3250ff;
    }
    ul.products li.product-category .thumb-info-wrapper:after {
        background: none;
    }
    ul.products li.product-category:hover .thumb-info-wrapper:after {
        background: rgba(27, 27, 23, 0.15);
    }
    ul.products li.product-category .thumb-info {
        padding: 0 1rem;
        min-height: auto;
    }
    li.product-category .thumb-info .thumb-info-wrapper {
        border-radius: 50%;
        overflow: hidden;
    }
    ul.products li.product-category .thumb-info h3 {
        font-size: 1rem;
        text-transform: none;
        letter-spacing: 0;
        line-height: 1.35;
    }
    .has-middle-content .porto-ultimate-content-box {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        position: relative;
        overflow: hidden;
    }
    .porto-ultimate-content-box > * {
        position: relative;
    }
    .text-bg {
        position: absolute;
        white-space: nowrap;
        left: 100%;
        top: 50%;
        margin-top: -0.5em;
        animation: slideX 120s infinite linear;
        pointer-events: none;
    }
    .heading-right-icon .porto-sicon-heading-right .porto-icon {
        margin-left: 0.25rem;
    }
    @media (min-width: 992px) and (max-width: 1219px) {
        .porto-ibanner-layer {
            font-size: 12px;
        }
    }
    @media (max-width: 991px) {
        .home-banner-slider .porto-ibanner-layer {
            font-size: 1.1vw;
        }
    }
    @keyframes slideX {
        0% {
            transform: translateX(0);
            left: 100%;
        }
        100% {
            transform: translateX(-100%);
            left: 0;
        }
    }
</style>
<div class="porto-wrap-container container pt-4">
    <div class="row">
        <div class="vc_column_container col-md-12">
            <div class="wpb_wrapper vc_column-inner">
                <div id="banner-slider-demo-34" class="porto-carousel owl-carousel has-ccols ccols-1 home-banner-slider mb-5 nav-style-1">
                    <div class="porto-ibanner mb-0" style="background: #ffffff;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner1.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="left: 8.3%; top: 50%; transform: translateY(-50%);">
                                <h4
                                    style="font-size: 5em; color: rgb(255, 255, 255); line-height: 0.85; font-weight: 800; letter-spacing: -0.025em;"
                                    class="vc_custom_heading custom-font1 text-shadow-1 mb-0 align-left text-uppercase heading-light"
                                >
                                    TRENDY
                                </h4>
                                <h3 style="font-size: 5.25em; line-height: 0.85; letter-spacing: -0.04em;" class="vc_custom_heading mb-0 align-left text-uppercase">
                                    gaming
                                </h3>
                                <h4 style="font-size: 4.125em; line-height: 0.85; letter-spacing: -0.04em;" class="vc_custom_heading mb-0 align-right text-uppercase">
                                    chairs
                                </h4>
                                <h4
                                    style="font-size: 5em; color: rgb(255, 255, 255); line-height: 0.85; font-weight: 800; letter-spacing: -0.025em;"
                                    class="vc_custom_heading custom-font1 text-shadow-1 mb-0 align-right text-uppercase heading-light"
                                >
                                    Deals
                                </h4>
                            </div>
                            <div class="porto-ibanner-layer" style="right: 9%; top: 50%; transform: translateY(-50%);">
                                <div>
                                    <h3 style="font-size: 1.375em; line-height: 1; letter-spacing: -0.035em; margin-bottom: 0.3636em;" class="vc_custom_heading align-left">Porto Game Chair</h3>
                                    <h4 style="font-size: 1.25em; line-height: 1; font-weight: 400; letter-spacing: -0.025em; margin-bottom: 0.8em;" class="vc_custom_heading align-left">from <del>$299.99</del></h4>
                                    <h4 style="font-size: 1.25em; line-height: 1; font-weight: 400; letter-spacing: -0.025em; padding-top: 0.3em; padding-right: 0.6em;" class="vc_custom_heading pull-left mb-0 align-left">to</h4>
                                    <h5 style="font-size: 3.25em; line-height: 1.25; letter-spacing: -0.02em; margin-bottom: 0.45em;" class="vc_custom_heading coupon-sale-text mb-4 align-left heading-light"><sup>$</sup>199<sup>99</sup></h5>
                                    <div class="btn-container mb-0 text-center">
                                        <a class="vc_btn3 vc_btn3-shape-default d-block btn btn-modern btn-md btn-dark" style="font-size: 0.875em; font-weight: 700; padding: 1.1em 0.5em;" href="#">
                                            Shop Now
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ibanner mb-0" style="background: #ffffff;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner2.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="right: 10%; top: 50%; transform: translateY(-50%);">
                                <h4 style="font-size: 5em; color: #ffffff; line-height: 0.85; font-weight: 800; letter-spacing: -0.025em;" class="vc_custom_heading custom-font1 text-shadow-1 mb-0 align-left text-uppercase heading-light">
                                    NEW
                                </h4>
                                <h3 style="font-size: 5.25em; line-height: 0.85; letter-spacing: -0.04em;" class="vc_custom_heading mb-0 align-left text-uppercase">Selected</h3>
                                <h4 style="font-size: 4.125em; line-height: 0.85; letter-spacing: -0.04em;" class="vc_custom_heading mb-0 align-right text-uppercase">Deals</h4>
                                <h4 style="font-size: 5em; color: #ffffff; line-height: 0.85; font-weight: 800; letter-spacing: -0.025em;" class="vc_custom_heading custom-font1 text-shadow-1 mb-0 align-right text-uppercase heading-light">
                                    Releases
                                </h4>
                            </div>
                            <div class="porto-ibanner-layer" style="left: 9%; top: 50%; transform: translateY(-50%);">
                                <h3 style="font-size: 1.375em; line-height: 1; letter-spacing: -0.055em; margin-bottom: 1em;" class="vc_custom_heading align-left">Best Gadtets Deals</h3>
                                <h4 style="font-size: 1.25em; line-height: 1; font-weight: 400; letter-spacing: -0.025em; padding-top: 0.3em; padding-right: 1.2em;" class="vc_custom_heading pull-left mb-0 align-left">from</h4>
                                <h5
                                    style="font-size: 3.25em; line-height: 1.25; letter-spacing: -0.02em; margin-bottom: 0.5em; padding-right: 0.5em; padding-left: 0.5em;"
                                    class="vc_custom_heading coupon-sale-text mb-4 align-left heading-light"
                                >
                                    <sup>$</sup>1<sup>99</sup>
                                </h5>
                                <div class="btn-container mb-0 text-center">
                                    <a class="vc_btn3 vc_btn3-shape-square d-block btn btn-modern btn-md btn-dark" style="font-size: 0.875em; font-weight: 700; padding: 1.1em 0.5em;" href="#" title="">
                                        Shop Now
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                        var banner_owl = $("#banner-slider-demo-34");
                        banner_owl.owlCarousel({
                            items: 1,
                            autoplay: false,
                            autoplayTimeout: 5000,
                            autoplayHoverPause: true,
                            dots: false,
                            nav: true,
                            navRewind: true,
                            animateIn: "fadeIn",
                            animateOut: "fadeOut",
                            loop: false,
                            lazyLoad: true,
                        });
                    });
                </script>
                <div class="category-slider porto-products wpb_content_element mb-4">
                    <div class="slider-wrapper">
                        <ul class="products products-container products-slider owl-carousel category-pos-outside category-text-center category-color-dark">
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat1.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Fashion</h3>
                                                <span class="thumb-info-type"><mark class="count">7</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat2.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Furniture</h3>
                                                <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat3.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Sports</h3>
                                                <span class="thumb-info-type"><mark class="count">2</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat4.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Toys</h3>
                                                <span class="thumb-info-type"><mark class="count">2</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat5.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Cameras</h3>
                                                <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat6.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Gaming</h3>
                                                <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat7.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Headphones</h3>
                                                <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="product-category product-col">
                                <a href="#">
                                    <div class="thumb-info align-center">
                                        <div class="thumb-info-wrapper tf-none">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_cat8.jpg}}" />
                                        </div>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <h3 class="sub-title thumb-info-inner">Smartphones</h3>
                                                <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <script type="text/javascript">
                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                $(".category-slider .owl-carousel").owlCarousel({
                                    autoplay: false,
                                    autoplayTimeout: 5000,
                                    autoplayHoverPause: true,
                                    loop: false,
                                    navRewind: true,
                                    lazyLoad: true,
                                    margin: 0,
                                    nav: false,
                                    dots: false,
                                    responsive: {
                                        0: {
                                            items: 2,
                                        },
                                        640: {
                                            items: 2,
                                        },
                                        768: {
                                            items: 3,
                                        },
                                        992: {
                                            items: 4,
                                        },
                                        1200: {
                                            items: 8,
                                        },
                                    },
                                });
                            });
                        </script>
                    </div>
                </div>
                <div class="porto-ultimate-content-box-container mb-4 pb-3 text-center has-middle-content">
                    <div class="porto-ultimate-content-box" style="background-color: #ffffff; padding: 20px;">
                        <h5 style="font-size: 5rem; line-height: 1; font-weight: 800; letter-spacing: -0.025em;" class="vc_custom_heading text-bg custom-font1 text-shadow-1 mb-0 align-left text-uppercase heading-light">
                            DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP DOWNLOAD OUR APP
                        </h5>
                        <h5 style="font-size: 0.8125rem; color: #777777; line-height: 1.2; text-align: center; letter-spacing: 0.025em;" class="vc_custom_heading custom-font1 mb-0">EXCLUSIVE SALES, GET IT NOW!</h5>
                        <h3 style="font-size: 2rem; line-height: 1.2; text-align: center; font-weight: 800; letter-spacing: -0.025em;" class="vc_custom_heading py-2 mb-0 mx-4 pr-2"><i>DOWNLOAD OUR APP</i></h3>
                        <div class="btn-container mb-0 d-inline-block">
                            <a class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-md btn-dark" style="font-size: 0.8125rem; font-weight: 700; letter-spacing: -0.025em; padding-left: 2.5rem; padding-right: 2.5rem;" href="#" title="">
                                GET Now!
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row vc_row-has-fill porto-inner-container" style="background: #fff;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <style>
                        .features-slider .porto-sicon-box {
                            justify-content: center;
                        }
                    </style>
                    <div class="infobox-carousel porto-carousel owl-carousel mb-0 p-t-xl p-b-md features-slider">
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3150ff; font-size: 35px;"><i class="porto-icon-shipping"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px; letter-spacing: -0.025em; color: #282d3b;">FREE SHIPPING & RETURN</h3>
                                <p style="font-weight: 300; font-size: 13px; line-height: 19px; letter-spacing: 0.01em;">Free shipping on all orders over $99.</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3150ff; font-size: 35px;"><i class="porto-icon-money"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px; letter-spacing: -0.025em; color: #282d3b;">MONEY BACK GUARANTEE</h3>
                                <p style="font-weight: 300; font-size: 13px; line-height: 19px; letter-spacing: 0.01em;">100% money back guarantee</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3150ff; font-size: 37px;"><i class="porto-icon-support"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px; letter-spacing: -0.025em; color: #282d3b;">ONLINE SUPPORT 24/7</h3>
                                <p style="font-weight: 300; font-size: 13px; line-height: 19px; letter-spacing: 0.01em;">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                        <div class="porto-sicon-box style_1 default-icon">
                            <div class="porto-sicon-default">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #3150ff; font-size: 35px;"><i class="porto-icon-secure-payment"></i></div>
                            </div>
                            <div class="porto-sicon-header">
                                <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px; letter-spacing: -0.025em; color: #282d3b;">SECURE PAYMENT</h3>
                                <p style="font-weight: 300; font-size: 13px; line-height: 19px; letter-spacing: 0.01em;">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".infobox-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 1,
                                    },
                                    640: {
                                        items: 1,
                                    },
                                    768: {
                                        items: 2,
                                    },
                                    992: {
                                        items: 2,
                                    },
                                    1200: {
                                        items: 4,
                                    },
                                },
                            });
                        });
                    </script>
                    <style>
                        .sale-text {
                            padding: 0.175em 0.3em;
                            position: relative;
                            transform: rotate(-1.5deg);
                            white-space: nowrap;
                        }
                        .sale-text i {
                            font-style: normal;
                            position: absolute;
                            left: -2.25em;
                            top: 50%;
                            transform: translateY(-50%) rotate(-90deg);
                            font-size: 0.4em;
                            opacity: 0.6;
                            letter-spacing: 0;
                        }
                        .sale-text sub {
                            position: absolute;
                            left: 100%;
                            margin-left: 0.6rem;
                            bottom: 0.3em;
                            font-size: 62%;
                            line-height: 1;
                        }
                    </style>
                    <div class="vc_row wpb_row vc_inner row mb-3">
                        <div class="vc_column_container col-md-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ibanner m-b-md" style="background: #222529; min-height: 198px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner5.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer p-r-md p-b-md text-right" style="right: 0%; bottom: 0%;">
                                            <h5
                                                style="font-size: 1.625rem; line-height: 0.9; letter-spacing: 0.01em; margin-right: 1.6em;"
                                                class="vc_custom_heading d-inline-block custom-font1 sale-text mb-5 background-color-secondary align-left heading-light"
                                            >
                                                <i>UP TO</i>50%<sub>OFF</sub>
                                            </h5>
                                            <h4 style="font-size: 0.875rem; color: rgba(255, 255, 255, 0.4); line-height: 1; letter-spacing: 0.025em;" class="vc_custom_heading mb-1 custom-font1 align-right text-uppercase">
                                                flash sales on
                                            </h4>
                                            <h3 style="font-size: 1.875rem; line-height: 1; letter-spacing: 0.01em;" class="vc_custom_heading mb-0 align-left heading-light">NICE SHOES</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="vc_column_container col-md-8">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="porto-ibanner m-b-md" style="background: #eeeeee; min-height: 198px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner4.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer" style="right: 10.5%; top: 50%; transform: translateY(-50%);">
                                            <h3 style="font-size: 2.25em; line-height: 1.2; letter-spacing: 0.01em;" class="vc_custom_heading mb-0 align-right">
                                                TOP ELECTRONIC<br />
                                                FOR GIFTS
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-sicon-box mb-3 space-sm style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 34px; margin-right: 0.25rem;"><i class="porto-icon-percent-shape"></i></div>
                        </div>
                        <div class="porto-sicon-header"><h2 class="porto-sicon-title" style="font-weight: 600; font-size: 1.375rem; line-height: 1;">Special Offers</h2></div>
                    </div>
                    <style>
                        .top-sale-product {
                            border: 2px solid #0e39ff;
                            height: 100%;
                        }
                        .top-sale-product .product-item-info:hover .product-item-photo {
                            box-shadow: none;
                        }
                        .top-sale-product .product-item .weltpixel-quickview.weltpixel_quickview_button_v2 {
                            display: none;
                        }
                        .top-sale-product .product-item-info .product-item-details .product-item-actions .tocart {
                            padding-left: 45px;
                            height: 56px;
                            line-height: 56px;
                            padding-right: 45px;
                            font-size: 14px;
                            border-radius: 7px;
                        }
                        .top-sale-product .product-item-actions .actions-secondary.action {
                            height: 56px;
                            line-height: 56px;
                        }
                        .top-sale-product .product-item-info.type1 .product-item-inner {
                            margin-top: 46px;
                        }
                        .top-sale-product .add_to_cart_button {
                            padding-left: 45px;
                            height: 56px;
                            line-height: 56px;
                            padding-right: 45px;
                            font-size: 14px;
                            border-radius: 7px;
                        }
                        .top-sale-product .product-item .tocart::before {
                            font-size: 24px !important;
                            font-weight: 300 !important;
                        }
                        .border-gray {
                            border-style: solid;
                            border-width: 2px;
                            border-color: rgba(0, 0, 0, 0.09);
                        }
                        @media (min-width: 768px) {
                            .border-gray {
                                margin-left: -22px;
                            }
                        }
                    </style>
                    <div class="pt_row wpb_row pt_inner row pt_row-o-equal-height pt_row-flex" style="margin-bottom: 45px;">
                        <div class="pt_column_container col-md-4">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-products wpb_content_element top-sale-product mb-0 countdown-style-1">
                                    {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" product_type="1" product_count="1" column_count="1" aspect_ratio="0" image_width="450" image_height="450"
                                    template="grid.phtml"}}
                                </div>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-8">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-products wpb_content_element mb-0 border-gray h-100">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_type="6" product_count="8" column_count="4" aspect_ratio="0" image_width="350" image_height="350"
                                    template="grid.phtml"}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt_row wpb_row p-t-xl porto-inner-container">
    <style>
        .porto-ibanner.h-100 > img {
            height: 100%;
        }
        .porto-products.filter-vertical {
            display: flex;
            flex-wrap: wrap;
        }
        .porto-products.filter-vertical .section-title {
            font-size: 1.375rem;
            font-weight: 600;
            text-transform: none;
            flex: 0 0 100%;
            color: #313131;
        }
        .porto-products .product-categories {
            list-style: none;
            padding-left: 0;
            margin-bottom: 1rem;
        }
        .porto-products.filter-vertical .product-categories a {
            display: block;
            position: relative;
            color: #777;
            font-size: 0.8125rem;
        }
        .porto-products .product-categories a {
            padding: 0.25rem 0 !important;
        }
        .porto-products.filter-vertical .products-filter + div {
            padding: 0;
        }
        .products-grid:not(.small-list) .product-item .product-item-info {
            background: #fff;
        }
        @media (max-width: 767px) {
            .porto-products.filter-vertical .product-categories li {
                display: inline-block;
                margin-right: 20px;
            }
        }
        @media (min-width: 768px) {
            .porto-products.filter-vertical .products-filter {
                padding: 1rem 1rem 3rem;
                background: #fff;
                flex: 0 0 16.6666%;
            }
            .porto-products.filter-vertical .products-filter + div {
                max-width: 83.3333%;
                -webkit-flex: 0 0 83.3333%;
                flex: 0 0 83.3333%;
                padding-left: 15px;
                padding-right: 15px;
            }
            .porto-products.filter-vertical + .porto-sicon-box-link {
                position: absolute;
                bottom: 0.75rem;
                left: 1rem;
            }
        }
        @media (min-width: 992px) {
            .porto-products.filter-vertical .products-filter {
                padding: 2rem 2rem 3rem;
                max-width: 25%;
                flex-basis: 25%;
                border: none;
            }
            .porto-products.filter-vertical .products-filter + div {
                max-width: calc(50% + 10px);
                flex-basis: calc(50% + 10px);
                margin-left: auto;
                padding: 0;
                overflow: hidden;
            }
            .pc-home-category-banner {
                position: absolute !important;
                left: 25%;
                width: calc(25% - 10px);
                top: 0;
                bottom: 0;
            }
            .porto-products.filter-vertical + .porto-sicon-box-link {
                left: 2rem;
            }
        }
        @media (min-width: 992px) and (max-width: 1219px) {
            .porto-products .product-categories a {
                padding: 1px 0 !important;
            }
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="pt_column_container col-md-12">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="pt_row wpb_row pt_inner row position-relative no-padding mx-0 mb-5 pt_row-o-equal-height pt_row-flex">
                        <div class="pc-home-category-banner mb-4 mb-md-0 pt_column_container col-md-6 col-lg-3">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-ibanner h-100 mb-0" style="background: #efeeec;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner3.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer text-right" style="left: 50%; transform: translateX(-50%); top: 6.5%;">
                                            <h5 style="font-size: 0.875em; color: #999999; line-height: 1; font-weight: 400; letter-spacing: 0.05em;" class="vc_custom_heading mb-1 align-left"><i>Find the Boundaries. Push Through!</i></h5>
                                            <h3 style="font-size: 2.5em; line-height: 1; letter-spacing: 0.165em;" class="vc_custom_heading mb-0 text-nowrap align-left text-uppercase">mega sale</h3>
                                            <h4 style="font-size: 4.1875em; line-height: 1;" class="vc_custom_heading mb-1 text-nowrap align-left">70% OFF</h4>
                                            <h5 style="font-size: 0.75em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading d-inline-block align-middle mr-3 align-left text-uppercase">STARTING AT</h5>
                                            <h5 style="font-size: 1.6em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading sale-text d-inline-block background-color-primary mr-2 align-left heading-light">
                                                <sup>$</sup>199<sup>99</sup>
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-12">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-products wpb_content_element show-category filter-vertical mb-3 mb-md-0">
                                    <div class="products-filter">
                                        <h4 class="section-title">Sort By</h4>
                                        <ul class="product-categories">
                                            <li><a href="#">Kids Fashion</a></li>
                                            <li><a href="#">Casual Shoes</a></li>
                                            <li><a href="#">Spring & Autumn</a></li>
                                            <li><a href="#">Man</a></li>
                                            <li><a href="#">Accessories</a></li>
                                            <li><a href="#">Pants & Denim</a></li>
                                            <li><a href="#">Tees, Knits & Polos</a></li>
                                            <li><a href="#">Watch Fashion</a></li>
                                            <li><a href="#">Woman</a></li>
                                            <li><a href="#">Accessories</a></li>
                                            <li><a href="#">Dresses & Skirts</a></li>
                                            <li><a href="#">Shoes & Boots</a></li>
                                            <li><a href="#">Top & Blouses</a></li>
                                        </ul>
                                    </div>
                                    <div class="porto-products">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_type="6" product_count="6" column_count="3" aspect_ratio="0" image_width="350" image_height="300"
                                        template="grid.phtml"}}
                                    </div>
                                </div>
                                <a class="porto-sicon-box-link" href="#">
                                    <div class="porto-sicon-box d-inline-block mb-0 mb-md-4 style_1 heading-right-icon">
                                        <div class="porto-sicon-header"><h6 class="porto-sicon-title" style="font-weight: 600; font-size: 0.75rem; line-height: 1; letter-spacing: -0.02em; color: #0e39ff;">View All</h6></div>
                                        <div class="porto-sicon-heading-right">
                                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #0e39ff; font-size: 12px;"><i class="fas fa-long-arrow-alt-right"></i></div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row m-b-xl no-padding porto-inner-container">
    <style>
        .vc_row.no-padding > .container > .row {
            margin-left: 0;
            margin-right: 0;
        }

        .cat-list .thumb-info-title > a,
        .cat-grid .thumb-info-title > a {
            order: -1;
            font-size: 0.8125rem;
            text-transform: uppercase;
            letter-spacing: -0.01em;
            margin-bottom: 0.5rem;
        }
        .cat-list .product-category .sub-categories,
        .cat-grid .product-category .sub-categories {
            font-size: 0.8125rem;
            display: flex;
            flex-wrap: wrap;
            margin: 0;
        }
        .cat-list .thumb-info {
            display: flex;
            flex-direction: column;
            padding: 0 !important;
        }
        .cat-list .sub-categories li {
            padding: 0.25rem 0.25rem 0.25rem 0;
            width: 100%;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .subcats-cols-2 .sub-categories li {
            width: 50%;
        }
        ul.products.category-pos-outside li.product-category .thumb-info-title {
            padding: 0.75rem 0 0;
        }
        .subcats-cols-2 .thumb-info > a,
        .cat-grid .thumb-info > a {
            font-size: 0.75rem;
            font-weight: 600;
            letter-spacing: -0.02em;
            order: 2;
            white-space: nowrap;
        }
        .subcats-cols-2 .thumb-info > a:before,
        .cat-grid .thumb-info > a:before {
            content: "View All";
            margin-right: 2px;
        }
        .subcats-cols-2 .thumb-info > a:after,
        .cat-grid .thumb-info > a:after {
            content: "\f30b";
            font-family: "Font Awesome 5 Free";
            font-weight: 900;
        }
        .cat-list .thumb-info-title {
            display: flex !important;
            flex-direction: column;
            text-align: left !important;
            letter-spacing: 0;
        }
        ul.products,
        .products-slider.products {
            margin-bottom: -1px !important;
        }
        .products-slider.owl-carousel .owl-stage-outer {
            margin-top: 0;
            padding-top: 1px;
        }
        .custom-padding .products-slider.owl-carousel .product-item {
            padding-left: 0.5px;
            padding-right: 0.5px;
            margin-bottom: 1px;
        }
        .custom-padding .product-item-details {
            padding: 15px 15px 1px;
        }
        .custom-padding .product-item-info.type3 .product-item-actions .towishlist {
            right: 15px;
            bottom: -62px;
        }
        @media (max-width: 575px) {
            .p-t-xl {
                padding-top: 20px !important;
            }
            .p-r-xl {
                padding-right: 20px !important;
            }
            .p-l-xl {
                padding-left: 20px !important;
            }
            .m-r-n-xl {
                margin-right: -20px !important;
            }
            .m-l-n-xl {
                margin-left: -20px !important;
            }
        }
        @media (min-width: 1220px) {
            .w-mc {
                width: min-content;
            }
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="p-t-xl p-l-xl p-r-xl vc_column_container background-color-light col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 1.375rem; line-height: 1; font-weight: 600; letter-spacing: 0;" class="vc_custom_heading mb-3 align-left">Electronics</h2>
                    <div class="vc_row wpb_row vc_inner row">
                        <div class="vc_column_container col-md-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div id="interactive-banner-wrap-7219" class="porto-ibanner m-b-md" style="background: #efeeec; min-height: 150px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner6.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer d-flex flex-wrap flex-xl-nowrap align-items-center" style="width: 60%; left: 37%; top: 50%; transform: translateY(-50%);">
                                            <div class="wpb_raw_code wpb_content_element wpb_raw_html custom-font1 mb-0 mr-3 mr-xl-4">
                                                <div class="wpb_wrapper">
                                                    <div style="font-size: 1.125em; line-height: 1.2; font-weight: 700; padding: 0.5em;" class="mb-2 sale-text background-color-dark text-light">Exclusive COUPON</div>
                                                    <div style="font-size: 1.6em; line-height: 1; font-weight: 700;" class="mb-0 sale-text background-color-dark text-color-dark d-inline-block">
                                                        <i>UP TO</i><b class="text-color-light">$100</b><sub>OFF</sub>
                                                    </div>
                                                </div>
                                            </div>
                                            <h4 style="font-size: 2em; line-height: 1.2;" class="vc_custom_heading mb-0 w-mc text-xl-right align-left">DRONE & CAMERAS</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="vc_column_container col-md-6">
                            <div class="wpb_wrapper vc_column-inner">
                                <div id="interactive-banner-wrap-6621" class="porto-ibanner m-b-md" style="background: #222529; min-height: 150px;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner7.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer d-flex flex-wrap flex-xl-nowrap align-items-center" style="width: 60%; left: 37%; top: 50%; transform: translateY(-50%);">
                                            <h4 style="font-size: 1.9em; line-height: 1.1;" class="vc_custom_heading my-1 w-mc mr-4 text-xl-center align-left heading-light">ELECTRONIC DEALS</h4>
                                            <div class="wpb_raw_code wpb_content_element wpb_raw_html custom-font1 mb-0">
                                                <div class="wpb_wrapper">
                                                    <div style="font-size: 0.94em; line-height: 1.2; font-weight: 700; padding: 0.5em;" class="mb-2 sale-text background-color-light text-color-dark">Exclusive COUPON</div>
                                                    <div style="font-size: 1.5em; line-height: 1; font-weight: 700;" class="mb-0 sale-text background-color-secondary text-light d-inline-block"><i>UP TO</i><b>$100</b><sub>OFF</sub></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-products wpb_content_element cat-list subcats-cols-2 mb-4 hide-count">
                        <div class="columns-4">
                            <ul class="row products products-container grid category-pos-outside category-text-left category-color-dark show-nav-middle is-shortcode" style="margin-left: -10px; margin-right: -10px;">
                                <li class="product-category product-col col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-50"><a href="#">Bags & Cases</a></li>
                                                    <li class="cat-item cat-item-47"><a href="#">Batteries</a></li>
                                                    <li class="cat-item cat-item-45"><a href="#">Cables & Adapters</a></li>
                                                    <li class="cat-item cat-item-48"><a href="#">Chargers</a></li>
                                                    <li class="cat-item cat-item-46"><a href="#">Electronic Cigarettes</a></li>
                                                    <li class="cat-item cat-item-49"><a href="#">Home Electronic</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Accessories</h3></a>
                                                <span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-55"><a href="#">Audio Amplifier</a></li>
                                                    <li class="cat-item cat-item-54"><a href="#">HDMI Projectors</a></li>
                                                    <li class="cat-item cat-item-53"><a href="#">Projectors</a></li>
                                                    <li class="cat-item cat-item-51"><a href="#">Televisions</a></li>
                                                    <li class="cat-item cat-item-52"><a href="#">TV Receivers</a></li>
                                                    <li class="cat-item cat-item-56"><a href="#">TV Sticks</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Audio & Video</h3></a>
                                                <span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-60"><a href="#">Action Cameras</a></li>
                                                    <li class="cat-item cat-item-58"><a href="#">Camcorders</a></li>
                                                    <li class="cat-item cat-item-62"><a href="#">Camera & Photo</a></li>
                                                    <li class="cat-item cat-item-59"><a href="#">Camera Drones</a></li>
                                                    <li class="cat-item cat-item-57"><a href="#">Digital Cameras</a></li>
                                                    <li class="cat-item cat-item-61"><a href="#">Photo Supplies</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Camera & Photo</h3></a>
                                                <span class="thumb-info-type"><mark class="count">2</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-63"><a href="#">Gaming Laptops</a></li>
                                                    <li class="cat-item cat-item-66"><a href="#">Laptop Accessories</a></li>
                                                    <li class="cat-item cat-item-68"><a href="#">Laptop Bags & Cases</a></li>
                                                    <li class="cat-item cat-item-67"><a href="#">Tablet Accessories</a></li>
                                                    <li class="cat-item cat-item-65"><a href="#">Tablets</a></li>
                                                    <li class="cat-item cat-item-64"><a href="#">Ultraslim Laptops</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Laptops</h3></a>
                                                <span class="thumb-info-type"><mark class="count">2</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div id="category1-products" class="custom-padding porto-products wpb_content_element m-l-n-xl m-r-n-xl bg-gray mb-0">
                        <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="show-dots-title-right dots-style-1" product_type="3" product_count="8" aspect_ratio="0" image_width="350"
                            image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#category1-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 6,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row m-b-xl no-padding porto-inner-container">
    <style>
        .cat-medium .thumb-info {
            flex-direction: row;
            align-items: center;
        }
        .cat-medium .thumb-info > a {
            flex: 0 0 36%;
            max-width: 36%;
            margin-right: 4%;
            text-align: center;
        }
        .cat-medium .thumb-info i {
            display: block;
            font-size: 3.5rem;
            color: #ccc;
        }
        .cat-medium .thumb-info > a {
            flex: 0 0 36%;
            max-width: 36%;
            margin-right: 4%;
            text-align: center;
        }
        .cat-medium .thumb-info-wrap {
            flex: 0 0 60%;
            max-width: 60%;
        }
        .porto-ibanner-layer {
            position: absolute;
            z-index: 10;
        }
        .big-number {
            top: 0.0125em;
            letter-spacing: -0.025em;
        }
        .big-number small {
            font-size: 0.1413em !important;
            font-weight: inherit;
            letter-spacing: 0;
            line-height: 1;
            position: absolute;
            top: 50%;
            right: 1.62em;
            text-align: center;
            transform: translateY(-54%);
        }
        .big-number ins {
            display: block;
            text-decoration: none;
            font-size: 50%;
            text-transform: uppercase;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="background-color-light p-t-xl p-l-xl p-r-xl vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 1.375rem; line-height: 1; font-weight: 600; letter-spacing: 0;" class="vc_custom_heading mb-4 align-left">Gift & Gadgets</h2>
                    <div id="porto-product-categories-8562" class="porto-products wpb_content_element cat-list cat-medium mb-3 hide-count">
                        <div class="columns-4">
                            <ul class="row no-adding products products-container grid category-pos-outside category-text-center category-color-dark">
                                <li class="product-category product-col cat-has-icon col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"><i class="porto-icon-boy-broad-smile"></i></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-74"><a href="E">Gifts for Boyfriend</a></li>
                                                    <li class="cat-item cat-item-76"><a href="#">Gifts for Dad</a></li>
                                                    <li class="cat-item cat-item-75"><a href="#">Gifts for Husband</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">For Him</h3></a>
                                                <span class="thumb-info-type"><mark class="count">3</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col cat-has-icon col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"><i class="porto-icon-smiling-girl"></i></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-77"><a href="#">Gifts for Girlfriend</a></li>
                                                    <li class="cat-item cat-item-79"><a href="#">Gifts for Mom</a></li>
                                                    <li class="cat-item cat-item-78"><a href="#">Gifts for Wife</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">For Her</h3></a>
                                                <span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col cat-has-icon col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"><i class="porto-icon-smiling-baby"></i></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-80"><a href="#">Gifts for Boys</a></li>
                                                    <li class="cat-item cat-item-81"><a href="#">Gifts for Girls</a></li>
                                                    <li class="cat-item cat-item-82"><a href="#">Gifts for Tween Boys</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">For Kids</h3></a>
                                                <span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="product-category product-col cat-has-icon col-lg-3 col-md-4 col-sm-12">
                                    <div class="thumb-info align-center">
                                        <a href="#"><i class="porto-icon-gift-2"></i></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-84"><a href="#">Birthday for Her</a></li>
                                                    <li class="cat-item cat-item-83"><a href="#">Birthday for Him</a></li>
                                                    <li class="cat-item cat-item-85"><a href="#">Boyfriend Gifts</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Birthday</h3></a>
                                                <span class="thumb-info-type"><mark class="count">5</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div id="category2-products" class="custom-padding porto-products wpb_content_element m-l-n-xl m-r-n-xl bg-gray mb-0">
                        <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="show-dots-title-right dots-style-1" product_type="3" product_count="8" aspect_ratio="0" image_width="350"
                            image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#category2-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 6,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="porto-ibanner mb-0 m-l-n-xl m-r-n-xl home-percent-banner" style="background: #ffaa89; min-height: 167px;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner8.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer d-flex align-items-center flex-wrap" style="width: 86%; left: 7%; top: 50%; transform: translateY(-50%);">
                                <div class="porto-u-heading mr-3 my-2" data-hspacer="no_spacer" data-halign="left" style="text-align: left;">
                                    <div class="porto-u-main-heading">
                                        <h4 style="font-weight: 300; color: #ffffff; margin-bottom: 4px; font-size: 1.25em; line-height: 1.1; letter-spacing: 0.17em;">THE PERFECT GIFT FOR YOUR GIRLFRIEND</h4>
                                    </div>
                                    <div class="porto-u-sub-heading" style="font-weight: 700; color: #ffffff; font-size: 2.5625em; line-height: 1;">GIFT SELECTION ON SALE</div>
                                </div>
                                <h5 style="font-size: 12em; line-height: 0.8; margin-right: 0.16em;" class="vc_custom_heading mb-0 position-relative big-number align-left heading-light">
                                    50<small>%<ins>OFF</ins></small>
                                </h5>
                                <div class="btn-container d-inline-block">
                                    <a class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-md btn-light" style="font-size: 0.85em; font-weight: 700; padding: 1em 3em;" href="#" title="">
                                        SHOP NOW!
                                    </a>
                                </div>
                            </div>
                        </div>
                        <style>
                            @media (max-width: 991px) {
                                .home-percent-banner .porto-ibanner-layer {
                                    font-size: 9px;
                                }
                            }
                            @media (max-width: 575px) {
                                .home-percent-banner .porto-ibanner-layer {
                                    font-size: 7px;
                                }
                            }
                        </style>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row m-b-xl no-padding porto-inner-container">
    <style>
        .cat-grid .thumb-info {
            padding: 0 !important;
            display: flex;
            padding: 0 !important;
        }
        .cat-grid .sub-categories li {
            padding: 0;
            margin: 0 2rem 0.5rem 0;
        }
        .cat-grid .thumb-info > a {
            margin-left: 0.5rem;
            padding-top: 0.9rem;
        }
        .cat-grid .thumb-info-title {
            display: flex !important;
            letter-spacing: 0;
            flex-wrap: wrap;
            align-items: center;
            text-align: left !important;
        }
        .cat-grid .thumb-info-title {
            display: flex !important;
            letter-spacing: 0;
            flex-wrap: wrap;
            align-items: center;
            text-align: left !important;
        }
        .cat-grid .thumb-info-title .sub-title {
            margin-right: 3rem !important;
            font-size: 1.375rem !important;
            font-weight: 600 !important;
        }
        .cat-grid ul.products li.product-category {
            margin-bottom: 1.4286em;
            position: relative;
            flex: 0 0 100%;
            width: 100%;
            padding: 0;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="background-color-light p-t-lg p-l-xl p-r-xl vc_column_container col-md-12 col-lg-9">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-products wpb_content_element cat-grid mb-0 hide-count">
                        <div class="columns-1">
                            <ul class="products products-container grid category-pos-outside category-text-center category-color-dark show-nav-middle">
                                <li class="product-category product-col">
                                    <div class="thumb-info align-center">
                                        <a href="#"></a>
                                        <div class="thumb-info-wrap">
                                            <div class="thumb-info-title">
                                                <ul class="sub-categories">
                                                    <li class="cat-item cat-item-87"><a href="#">Furniture</a></li>
                                                    <li class="cat-item cat-item-90"><a href="#">Garden & Outdoors</a></li>
                                                    <li class="cat-item cat-item-89"><a href="#">Home Accessories</a></li>
                                                    <li class="cat-item cat-item-88"><a href="#">Lighting</a></li>
                                                </ul>
                                                <a href="#"><h3 class="sub-title thumb-info-inner">Home & Garden</h3></a>
                                                <span class="thumb-info-type"><mark class="count">4</mark> Products </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="porto-ibanner home-percent-banner" style="background: #f4ece4;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_home_banner9.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="left: 4%; top: 50%; transform: translateY(-50%);">
                                <div class="vc_custom_heading mb-1 heading heading-border heading-middle-border heading-middle-border-center heading-border-xs heading1814034712">
                                    <h5 style="font-size: 0.85em; line-height: 1; text-align: center; font-weight: 600; letter-spacing: 0.2em;" class="heading-tag text-uppercase">Amazing</h5>
                                </div>
                                <h3 style="font-size: 1.875em; line-height: 1.1; text-align: center; font-weight: 800;" class="vc_custom_heading px-3 mb-2 text-uppercase">Collection</h3>
                                <div class="porto-separator mb-2 pb-1"><hr class="separator-line align_center solid" style="background-color: #dfddda;" /></div>
                                <h5 style="font-size: 0.85em; color: rgba(34, 37, 41, 0.7); line-height: 1; text-align: center; font-weight: 600; letter-spacing: 0.2em;" class="vc_custom_heading mb-0 text-uppercase">Check our discounts</h5>
                            </div>
                            <div class="porto-ibanner-layer" style="right: 5%; top: 50%; transform: translateY(-50%);">
                                <h3 style="font-size: 1.6875em; line-height: 1; text-align: center; letter-spacing: -0.02em;" class="vc_custom_heading mb-2 text-uppercase">STARTING AT <sup>$</sup>199<sup>99</sup></h3>
                                <h6 style="font-size: 0.7em; color: #777777; line-height: 1; text-align: center; font-weight: 600; letter-spacing: 0.18em;" class="vc_custom_heading mb-0 text-uppercase">* limited time only</h6>
                            </div>
                        </div>
                    </div>
                    <style>
                        .product.data.items > .item.title {
                            color: #777;
                            font-weight: 400;
                            text-transform: none;
                            font-size: 0.8125rem;
                        }
                        .product.data.items > .item.title > .switch {
                            font-size: inherit;
                        }
                        .product.data.items > .item.title.active {
                            color: #0e39ff;
                            font-weight: 600;
                        }
                        .product.data.items > .item.content {
                            background: #e7e7e7;
                        }
                        @media (max-width: 767px) {
                            .product.data.items > .item.title {
                                padding-left: 10px;
                                padding-right: 10px;
                            }
                            .product.data.items > .item.content {
                                padding-top: 0;
                                padding-bottom: 0;
                            }
                        }
                        @media (min-width: 768px) {
                            .product.data.items > .item.title:first-child {
                                margin-left: 40px;
                            }
                            .product.data.items > .item.title {
                                margin: 0 2rem 0 0;
                                padding: 0.25rem 0;
                                border-bottom-width: 0;
                            }
                            .product.data.items > .item.title.active {
                                border: none;
                            }
                            .product.data.items > .item.content {
                                border-top: none;
                                margin-top: 47px;
                                padding: 0;
                            }
                        }
                    </style>
                    <div class="tabs tabs-simple m-l-n-xl m-r-n-xl">
                        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                            <div class="data item title" aria-labeledby="tab-label-tab1-title" data-role="collapsible" id="tab-label-tab1">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab1" id="tab-label-tab1-title">
                                    <span>Best Sellers</span>
                                </a>
                            </div>
                            <div class="data item content bg-gray custom-padding" id="tab1" data-role="content">
                                <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="show-dots-title-right dots-style-1" product_type="3" product_count="8" aspect_ratio="0" image_width="350"
                                    image_height="350" template="owl_list.phtml"}}
                                    <script type="text/javascript">
                                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                            $("#tab1 .owl-carousel").owlCarousel({
                                                autoplay: false,
                                                autoplayTimeout: 5000,
                                                autoplayHoverPause: true,
                                                loop: false,
                                                navRewind: true,
                                                lazyLoad: true,
                                                margin: 0,
                                                nav: false,
                                                dots: false,
                                                responsive: {
                                                    0: {
                                                        items: 2,
                                                    },
                                                    640: {
                                                        items: 2,
                                                    },
                                                    768: {
                                                        items: 2,
                                                    },
                                                    992: {
                                                        items: 3,
                                                    },
                                                    1200: {
                                                        items: 4,
                                                    },
                                                },
                                            });
                                        });
                                    </script>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab2-title" data-role="collapsible" id="tab-label-tab2">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2" id="tab-label-tab2-title">
                                    <span>New Arrivals</span>
                                </a>
                            </div>
                            <div class="data item content bg-gray custom-padding" id="tab2" data-role="content">
                                <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="show-dots-title-right dots-style-1" product_type="3" product_count="8" aspect_ratio="0" image_width="350"
                                    image_height="350" template="owl_list.phtml"}}
                                    <script type="text/javascript">
                                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                            $("#tab2 .owl-carousel").owlCarousel({
                                                autoplay: false,
                                                autoplayTimeout: 5000,
                                                autoplayHoverPause: true,
                                                loop: false,
                                                navRewind: true,
                                                lazyLoad: true,
                                                margin: 0,
                                                nav: false,
                                                dots: false,
                                                responsive: {
                                                    0: {
                                                        items: 2,
                                                    },
                                                    640: {
                                                        items: 2,
                                                    },
                                                    768: {
                                                        items: 2,
                                                    },
                                                    992: {
                                                        items: 3,
                                                    },
                                                    1200: {
                                                        items: 4,
                                                    },
                                                },
                                            });
                                        });
                                    </script>
                                </div>
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-tab3-title" data-role="collapsible" id="tab-label-tab3">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab3" id="tab-label-tab3-title">
                                    <span>Best Ratings </span>
                                </a>
                            </div>
                            <div class="data item content bg-gray custom-padding" id="tab3" data-role="content">
                                <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="show-dots-title-right dots-style-1" product_type="3" product_count="8" aspect_ratio="0" image_width="350"
                                    image_height="350" template="owl_list.phtml"}}
                                    <script type="text/javascript">
                                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                            $("#tab3 .owl-carousel").owlCarousel({
                                                autoplay: false,
                                                autoplayTimeout: 5000,
                                                autoplayHoverPause: true,
                                                loop: false,
                                                navRewind: true,
                                                lazyLoad: true,
                                                margin: 0,
                                                nav: false,
                                                dots: false,
                                                responsive: {
                                                    0: {
                                                        items: 2,
                                                    },
                                                    640: {
                                                        items: 2,
                                                    },
                                                    768: {
                                                        items: 2,
                                                    },
                                                    992: {
                                                        items: 3,
                                                    },
                                                    1200: {
                                                        items: 4,
                                                    },
                                                },
                                            });
                                        });
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="background-color-light p-t-xl px-4 vc_column_container col-md-12 col-lg-3" style="border-left: 1px solid #eeeeee; border-radius: 1px;">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-sicon-box mb-4 space-sm style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 30px;"><i class="porto-icon-percent-shape"></i></div>
                        </div>
                        <div class="porto-sicon-header"><h2 class="porto-sicon-title" style="font-weight: 600; font-size: 1.125rem; line-height: 1; letter-spacing: -0.025em;">Special Offers</h2></div>
                    </div>
                    <div class="wpb_content_element">
                        <div class="widget widget_products">
                            {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" product_count="6" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                    <a class="porto-sicon-box-link" href="#">
                        <div class="porto-sicon-box d-inline-block mb-4 mt-3 ml-2 style_1 heading-right-icon">
                            <div class="porto-sicon-header"><h6 class="porto-sicon-title" style="font-weight: 600; font-size: 0.75rem; line-height: 1; letter-spacing: -0.02em; color: #0e39ff;">View All</h6></div>
                            <div class="porto-sicon-heading-right">
                                <div class="porto-just-icon-wrapper porto-icon none" style="color: #0e39ff; font-size: 12px;"><i class="fas fa-long-arrow-alt-right"></i></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <h2 style="font-size: 1.375rem; line-height: 1; font-weight: 600;" class="vc_custom_heading mb-4 align-left">Featured Brands</h2>
                    <div class="porto-carousel brand-carousel owl-carousel bg-gray m-b-xl nav-style-1">
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand1.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand2.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand3.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand4.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand5.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand6.png}}" alt="" /></div>
                        <div class="item background-color-light" style="padding-top: 3.5rem; padding-bottom: 3.5rem;"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand1.png}}" alt="" /></div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".brand-carousel.owl-carousel").owlCarousel({
                                autoplay: true,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                nav: true,
                                dots: false,
                                loop: false,
                                margin: 1,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 2,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 6,
                                    },
                                },
                            });
                        });
                    </script>
                    <div class="porto-products wpb_content_element show-category filter-horizontal bg-content-gray selected-products m-b-xl" style="clear: both;">
                        <style>
                            .selected-products .product.data.items > .item.title:first-child {
                                margin-left: 0;
                            }
                            .selected-products .product.data.items > .item.title:first-child > * {
                                display: inline-block;
                                vertical-align: middle;
                            }
                            .selected-products .product.data.items > .item.title:first-child:before {
                                content: "Selected Products";
                                font-size: 1.375rem;
                                font-weight: 600;
                                margin-right: 2rem;
                                color: #222529;
                                vertical-align: middle;
                            }
                            @media (max-width: 767px) {
                                .selected-products .product.data.items > .item.title:first-child > * {
                                    display: block;
                                }
                                .selected-products .product.data.items > .item.title:first-child:before {
                                    margin-bottom: 15px;
                                    display: block;
                                }
                            }
                        </style>
                        <div class="tabs tabs-simple">
                            <a class="porto-sicon-box-link" href="#" title="Shop" style="position: absolute; right: 10px; z-index: 3;">
                                <div class="porto-sicon-box mb-2 style_1 heading-right-icon" style="margin-top: 5px;">
                                    <div class="porto-sicon-header"><h6 class="porto-sicon-title" style="font-weight: 600; font-size: 0.75rem; line-height: 1; letter-spacing: -0.02em; color: #0e39ff;">View All</h6></div>
                                    <div class="porto-sicon-heading-right">
                                        <div class="porto-just-icon-wrapper porto-icon none" style="color: #0e39ff; font-size: 12px;"><i class="fas fa-long-arrow-alt-right"></i></div>
                                    </div>
                                </div>
                            </a>
                            <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                                <div class="data item title" aria-labeledby="tab-label-tab2_1-title" data-role="collapsible" id="tab-label-tab2_1">
                                    <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2_1" id="tab-label-tab2_1-title">
                                        <span>Best Sellers</span>
                                    </a>
                                </div>
                                <div class="data item content bg-gray custom-padding" id="tab2_1" data-role="content">
                                    <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="nav-center-images-only nav-style-1 dots-style-1" product_type="3" product_count="8" aspect_ratio="0"
                                        image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab2_1 .owl-carousel").owlCarousel({
                                                    autoplay: false,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: false,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 4,
                                                        },
                                                        1200: {
                                                            items: 6,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                                <div class="data item title" aria-labeledby="tab-label-tab2_2-title" data-role="collapsible" id="tab-label-tab2_2">
                                    <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2_2" id="tab-label-tab2_2-title">
                                        <span>New Arrivals</span>
                                    </a>
                                </div>
                                <div class="data item content bg-gray custom-padding" id="tab2_2" data-role="content">
                                    <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="nav-center-images-only nav-style-1 dots-style-1" product_type="3" product_count="8" aspect_ratio="0"
                                        image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab2_2 .owl-carousel").owlCarousel({
                                                    autoplay: false,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: false,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 4,
                                                        },
                                                        1200: {
                                                            items: 6,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                                <div class="data item title" aria-labeledby="tab-label-tab2_3-title" data-role="collapsible" id="tab-label-tab2_3">
                                    <a class="data switch" tabindex="-1" data-toggle="switch" href="#tab2_3" id="tab-label-tab2_3-title">
                                        <span>Best Ratings </span>
                                    </a>
                                </div>
                                <div class="data item content bg-gray custom-padding" id="tab2_3" data-role="content">
                                    <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="nav-center-images-only nav-style-1 dots-style-1" product_type="3" product_count="8" aspect_ratio="0"
                                        image_width="350" image_height="350" template="owl_list.phtml"}}
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $("#tab2_3 .owl-carousel").owlCarousel({
                                                    autoplay: false,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: false,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: true,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 2,
                                                        },
                                                        992: {
                                                            items: 4,
                                                        },
                                                        1200: {
                                                            items: 6,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ultimate-content-box-container text-center m-b-xl">
                        <div class="porto-ultimate-content-box d-flex align-items-center justify-content-center flex-wrap" style="background-color: #222529; padding: 4rem 1rem;">
                            <div class="wpb_single_image wpb_content_element vc_align_left mb-0 d-inline-block align-middle">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                        <img class="d-block" src="{{media url=wysiwyg/smartwave/porto/homepage/34/shop34_logo2.png}}" />
                                    </div>
                                </div>
                            </div>
                            <h3 style="font-size: 1.5rem; color: rgba(245, 245, 247, 0.7); line-height: 1.2; text-align: center; font-weight: 400; letter-spacing: -0.025em;" class="vc_custom_heading m-4 mx-xl-5 d-inline-block align-middle">
                                The Lowest Prices Once A Month! Hurry To Snap Up
                            </h3>
                            <div class="btn-container mb-0 align-middle btn-border-gray d-inline-block">
                                <a class="vc_btn3 vc_btn3-shape-default btn btn-borders btn-md btn-light" style="font-size: 1rem; font-weight: 600; letter-spacing: -0.025em; padding: 0.8em 3.2em;" href="#" title="">SHOP NOW!</a>
                            </div>
                        </div>
                    </div>
                    <h2 style="font-size: 1.375rem; line-height: 1; font-weight: 600; position: relative;" class="vc_custom_heading mb-3">
                        Recently Viewed Products
                        <a class="porto-sicon-box-link" href="#" title="Shop" style="position: absolute; right: 0; top: 3px;">
                            <div class="porto-sicon-box mb-2 style_1 heading-right-icon" style="margin-top: 5px;">
                                <div class="porto-sicon-header"><h6 class="porto-sicon-title" style="font-weight: 600; font-size: 0.75rem; line-height: 1; letter-spacing: -0.02em; color: #0e39ff;">View All</h6></div>
                                <div class="porto-sicon-heading-right">
                                    <div class="porto-just-icon-wrapper porto-icon none d-block" style="color: #0e39ff; font-size: 12px; margin-top: 3px;"><i class="fas fa-long-arrow-alt-right"></i></div>
                                </div>
                            </div>
                        </a>
                    </h2>
                    <div id="recently-products" class="custom-padding porto-products wpb_content_element m-b-xxl bg-gray clear">
                        <div class="slider-wrapper" style="margin-left: -0.5px; margin-right: -0.5px;">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" extra_class="nav-center-images-only nav-style-1 dots-style-1" product_type="3" product_count="8" aspect_ratio="0"
                            image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#recently-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 6,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
