<style>
    header.page-header.type20 {
        position: absolute;
        width: 100%;
        top: 0;
        background-color: transparent;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .layout-fullwidth .container {
        padding-left: 10px;
        padding-right: 10px;
    }
    @media (min-width: 576px) {
        .layout-fullwidth .container {
            max-width: 540px;
        }
    }
    @media (min-width: 768px) {
        .layout-fullwidth .container {
            max-width: 720px;
        }
    }
    @media (min-width: 992px) {
        .layout-fullwidth .container {
            max-width: 960px;
        }
    }
    @media (min-width: 1160px) {
        .layout-fullwidth .container {
            max-width: 1140px;
        }
    }
    @media (max-width: 991px) {
        .layout-fullwidth .container {
            max-width: none;
        }
    }
    .cms-index-index .page-main {
        padding: 0 !important;
    }
    .home-slider .porto-ultimate-content-box {
        min-height: calc(100vh - 48px) !important;
    }
    @media (min-width: 992px) {
        .home-slider .container {
            width: 50%;
        }
        .heading.heading-middle-border-center {
            max-width: 60%;
            margin-left: auto;
            margin-right: auto;
        }
    }
    @media (min-width: 1160px) {
        .pl-xl-5,
        .px-xl-5 {
            padding-left: 3rem !important;
        }
    }
    @media (min-width: 1200px) {
        .home-slider .container {
            width: 60%;
        }
    }
    @media (min-width: 1600px) {
        .home-slider .container {
            width: 100%;
        }
    }
    @media (max-width: 480px) {
        .porto-ultimate-content-box {
            font-size: 6px;
        }
    }
    .sale-text strong {
        font-size: 220%;
        vertical-align: text-top;
    }
    .porto-ultimate-content-box .btn-container {
        font-size: 1em;
    }
    .porto-ultimate-content-box .btn-borders.btn-xl {
        font-size: 1.9em;
    }
    .tri-line,
    .heading.heading-middle-border .heading-tag:before,
    .heading.heading-middle-border .heading-tag:after {
        background: url({{mediaurl=wysiwyg/smartwave/porto/homepage/30/shop30_divider_line.png}}) repeat-x;
        background-position: left top;
        min-height: 8px;
        border: none;
    }
    .vc_custom_heading h2 b {
        font-weight: 600;
        margin-right: 0.375rem;
    }
    .home-slider .owl-carousel .owl-nav {
        right: 4%;
        bottom: 5%;
        top: auto;
        width: auto;
    }
    .home-slider .owl-carousel .owl-nav > button {
        position: static;
    }
    .home-slider .widget_sidebar_menu {
        position: absolute;
        left: 3.125vw;
        top: 120px;
        z-index: 1;
        background: none;
    }
    .rtl .home-slider .widget_sidebar_menu {
        right: 3.125vw;
        left: auto;
    }
    @media (min-width: 992px) {
        .home-slider .widget_sidebar_menu {
            width: calc(43.75vw - 25%);
        }
    }
    @media (min-width: 1200px) {
        .home-slider .widget_sidebar_menu {
            width: calc(43.75vw - 30%);
        }
    }
    @media (min-width: 1600px) {
        .home-slider .widget_sidebar_menu {
            width: calc(43.75vw - 570px);
        }
    }
</style>
<div class="row home-slider no-padding" style="padding-top: 48px; background-color: #f1f1ef;">
    <div class="col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div id="banner-slider-demo-30" class="porto-carousel owl-carousel home-banner-slider mb-0 nav-style-4 show-nav-hover">
                <div class="porto-ultimate-content-box-container">
                    <div
                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                        style="background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center center;
                      background-color: rgba(0, 0, 0, 0);
                      background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/30/shop30_home_slider1.jpg}}');
                      padding-top: 90px;
                      padding-bottom: 90px;"
                    >
                        <div class="porto-container container pl-4 pl-xl-5" style="padding-right: 10px;">
                            <p style="font-size: 2.2em; line-height: 1; font-weight: 500;" class="vc_custom_heading ls-n-20 mb-3 align-left">
                                New Brown Collection
                            </p>
                            <h2 style="font-size: 6.875em; line-height: 1; letter-spacing: 0.005em;" class="vc_custom_heading mb-0 align-left">Summer Sale</h2>
                            <h3 style="font-size: 12.1em; line-height: 1;" class="vc_custom_heading mb-3 align-left appear-animation">30% OFF</h3>
                            <h4 style="font-size: 1.7em;" class="vc_custom_heading mr-3 pull-left align-left">STARTING AT</h4>
                            <h4 style="font-size: 1.7em; line-height: 1;" class="vc_custom_heading mr-4 mr-xl-5 pull-left sale-text align-left heading-primary">
                                $<strong>39</strong>99
                            </h4>
                            <div class="btn-container mb-0 d-inline-block">
                                <button class="vc_btn3 vc_btn3-shape-default btn btn-borders btn-xl btn-dark">
                                    GET YOURS!
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="porto-ultimate-content-box-container">
                    <div
                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                        style="
                      background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center center;
                      background-color: rgba(0, 0, 0, 0);
                      background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/30/shop30_home_slider2.jpg}}');
                      padding-top: 90px !important;
                      padding-bottom: 90px !important;
                      "
                    >
                        <div class="porto-container container pl-4 pl-xl-5" style="padding-right: 10px;">
                            <div class="vc_row wpb_row vc_inner row justify-content-end" style="margin-right: 0px; margin-left: 0px;">
                                <div class="col-auto pr-4 pr-xl-5 vc_column_container col-md-12" style="padding-top: 2.25rem;">
                                    <div class="wpb_wrapper vc_column-inner">
                                        <h2 style="font-size: 7.6em; line-height: 1; padding-top: 2.2rem;" class="vc_custom_heading mb-0 tri-line align-left">Must Have</h2>
                                        <h3 style="font-size: 9.3em; line-height: 1;" class="vc_custom_heading mb-4 align-left">SANDALS</h3>
                                        <h4 style="font-size: 1.7em;" class="vc_custom_heading mr-3 pull-left align-left">STARTING AT</h4>
                                        <h4 style="font-size: 1.7em; line-height: 1;" class="vc_custom_heading mr-4 pull-left sale-text align-left heading-primary">$<strong>19</strong>99</h4>
                                        <div class="btn-container mb-0 d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-borders btn-lg btn-dark">GET YOURS!</button></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="widget_sidebar_menu main-sidebar-menu d-none d-lg-block">
                <div class="sidebar-menu-wrap">
                    {{block class="MagentoEgypt\PortoExtend\Block\Megamenu" name="sw.sidenav" template="Vnecoms_VendorsDomain::sidemenu.phtml"}}
                </div>
            </div>
        </div>
        <script type="text/javascript">
            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                var owl_30 = $("#banner-slider-demo-30").owlCarousel({
                    items: 1,
                    autoplay: false,
                    autoplayTimeout: 5000,
                    autoplayHoverPause: true,
                    dots: false,
                    navRewind: true,
                    animateIn: "fadeIn",
                    animateOut: "fadeOut",
                    loop: true,
                    nav: true,
                });
            });
        </script>
    </div>
</div>
<style>
    .home-bar .porto-sicon-box {
        margin-bottom: 0;
        justify-content: center;
        padding: 2rem 0;
    }
    .home-bar .col-md-6:not(:last-child) {
        border-right: 1px solid #fff;
    }
</style>
<div class="vc_row wpb_row row home-bar no-padding vc_row-has-fill" style="background-color: #ededea;">
    <div class="col-md-6 col-xl-3">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-sicon-box style_1 default-icon">
                <div class="porto-sicon-default">
                    <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 35px;"><i class="porto-icon-shipping"></i></div>
                </div>
                <div class="porto-sicon-header">
                    <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 1;">FREE SHIPPING & RETURN</h3>
                    <p style="font-size: 13px; line-height: 1.4; color: #666666;">Free shipping on all orders over $99.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-3">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-sicon-box style_1 default-icon">
                <div class="porto-sicon-default">
                    <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 37px;"><i class="porto-icon-money"></i></div>
                </div>
                <div class="porto-sicon-header">
                    <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 1;">MONEY BACK GUARANTEE</h3>
                    <p style="font-size: 13px; line-height: 1.4; color: #666666;">100% money back guarantee</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-3">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-sicon-box style_1 default-icon">
                <div class="porto-sicon-default">
                    <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 37px;"><i class="porto-icon-support"></i></div>
                </div>
                <div class="porto-sicon-header">
                    <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 1;">ONLINE SUPPORT 24/7</h3>
                    <p style="font-size: 13px; line-height: 1.4; color: #666666;">Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-3">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-sicon-box style_1 default-icon">
                <div class="porto-sicon-default">
                    <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 35px;"><i class="porto-icon-secure-payment"></i></div>
                </div>
                <div class="porto-sicon-header">
                    <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 14px; line-height: 1;">SECURE PAYMENT</h3>
                    <p style="font-size: 13px; line-height: 1.4; color: #666666;">Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row pt-5 section-no-borders porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_custom_heading mb-0 heading heading-border heading-middle-border heading-middle-border-center">
                        <h2 style="font-size: 1.625rem; line-height: 1; text-align: center; font-weight: 300;" class="heading-tag"><b>Featured</b> Products</h2>
                    </div>
                    <p style="text-align: center;" class="vc_custom_heading mb-4 pb-1">Amazing products added recently in our catalog</p>
                    <div class="porto-products wpb_content_element archive-products mb-0">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="3" product_count="4" column_count="4" aspect_ratio="0" image_width="350" image_height="350"
                        template="grid.phtml"}}
                    </div>
                    <div class="porto-separator tall"><hr class="separator-line align_center solid" /></div>
                    <div class="vc_custom_heading mb-0 pt-2 heading heading-border heading-middle-border heading-middle-border-center">
                        <h2 style="font-size: 1.625rem; line-height: 1; text-align: center; font-weight: 300;" class="heading-tag"><b>Summer</b> Collection</h2>
                    </div>
                    <p style="text-align: center;" class="vc_custom_heading mb-4 pb-1">Amazing products added recently in our catalog</p>
                    <div class="porto-grid-container">
                        <div id="porto-banner-masonry" class="porto-banner-grid mb-5 porto-preset-layout wpb_content_element clearfix">
                            <div class="porto-grid-item grid-col-1-2 grid-col-md-1 grid-height-1">
                                <div class="porto-ibanner porto-ibe-zoom" style="background: #f4f4f4;">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/30/shop30_home_banner.jpg}}" />
                                    <div class="porto-ibanner-desc no-padding d-flex">
                                        <div class="porto-ibanner-layer" style="right: 7%; top: 50%; transform: translateY(-50%);">
                                            <h3 style="font-size: 3.75em; line-height: 1.2;" class="vc_custom_heading custom-font4 mb-0 align-right">
                                                Sport<br />
                                                Shoes
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2">
                                <div class="porto-ultimate-content-box-container">
                                    <div class="porto-ultimate-content-box has-content-pos justify-content-center" style="background-color: #222529;" data-bg="#222529" id="porto_ucb_3476">
                                        <h3 style="font-size: 3.2em; line-height: 1; text-align: center;" class="vc_custom_heading custom-font4 mb-0 heading-light">For Her</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2">
                                <div class="porto-ibanner porto-ibe-zoom" style="">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/30/Product-9.jpg}}" />
                                    <a class="porto-ibanner-link" href="#"></a>
                                </div>
                            </div>
                            <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2">
                                <div class="porto-ultimate-content-box-container">
                                    <div class="porto-ultimate-content-box has-content-pos justify-content-center" style="background-color: #222529;" data-bg="#222529" id="porto_ucb_1956">
                                        <h3 style="font-size: 3.2em; line-height: 1; text-align: center;" class="vc_custom_heading custom-font4 mb-0 heading-light">For Him</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2">
                                <div class="porto-ibanner porto-ibe-zoom" style="">
                                    <img src="{{media url=wysiwyg/smartwave/porto/homepage/30/Product-11.jpg}}" />
                                    <a class="porto-ibanner-link" href="#"></a>
                                </div>
                            </div>
                            <div class="grid-col-sizer"></div>
                        </div>
                        <style scope="scope">
                            .porto-banner-grid .porto-grid-item {
                                padding: 10px;
                            }
                            .porto-banner-grid {
                                margin: -10px -10px 10px;
                                opacity: 0;
                            }
                            .porto-banner-grid .grid-col-1-2 {
                                flex: 0 0 50%;
                                width: 50%;
                            }
                            .porto-banner-grid .grid-col-1-4 {
                                flex: 0 0 25%;
                                width: 25%;
                            }
                            .porto-banner-grid .grid-col-sizer {
                                flex: 0 0 25%;
                                width: 25%;
                            }
                            .porto-banner-grid .grid-height-1 {
                                height: 550px;
                            }
                            .porto-banner-grid .grid-height-1-2 {
                                height: 275px;
                            }
                            .porto-preset-layout .porto-grid-item > *,
                            .porto-preset-layout .vc_porto_grid_item > *,
                            .porto-preset-layout .porto-ultimate-content-box-container,
                            .porto-preset-layout .porto-ultimate-content-box,
                            .porto-preset-layout .porto-ibanner,
                            .porto-preset-layout .porto-ibanner > img {
                                height: 100%;
                                margin-bottom: 0;
                            }
                            @media (max-width: 767px) {
                                .porto-banner-grid .grid-col-md-1 {
                                    flex: 0 0 100%;
                                    width: 100%;
                                }
                                .porto-banner-grid .grid-col-md-1-2 {
                                    flex: 0 0 50%;
                                    width: 50%;
                                }
                                .porto-banner-grid .grid-col-sizer {
                                    flex: 0 0 50%;
                                    width: 50%;
                                }
                                .porto-banner-grid .grid-height-1 {
                                    height: 367px;
                                }
                                .porto-banner-grid .grid-height-1-2 {
                                    height: 183px;
                                }
                            }
                            @media (max-width: 480px) {
                                .porto-banner-grid .porto-grid-item {
                                    flex: 0 0 100%;
                                    width: 100%;
                                }
                            }
                        </style>
                        <script type="text/javascript">
                            require(["jquery", "packery"], function ($, Packery) {
                                $.bridget("packery", Packery);
                                var $container = $("#porto-banner-masonry");
                                $container.css("opacity", 0);
                                if ($container.length > 0) {
                                    $container.imagesLoaded(function () {
                                        $container.packery({
                                            itemSelector: ".porto-grid-item",
                                            columnWidth: ".grid-col-sizer",
                                            percentPosition: true,
                                        });
                                    });
                                    setTimeout(function () {
                                        $container.animate(
                                            {
                                                opacity: 1,
                                            },
                                            200
                                        );
                                    }, 500);
                                }
                            });
                        </script>
                    </div>
                    <div class="porto-separator tall"><hr class="separator-line align_center solid" /></div>
                    <div class="vc_custom_heading mb-0 pt-2 heading heading-border heading-middle-border heading-middle-border-center">
                        <h2 style="font-size: 1.625rem; line-height: 1; text-align: center; font-weight: 300;" class="heading-tag"><b>Best Seller</b> Products</h2>
                    </div>
                    <p style="text-align: center;" class="vc_custom_heading mb-4 pb-1">Only the best seller products added recently in our catalog</p>
                    <div id="bestseller-products" class="porto-products wpb_content_element">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1 product_type="3"
                            product_count="8" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#bestseller-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 3,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="porto-separator mb-4"><hr class="separator-line align_center solid" /></div>
                    <div class="porto-carousel brand-carousel owl-carousel py-4 mb-4">
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand1.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand2.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand3.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand4.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand5.png}}" alt="" /></div>
                        <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand6.png}}" alt="" /></div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".brand-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 3,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 6,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
