<style>
    .columns .column.main {
        padding-bottom: 0;
    }
    .page-header.type9 {
        position: absolute;
        width: 100%;
        top: 0;
        background: none;
    }
    .page-header.type9:not(.sticky-header) .header-main {
        background: none;
    }
    .fullscreen-carousel {
        height: 100vh;
        position: relative;
        max-height: 804px;
    }
    .fullscreen-carousel .owl-carousel:not(.owl-loaded) > *,
    .fullscreen-carousel .owl-item > * {
        height: 100vh;
    }
    .fullscreen-carousel .owl-item .porto-ultimate-content-box {
        height: 100%;
    }
    .fullscreen-carousel .owl-item .porto-ultimate-content-box-container {
        max-height: 804px;
    }
    .coupon-sale-text {
        position: relative;
        padding-left: 0.265em;
        transform: none;
        letter-spacing: 0;
    }
    .coupon-sale-text i {
        font-style: normal;
        font-size: 0.265em;
        font-weight: 500;
        transform: translateY(-50%) rotate(-90deg);
        position: absolute;
        top: 50%;
        left: -1em;
    }
    .vc_custom_heading strong {
        font-size: 2em;
        vertical-align: text-top;
    }
    @media (max-width: 991px) {
        .porto-ultimate-content-box {
            font-size: 9px;
        }
    }
    @media (max-width: 767px) {
        .porto-ultimate-content-box {
            font-size: 7px;
        }
    }
    @media (max-width: 575px) {
        .porto-ultimate-content-box {
            font-size: 6px;
        }
    }
</style>
<div class="row home-banner-slider no-padding" style="margin-top: 60px; background-color: #9c948f;">
    <div class="col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div class="fullscreen-carousel">
                <div id="banner-slider-demo-11" class="porto-carousel owl-carousel home-banner-slider mb-0 nav-pos-inside nav-style-4 show-nav-hover">
                    <div class="porto-ultimate-content-box-container">
                        <div
                            class="porto-ultimate-content-box has-content-pos justify-content-center porto-lazyload lazy-load-loaded"
                            style="padding-top: 80px;
                        background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        background-color: rgba(0, 0, 0, 0);
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/11/shop11_home_slider1.jpg}}');
                        "
                        >
                            <div class="porto-container container inner-30 inner-lg-45">
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="pl-lg-4 col-sm-9 offset-sm-3 vc_column_container col-md-9 offset-lg-5 col-lg-7 offset-md-3 col-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h2 style="font-size: 4.8em; line-height: 1;" class="vc_custom_heading mb-2 align-left">New Season Dresses</h2>
                                            <h3 style="font-size: 11.3em; line-height: 1;" class="vc_custom_heading coupon-sale-text mb-4 align-left"><i>UP TO</i>50% OFF</h3>
                                            <div class="porto-separator mb-0"><hr class="separator-line align_left solid" style="background-color: #222529; height: 5px; width: 10%;" /></div>
                                            <h4 style="font-size: 2em; line-height: 1;" class="vc_custom_heading d-inline-block ls-n-20 mr-4 my-3 align-left">STARTING AT $<strong>39</strong>99</h4>
                                            <div class="btn-container mb-0 d-inline-block" style="margin-left: -2px;">
                                                <a class="btn btn-modern btn-xl btn-light" href="#" title="Shop"> Shop Now <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i> </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ultimate-content-box-container">
                        <div
                            class="porto-ultimate-content-box has-content-pos justify-content-center"
                            style="padding-top: 80px;
                        background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        background-color: rgba(0, 0, 0, 0);
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/11/shop11_home_slider2.jpg}}');
                        "
                        >
                            <div class="container inner-30 inner-lg-45">
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="pl-4 col-md-9 col-xl-7 offset-lg-1 col-lg-8 col-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h2 style="font-size: 4.8em; line-height: 1;" class="vc_custom_heading mb-2 align-left">New Season Dresses</h2>
                                            <h3 style="font-size: 11.3em; line-height: 1;" class="vc_custom_heading coupon-sale-text mb-4 align-left"><i>UP TO</i>20% OFF</h3>
                                            <div class="porto-separator mb-0"><hr class="separator-line align_left solid" style="background-color: #222529; height: 5px; width: 10%;" /></div>
                                            <h4 style="font-size: 2em; line-height: 1;" class="vc_custom_heading d-inline-block ls-n-20 mr-4 my-3 align-left">STARTING AT $<strong>19</strong>99</h4>
                                            <div class="btn-container mb-0 d-inline-block" style="margin-left: -2px;">
                                                <button class="btn btn-modern btn-xl btn-light">Shop Now <i style="padding-left: 7px;" class="fas fa-long-arrow-alt-right"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                    $("#banner-slider-demo-11").owlCarousel({
                        items: 1,
                        autoplay: false,
                        autoplayTimeout: 5000,
                        autoplayHoverPause: true,
                        dots: false,
                        navRewind: true,
                        animateIn: "fadeIn",
                        animateOut: "fadeOut",
                        loop: true,
                        nav: true,
                    });
                });
            </script>
        </div>
    </div>
</div>
<div class="home-ads no-padding" style="background-color: #efefef;">
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block35')->toHtml() ?>
    <style>
        .home-ads .row > div {
            border-right: 1px solid #dedede;
        }
        .home-ads .row > div:first-child {
            border-left: 1px solid #dedede;
        }
        @media (max-width: 767px) {
            .home-ads .row > div {
                border-bottom: 1px solid #dedede;
                border-left: 1px solid #dedede;
            }
        }
    </style>
</div>
<div class="home-bar no-padding porto-inner-container">
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block32')->toHtml() ?>
    <style>
        .home-bar .row > div {
            padding-top: 24px;
            padding-bottom: 24px;
            border-right: 1px solid #dedede;
            border-bottom: 1px solid #dedede;
        }
        .home-bar .row > div:first-child {
            border-left: 1px solid #dedede;
        }
        .home-bar .row > div:first-child {
            border-left: 1px solid #dedede;
        }
        .home-bar .porto-sicon-box {
            justify-content: center;
            margin-bottom: 0;
        }
        @media (max-width: 991px) {
            .home-bar .row > div {
                border-left: 1px solid #dedede;
            }
            .home-bar .porto-sicon-box {
                justify-content: flex-start;
                padding: 0 1.5rem;
            }
        }
    </style>
</div>
<div class="vc_row wpb_row porto-inner-container" style="padding-top: 55px; padding-bottom: 30px;">
    <style>
        .porto-u-heading .porto-u-main-heading h2 {
            padding: 0;
            margin: 0;
        }
        ul.products li.product-category .thumb-info-wrapper:after {
            background: rgba(27, 27, 23, 0);
        }
        ul.products li.product-category:hover .thumb-info-wrapper:after {
            background: rgba(27, 27, 23, 0.15);
        }
        ul.products li.product-category .thumb-info h3 {
            position: relative;
            padding-top: 1rem;
            padding-bottom: 1rem;
            margin-left: 0.5rem;
            margin-right: 0.5rem;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: none;
            line-height: 1.35;
        }
        ul.products li.product-category .thumb-info h3:before {
            content: "";
            position: absolute;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            background: #fff;
            transform: skew(-20deg);
            z-index: -1;
        }
        ul.products li.product-category .thumb-info h3:after {
            content: "\f30b";
            font-family: "Font Awesome 5 Free";
            margin-left: 0.25rem;
        }
        .porto-products.hide-count li.product-category .thumb-info-type {
            display: none;
        }
    </style>
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-4 text-center">
                        <div class="porto-u-main-heading"><h2 style="font-weight: 700; font-size: 1.375rem; line-height: 1.1;"><?= __('FEATURED PRODUCTS') ?></h2></div>
                        <div class="porto-u-sub-heading" style=""><?= __('Amazing products added recently in our catalog') ?></div>
                    </div>
                    <div class="porto-products wpb_content_element archive-products mb-5">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="3" extra_class="nav-center-images-only nav-style-4" product_count="4" column_count="4" aspect_ratio="0"
                        image_width="250" image_height="250" template="grid.phtml"}}
                        <div class="load-more text-center" style="margin: 21px 0 61px;">
                            <a class="btn btn-modern btn-dark" href="#" style="padding: 1.1em 2.6em; font-size: 0.875rem; line-height: 1.3333; letter-spacing: 0; border: none;"><?= __('Show More') ?>...</a>
                        </div>
                    </div>
                    <div class="porto-separator tall mb-5"><hr class="separator-line align_center solid" /></div>
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block33')->toHtml() ?>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".category-slider .owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: false,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 2,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 5,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block34')->toHtml() ?>
<div class="vc_row wpb_row porto-inner-container" style="padding-top: 55px; padding-bottom: 20px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-u-heading mb-4 text-center">
                        <div class="porto-u-main-heading"><h2 style="font-weight: 700; font-size: 1.375rem; line-height: 1.1;"><?= __('TOP RATED PRODUCTS') ?></h2></div>
                        <div class="porto-u-sub-heading" style=""><?= __('Only the top rated products added recently in our catalog') ?></div>
                    </div>
                    <div class="porto-products wpb_content_element mb-3">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="3" extra_class="nav-center-images-only nav-style-4" product_count="3" column_count="3" aspect_ratio="0"
                        image_width="350" image_height="350" template="grid.phtml"}}
                    </div>
                    <div class="porto-separator tall mb-5"><hr class="separator-line align_center solid" /></div>
                    <div class="vc_row wpb_row vc_inner row">
                        <div class="col-md-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_products">
                                        <h2 class="widgettitle"><?= __('Recently Added Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_products">
                                        <h2 class="widgettitle"><?= __('Best Selling Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\BestsellersList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_products">
                                        <h2 class="widgettitle"><?= __('Featured Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row porto-inner-container" style="padding-top: 2rem; padding-bottom: 2rem;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-brand">
                        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block10')->toHtml() ?>
                        <script type="text/javascript">
                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                $(".brand-carousel.owl-carousel").owlCarousel({
                                    autoplay: true,
                                    autoplayTimeout: 5000,
                                    autoplayHoverPause: true,
                                    nav: true,
                                    dots: false,
                                    loop: false,
                                    responsive: {
                                        0: {
                                            items: 2,
                                        },
                                        640: {
                                            items: 3,
                                        },
                                        768: {
                                            items: 4,
                                        },
                                        992: {
                                            items: 5,
                                        },
                                        1200: {
                                            items: 6,
                                        },
                                    },
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
