<style>
    .columns .column.main {
        padding: 0;
    }
    .pt_row {
        clear: both;
    }
    hr.solid,
    hr {
        background: rgba(255, 255, 255, 0.06);
    }
    .ls-10em {
        letter-spacing: 0.01em;
    }
    .ls-25em {
        letter-spacing: 0.025em;
    }
    .ls-negative-25em {
        letter-spacing: -0.025em;
    }
    .font-weight-semibold,
    .text-weight-semibold {
        font-weight: 600;
    }
    .pc-position-absolute {
        position: absolute !important;
    }
    .right-0,
    .pc-right-0 {
        right: 0;
    }
    .bottom-0,
    .pc-bottom-0 {
        bottom: 0;
    }
    .top-0,
    .pc-top-0 {
        top: 0;
    }
    .left-0,
    .pc-left-0 {
        top: 0;
    }
    .pt_btn3.btn {
        font-family: "Open Sans";
        font-weight: 700;
        text-transform: uppercase;
        padding: 1.2em 2.5em;
        letter-spacing: 0.01em;
    }
    .pt_btn3.btn-sm {
        padding: 1em 2.25em;
    }
    .porto-ultimate-content-box {
        position: relative;
        font-size: inherit;
    }
    .porto-ultimate-content-box .btn-container {
        font-size: inherit;
        margin-bottom: 20px;
    }
    .porto-ultimate-content-box .price del {
        font-size: 65%;
        color: #a7a7a7;
    }
    .coupon-text-sale {
        transform: rotate(0);
        letter-spacing: 0.01em;
        position: relative;
        padding-left: 8px;
    }
    .coupon-text-sale i {
        font-style: normal;
        position: absolute;
        left: -1.5em;
        top: 50%;
        transform: translateY(-50%) rotate(-90deg);
        font-size: 0.65em;
        opacity: 0.6;
        letter-spacing: 0;
    }
    .coupon-text-sale b {
        display: inline-block;
        background: #ee8379;
        color: #fff;
        font-size: 1.6em;
        padding: 4px 8px;
        margin-right: 0.25rem;
    }
</style>
<div class="pt_row porto-inner-container" style="margin-top: 20px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="m-b-md pt_column_container col-md-8">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="porto-ultimate-content-box-container">
                        <div
                            class="porto-ultimate-content-box has-content-pos justify-content-center"
                            style="background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        min-height: 440px;
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_banner1.jpg}}');
                        padding-right: 40px;
                        background-color: #181a1c;"
                        >
                            <h3
                                style="font-size: 18px; line-height: 1; font-weight: 700; padding-top: 10px; padding-right: 12px; padding-bottom: 10px; padding-left: 12px;"
                                class="pt_custom_heading align-self-end background-color-primary align-right text-uppercase heading-light"
                            >
                                50% OFF
                            </h3>
                            <h2 style="font-size: 40px; line-height: 1; font-weight: 700;" class="pt_custom_heading mb-2 ls-10em align-right text-uppercase heading-light">
                                PORTOGEAR 2
                            </h2>
                            <h3 style="font-size: 28px; line-height: 1.2; font-weight: 600;" class="pt_custom_heading price mb-0 align-right heading-light"><del>$59</del> $29</h3>
                            <div class="btn-container pc-position-absolute pc-bottom-0 pc-right-0 d-inline-block" style="margin-right: 20px;">
                                <button class="pt_btn3 btn btn-lg btn-quaternary">Shop Now</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt_column_container col-md-4">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="porto-ultimate-content-box-container m-b-md">
                        <div
                            class="porto-ultimate-content-box has-content-pos justify-content-end"
                            style="background-size: contain;
                        background-repeat: no-repeat;
                        background-position: left center;
                        min-height: 210px;
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_banner2.png}}');
                        padding-right: 20px;
                        padding-bottom: 20px;
                        background-color: #181a1c;"
                        >
                            <h3 style="font-size: 13px; color: rgba(255, 255, 255, 0.4); line-height: 1; font-weight: 700;" class="pt_custom_heading mb-2 ls-25em align-right text-uppercase">
                                flash sales on
                            </h3>
                            <h2 style="font-size: 28px; line-height: 0.9; font-weight: 700;" class="pt_custom_heading ls-10em mb-5 align-right heading-light">
                                CONSOLES
                            </h2>
                            <div class="btn-container mb-0 text-right">
                                <button class="pt_btn3 pt_btn3-shape-default btn btn-sm btn-quaternary">
                                    SHOP NOW
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ultimate-content-box-container m-b-md">
                        <div
                            class="porto-ultimate-content-box"
                            style="background-size: cover;
                        background-repeat: no-repeat;
                        background-position: center center;
                        min-height: 210px;
                        background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_banner3.jpg}}');
                        padding-top: 20px;
                        padding-left: 25px;
                        background-color: #181a1c;"
                        >
                            <h3 style="font-size: 13px; color: rgba(255, 255, 255, 0.4); line-height: 1; font-weight: 700;" class="pt_custom_heading mb-1 ls-25em align-left text-uppercase">
                                CHECK NEW WIRELESS
                            </h3>
                            <h2 style="font-size: 23px; line-height: 1; font-weight: 700;" class="pt_custom_heading ls-10em mb-3 align-left heading-light">
                                CONTROLLERS
                            </h2>
                            <h3 style="font-size: 16px; line-height: 1; font-weight: 700;" class="pt_custom_heading coupon-text-sale mb-0 align-left text-uppercase heading-light"><i>Up To</i><b>50%</b> OFF</h3>
                            <div class="btn-container pc-position-absolute pc-bottom-0 pc-right-0 text-right" style="margin-right: 20px;">
                                <button class="pt_btn3 btn btn-sm btn-quaternary">SHOP NOW</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .home-features .pt_column_container > .pt_column-inner {
        width: auto;
        border-right: 1px solid #2c2f33;
        display: flex;
        justify-content: center;
        padding-top: 15px !important;
        padding-bottom: 15px !important;
    }
    @media (max-width: 767px) {
        .home-features .pt_column_container > .pt_column-inner {
            border-right: none;
            justify-content: flex-start;
            padding-left: 5% !important;
            border-bottom: 1px solid #2c2f33;
        }
    }
    .home-features .pt_column_container:last-child > .pt_column-inner {
        border-right: none;
        border-bottom: none;
    }
</style>
<div class="pt_row home-features no-padding porto-inner-container" style="padding-top: 10px; padding-bottom: 30px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="pt_column_container col-md-4">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #0078f2; font-size: 35px; display: inline-block;"><i class="porto-icon-shipping"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h4 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px;">FREE SHIPPING & RETURN</h4>
                            <p style="font-weight: 300; font-size: 13px; line-height: 20px; color: #839199;">Free shipping on all orders over $99</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt_column_container col-md-4">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #0078f2; font-size: 35px; display: inline-block;"><i class="porto-icon-money"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h4 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px;">MONEY BACK GUARANTEE</h4>
                            <p style="font-weight: 300; font-size: 13px; line-height: 20px; color: #839199;">100% money back guarantee</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt_column_container col-md-4">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="porto-sicon-box style_1 default-icon">
                        <div class="porto-sicon-default">
                            <div class="porto-just-icon-wrapper" style="text-align: center;">
                                <div class="porto-icon none" style="color: #0078f2; font-size: 35px; display: inline-block;"><i class="porto-icon-support"></i></div>
                            </div>
                        </div>
                        <div class="porto-sicon-header">
                            <h4 class="porto-sicon-title" style="font-weight: 600; font-size: 15px; line-height: 15px;">ONLINE SUPPORT 24/7</h4>
                            <p style="font-weight: 300; font-size: 13px; line-height: 20px; color: #839199;">Lorem ipsum dolor sit amet</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt_row pt_row-has-fill porto-inner-container" style="padding-top: 65px; padding-bottom: 40px; background-color: #1c1e21;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="pt_column_container col-md-12">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="wpb_text_column wpb_content_element pull-right mb-2 pc-position-static">
                        <div class="wpb_wrapper">
                            <p class="mb-0">
                                <a class="font-weight-semibold text-color-primary text-uppercase" style="font-size: 12px;" title="Shop" href="#"> View All Products<i class="fas fa-long-arrow-alt-right ml-1"></i> </a>
                            </p>
                            <p style="position: absolute; top: 0; left: -22%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 3, 'transition': true}">
                                <img class="alignnone size-full" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating5.png}}" />
                            </p>
                            <p style="position: absolute; top: 39%; left: -26%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 3.5, 'transition': true, 'horizontal': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating6.png}}" />
                            </p>
                            <p style="position: absolute; top: 62%; left: -14%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 2.5, 'transition': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating7.png}}" />
                            </p>
                            <p style="position: absolute; top: 22%; left: -12%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 2, 'transition': true, 'horizontal': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating8.png}}" data-plugin-options="{'startPos': 'none', 'speed': 2, 'transition': true, 'horizontal': true}" />
                            </p>
                            <p style="position: absolute; top: 58%; right: -26%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 3, 'transition': true}">
                                <img class="alignnone size-full" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating1.png}}" />
                            </p>
                            <p style="position: absolute; top: 25%; right: -26%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 3.5, 'transition': true, 'horizontal': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating2.png}}" />
                            </p>
                            <p style="position: absolute; top: 0; right: -16%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 2.5, 'transition': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating3.png}}" />
                            </p>
                            <p style="position: absolute; top: 38%; right: -11%;" data-plugin-float-element="" data-plugin-options="{'startPos': 'none', 'speed': 2, 'transition': true, 'horizontal': true}">
                                <img class="alignnone" src="{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_floating4.png}}" />
                            </p>
                        </div>
                        <script type="text/javascript">
                            require(["jquery", "floatelement"], function ($) {
                                $("[data-plugin-float-element]:not(.manual)").each(function () {
                                    var options = $(this).data("plugin-options");
                                    if (options && "string" == typeof options)
                                        try {
                                            options = JSON.parse(options.replace(/'/g, '"').replace(";", ""));
                                        } catch (options) {}
                                    $(this).themePluginFloatElement(options);
                                });
                            });
                        </script>
                    </div>
                    <h4 style="font-size: 24px; line-height: 1; font-weight: 600;" class="pt_custom_heading mb-4 align-left">Featured Product and Offers</h4>
                    <div class="porto-products wpb_content_element mb-0">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_type="3" product_count="4" column_count="4" aspect_ratio="1" image_width="300" image_height="420"
                        template="grid.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt_row porto-inner-container" style="padding-top: 40px; padding-bottom: 20px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="pt_column_container col-md-12">
                <div class="wpb_wrapper pt_column-inner">
                    <div class="pt_row pt_inner row pt_row-has-fill pt_row-o-content-middle pt_row-flex" style="margin-right: 0px; margin-bottom: 32px; margin-left: 0px; background-color: #f4f4f4;">
                        <div
                            class="px-0 pt_column_container col-md-4"
                            style="background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_shop_banner.jpg}}');
                     padding-top: 70px;
                     padding-bottom: 70px;
                     background-position: center;
                     background-repeat: no-repeat;
                     background-size: cover;"
                        >
                            <div class="wpb_wrapper pt_column-inner"></div>
                        </div>
                        <div class="py-4 pt_column_container col-md-5">
                            <div class="wpb_wrapper pt_column-inner">
                                <h2 style="font-size: 38px; color: #181a1c; line-height: 1; font-weight: 800;" class="pt_custom_heading mb-1 ls-10em align-left text-uppercase">PORTO SWITCH LITE</h2>
                                <h3 style="font-size: 18px; color: #777777; line-height: 1; font-weight: 700;" class="pt_custom_heading mb-0 ls-25em align-left text-uppercase">now available for pre-order</h3>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-3">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="btn-container mb-3 mb-md-0 d-inline-block"><button class="pt_btn3 btn btn-md btn-quaternary">PRE-ORDER NOW</button></div>
                            </div>
                        </div>
                    </div>
                    <div class="wpb_text_column wpb_content_element pull-right mb-2">
                        <div class="wpb_wrapper">
                            <p>
                                <a class="font-weight-semibold text-color-primary text-uppercase" style="font-size: 12px;" title="Shop" href="#"> View All Products<i class="fas fa-long-arrow-alt-right ml-1"></i> </a>
                            </p>
                        </div>
                    </div>
                    <h4 style="font-size: 24px; line-height: 1; font-weight: 600;" class="pt_custom_heading mb-4 align-left">Recently Released</h4>
                    <div class="pt_row pt_inner row">
                        <div class="pt_column_container col-md-4">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-ultimate-content-box-container h-100">
                                    <div class="porto-ultimate-content-box" style="background-color: #1c1e21; margin-bottom: 20px; padding: 20px;">
                                        <div id="recently-products" class="porto-products wpb_content_element content-center">
                                            <div class="slider-wrapper">
                                                {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="dots-style-1" product_count="3" aspect_ratio="1" image_width="400" image_height="566"
                                                template="owl_list.phtml"}}
                                                <script type="text/javascript">
                                                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                        $("#recently-products .owl-carousel").owlCarousel({
                                                            items: 1,
                                                            autoplay: false,
                                                            autoplayTimeout: 5000,
                                                            autoplayHoverPause: true,
                                                            loop: true,
                                                            navRewind: true,
                                                            lazyLoad: true,
                                                            margin: 0,
                                                            nav: false,
                                                            dots: true,
                                                        });
                                                    });
                                                </script>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-8">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-products wpb_content_element mb-0">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_type="3" product_count="8" column_count="4" aspect_ratio="1" image_width="300" image_height="420"
                                    template="grid.phtml"}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-separator"><hr class="separator-line align_center solid" style="margin-bottom: 40px;" /></div>
                    <div class="wpb_text_column wpb_content_element pull-right mb-2">
                        <div class="wpb_wrapper">
                            <p>
                                <a class="font-weight-semibold text-color-primary text-uppercase" style="font-size: 12px;" title="Shop" href="#"> View All Products<i class="fas fa-long-arrow-alt-right ml-1"></i> </a>
                            </p>
                        </div>
                    </div>
                    <h4 style="font-size: 24px; line-height: 1; font-weight: 600;" class="pt_custom_heading mb-4 align-left">Most Popular</h4>
                    <div class="pt_row pt_inner row">
                        <div class="pt_column_container col-md-8">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-products wpb_content_element mb-0">
                                    {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_type="3" product_count="8" column_count="4" aspect_ratio="1" image_width="300" image_height="420"
                                    template="grid.phtml"}}
                                </div>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-4">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-ultimate-content-box-container h-100">
                                    <div class="porto-ultimate-content-box" style="background-color: #1c1e21; margin-bottom: 20px; padding: 20px;">
                                        <div id="popular-products" class="porto-products wpb_content_element content-center">
                                            <style>
                                                .content-center .product-item-info.type3 {
                                                    text-align: center;
                                                    margin-bottom: 1.5rem;
                                                }
                                                .content-center .product-item-info.type3 .product-reviews-summary {
                                                    margin: 0 auto 0.55rem;
                                                }
                                                .content-center .product-item-name a {
                                                    font-size: 22px;
                                                }
                                            </style>
                                            <div class="slider-wrapper">
                                                {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="dots-style-1" product_count="3" aspect_ratio="1" image_width="400" image_height="566"
                                                template="owl_list.phtml"}}
                                                <script type="text/javascript">
                                                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                        $("#popular-products .owl-carousel").owlCarousel({
                                                            items: 1,
                                                            autoplay: false,
                                                            autoplayTimeout: 5000,
                                                            autoplayHoverPause: true,
                                                            loop: true,
                                                            navRewind: true,
                                                            lazyLoad: true,
                                                            margin: 0,
                                                            nav: false,
                                                            dots: true,
                                                        });
                                                    });
                                                </script>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pt_row pt_inner row">
                        <div class="pt_column_container col-md-6">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-ultimate-content-box-container">
                                    <div
                                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                                        style="background-size: cover;
                          background-repeat: no-repeat;
                          background-position: center center;
                          min-height: 400px;
                          background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_banner4.jpg}}');
                          padding-right: 20px;
                          background-color: #ffffff;"
                                    >
                                        <p style="font-size: 13px; line-height: 1; font-weight: 700;" class="pt_custom_heading custom-font1 mb-1 align-right text-uppercase">FEEL LIKE A PLAYER</p>
                                        <h2 style="font-size: 36px; line-height: 1; font-weight: 800;" class="pt_custom_heading mb-1 ls-negative-25em align-right text-uppercase heading-quaternary"><i>PROBALL 2019</i></h2>
                                        <h3 style="font-size: 28px; line-height: 1; font-weight: 600;" class="pt_custom_heading mb-0 align-right heading-quaternary">$29</h3>
                                        <div class="btn-container pc-position-absolute pc-bottom-0 pc-right-0 d-inline-block" style="margin-right: 20px;">
                                            <button class="pt_btn3 btn btn-sm btn-quaternary">SHOW NOW</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt_column_container col-md-6">
                            <div class="wpb_wrapper pt_column-inner">
                                <div class="porto-ultimate-content-box-container">
                                    <div
                                        class="porto-ultimate-content-box has-content-pos justify-content-center"
                                        style="background-size: cover;
                            background-repeat: no-repeat;
                            background-position: center center;
                            min-height: 400px;
                            background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/29/shop29_home_banner5.jpg}}');
                            margin-bottom: 20px;
                            padding-left: 20px;
                            background-color: #000000;"
                                    >
                                        <h3
                                            style="font-size: 18px; line-height: 1; font-weight: 700; margin-top: 20px; padding: 10px 12px;"
                                            class="pt_custom_heading background-color-primary pc-position-absolute pc-top-0 align-left text-uppercase heading-light"
                                        >
                                            50% OFF
                                        </h3>
                                        <p style="font-size: 13px; color: rgba(255, 255, 255, 0.4); line-height: 1; font-weight: 700;" class="pt_custom_heading custom-font1 mb-1 align-left text-uppercase">be a kendo warrior</p>
                                        <h2 style="font-size: 36px; line-height: 1; font-weight: 800;" class="pt_custom_heading mb-1 ls-negative-25em align-left text-uppercase heading-light">PROWARRIOR</h2>
                                        <h3 style="font-size: 28px; line-height: 1; font-weight: 600;" class="pt_custom_heading mb-0 price align-left heading-light"><del>$59</del> $29</h3>
                                        <div class="btn-container pc-position-absolute pc-bottom-0 d-inline-block"><button class="pt_btn3 btn btn-sm btn-light">SHOW NOW</button></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
