<style>
    .columns .column.main {
        padding-bottom: 0;
    }
    .h-100.owl-carousel .owl-stage-outer,
    .h-100.owl-carousel .owl-stage,
    .h-100.owl-carousel .owl-item,
    .h-100 > .porto-ultimate-content-box {
        height: 100%;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .owl-carousel.nav-inside-left .owl-dots {
        left: 5%;
        bottom: 2rem;
    }
    .product.data.items > .item.content {
        border-width: 2px;
        position: relative;
        top: 0;
        z-index: -1;
        margin-top: 44px;
    }
    @media (max-width: 767px) {
        .product.data.items > .item.content {
            margin-top: 35px;
            padding-top: 0;
        }
    }
    .product.data.items > .item.content > .products {
        margin-top: -9px;
    }
    .product.data.items .item.title {
        font-family: Poppins;
        font-weight: 700;
        font-size: 14px;
        letter-spacing: -0.025em;
        color: #282d3b;
        padding: 10px 0;
    }
    .product.data.items > .item.title:hover {
        border-color: #ee3d43;
        color: #ee3d43;
    }
    .product.data.items > .item.title.active {
        color: #ee3d43;
        border-color: #ee3d43;
    }
    .product.data.items > .item.title > .switch {
        font-size: inherit;
    }
    .bg-size-auto100 > div {
        background-size: auto 100% !important;
    }
    @media (min-width: 768px) {
        .product.data.items > .item.title {
            margin-right: 31px;
        }
        .pc-width-44 {
            flex: 0 0 44.4444%;
            max-width: 44.4444%;
        }
        .pc-width-55 {
            flex: 0 0 55.5555%;
            max-width: 55.5555%;
        }
    }
</style>
<div class="home-banner-slider mt-lg-3 pt-lg-1 porto-inner-container">
    <div class="container">
        <div class="row">
            <div class="m-b-md col-md-12 col-lg-9">
                <div class="wpb_wrapper vc_column-inner h-100">
                    <div id="banner-slider-demo-13" class="porto-carousel home-banner-slider owl-carousel h-100 mb-0 nav-inside dots-style-1 nav-inside-left">
                        <div class="porto-ultimate-content-box-container h-100">
                            <div
                                class="porto-ultimate-content-box has-content-pos justify-content-center"
                                style="padding: 5rem 0 5rem 5%;
                          background-color: #374654;
                          background-size: cover;
                          background-repeat: no-repeat;
                          background-position: center center;
                          background-color: rgba(0, 0, 0, 0);
                          min-height: 378px;
                          background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/13/shop13_home_slider1.jpg}}');
                          "
                            >
                                <h4 style="font-size: 1.54em; color: rgba(255, 255, 255, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 align-left">Find the Boundaries. Push Through!</h4>
                                <h2 style="font-size: 4.3125em; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading mb-1 custom-font4 align-left heading-light">Summer Sale</h2>
                                <h3 style="font-size: 7.6em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left heading-light">70% OFF</h3>
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="vc_column_container col-md-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h4 style="font-size: 1.1em; line-height: 1; font-weight: 600;" class="vc_custom_heading mr-3 pull-left p-t-sm ls-n-20 align-left text-uppercase heading-light">Starting At</h4>
                                            <h4 style="font-size: 1.5em; line-height: 1;" class="vc_custom_heading coupon-sale-text d-inline-block mr-2 background-color-secondary align-left heading-light">
                                                <b><sup>$</sup>199<sup>99</sup></b>
                                            </h4>
                                            <div class="btn-container mb-0 d-inline-block"><button class="btn btn-modern btn-md btn-primary">Shop Now!</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="porto-ultimate-content-box-container h-100">
                            <div
                                class="porto-ultimate-content-box has-content-pos justify-content-center"
                                style="padding: 5rem 0 5rem 5%;
                          background-color: #ee3d43;
                          background-size: cover;
                          background-repeat: no-repeat;
                          background-position: center center;
                          background-color: rgba(0, 0, 0, 0);
                          min-height: 378px;
                          background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/13/shop13_home_slider2.jpg}}');
                          "
                            >
                                <h4 style="font-size: 1.6em; color: rgba(255, 255, 255, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 mb-2 align-left">OVER 200 PRODUCTS WITH DISCOUNTS</h4>
                                <h3 style="font-size: 5.5em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left heading-light">GREAT DEALS</h3>
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="vc_column_container col-md-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h4 style="font-size: 1.4em; line-height: 1.5; font-weight: 700;" class="vc_custom_heading mr-2 pull-left align-left text-uppercase heading-light">Starting At</h4>
                                            <h6 style="font-size: 2.6em; line-height: 1;" class="vc_custom_heading pull-left m-r-lg align-left heading-light">
                                                <b><sup>$</sup>299<sup>99</sup></b>
                                            </h6>
                                            <div class="btn-container mb-0 d-inline-block"><button class="btn btn-modern btn-md btn-primary">Get Yours!</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $("#banner-slider-demo-13").owlCarousel({
                                items: 1,
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                dots: true,
                                navRewind: true,
                                animateIn: "fadeIn",
                                animateOut: "fadeOut",
                                loop: false,
                                nav: false,
                            });
                        });
                    </script>
                </div>
            </div>
            <div class="col-md-12 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block37')->toHtml() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="header-top-ads mb-3" style="padding-left: 40px; padding-right: 40px; background-color: #2f3946;">
    <style>
        .header-top-ads {
            padding-top: 25px;
            padding-bottom: 5px;
        }
        @media (min-width: 768px) {
            .header-top-ads {
                text-align: center;
            }
            .header-top-ads .porto-sicon-box {
                display: inline-flex;
                text-align: left;
            }
        }
    </style>
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block38')->toHtml() ?>
</div>
<div class="pt-4 porto-inner-container">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-9">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="tabs m-t-n-sm mb-0 tabs-simple">
                        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active","collapsible":"true"}}'>
                            <div class="data item title" aria-labeledby="tab-label-featured-title" data-role="collapsible" id="tab-label-featured">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#featured" id="tab-label-featured-title">
                                    <span><?= __('Featured Products') ?></span>
                                </a>
                            </div>
                            <div class="data item content" id="featured" data-role="content">
                                {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="9" column_count="3" product_type="3" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                            <div class="data item title" aria-labeledby="tab-label-latest-title" data-role="collapsible" id="tab-label-latest">
                                <a class="data switch" tabindex="-1" data-toggle="switch" href="#latest" id="tab-label-latest-title">
                                    <span><?= __('Latest Products') ?></span>
                                </a>
                            </div>
                            <div class="data item content" id="latest" data-role="content">
                                {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" product_count="9" column_count="3" product_type="3" aspect_ratio="0" image_width="350" image_height="350"
                                template="grid.phtml"}}
                            </div>
                        </div>
                    </div>
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block39')->toHtml() ?>
                    <div class="row py-3">
                        <div class="col-md-12 col-lg-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_top_rated_products">
                                        <h2 class="widgettitle"><?= __('Top Rated Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_products">
                                        <h2 class="widgettitle"><?= __('Best Selling Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\BestsellersList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-4">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_content_element">
                                    <div class="widget widget_products">
                                        <h2 class="widgettitle"><?= __('Latest Products') ?></h2>
                                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-3">
                <style>
                    .widget_product_categories {
                        border: 1px solid #e7e7e7;
                    }
                    .widget_product_categories .widget-title {
                        background: #f6f7f9;
                        font-size: 0.875rem;
                        font-weight: 700;
                        letter-spacing: -0.025em;
                        padding: 1rem 1.25rem;
                        margin: 0;
                    }
                    .widget_product_categories .category-sidebar {
                        padding-left: 1.25rem;
                        padding-right: 1.25rem;
                    }
                    .widget_product_categories .category-sidebar li > .expand-icon {
                        color: #222529;
                    }
                    .widget_product_categories .category-sidebar li:hover {
                        color: #282d3b;
                    }
                </style>
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_widgetised_column wpb_content_element sidebar-content">
                        <div class="wpb_wrapper">
                            <div class="widget widget_product_categories">
                                <h3 class="widget-title"><?= __('Browse Categories')?></h3>
                                {{block class="Smartwave\Porto\Block\CategoryCollection" name="category_sidebar" template="Smartwave_Porto::category_side.phtml"}}
                            </div>
                            <div class="widget widget-block">
                                <div class="porto-block">
                                    <style>
                                        .info-box-small-wrap {
                                            padding: 0 30px 10px;
                                        }
                                        .info-box-small-wrap .porto-sicon-top {
                                            position: relative;
                                            padding-top: 25px;
                                        }
                                        .info-box-small-wrap .porto-sicon-top:before {
                                            content: "";
                                            position: absolute;
                                            top: 0;
                                            height: 25px;
                                            left: 50%;
                                            border-left: 1px solid #e7e7e7;
                                        }
                                        .info-box-small-wrap .porto-sicon-header .porto-sicon-title {
                                            font-family: "Open Sans";
                                            position: relative;
                                            display: inline-block;
                                        }
                                        .info-box-small-wrap .porto-sicon-title sup {
                                            font-weight: 600;
                                            font-size: 60%;
                                        }
                                        .info-box-small-wrap .porto-sicon-title sub {
                                            font-family: "Oswald";
                                            font-size: 20px;
                                            text-transform: uppercase;
                                            font-weight: 400;
                                            position: absolute;
                                            right: 4px;
                                            bottom: 3px;
                                            line-height: 1.4em;
                                        }
                                        .porto-sicon-read span {
                                            display: none;
                                        }
                                        .wpb_wrapper .porto-sicon-read {
                                            display: block;
                                            text-decoration: none !important;
                                            font-size: 0.8125rem;
                                            font-weight: 700;
                                            color: #fff !important;
                                            background: #282d3b;
                                            padding: 0.75em 2.25em;
                                            margin-top: 1rem;
                                            width: fit-content;
                                            margin-left: auto;
                                            margin-right: auto;
                                        }
                                        .info-box-small-wrap .porto-sicon-box {
                                            margin-bottom: 0.5rem;
                                        }
                                    </style>
                                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block40')->toHtml() ?>
                                    <script type="text/javascript">
                                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                            $(".info-box-small-wrap .owl-carousel").owlCarousel({
                                                items: 1,
                                                autoplay: false,
                                                autoplayTimeout: 5000,
                                                autoplayHoverPause: true,
                                                dots: true,
                                                nav: false,
                                                loop: false,
                                                navRewind: true,
                                                margin: 1,
                                            });
                                        });
                                    </script>
                                </div>
                            </div>
                            <div class="widget widget_text">
                                <div class="box-newsletter text-center">
                                    <div class="box-content pb-3 px-4">
                                        <h4 class="widget-title"><?= __('Subscribe Newsletter')?></h4>
                                        <div class="content-form">
                                            <p style="font-size: 0.8125rem;"><?= __('Get all the latest information on Events, Sales and Offers.')?></p>
                                            {{block class="Magento\Newsletter\Block\Subscribe" name="home.newsletter" template="subscribe_form.phtml"}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
