<style>
    .cms-index-index.layout-1220 .page-main {
        max-width: 100%;
    }
    .columns .column.main {
        padding: 0;
    }
    .porto-u-heading .porto-u-main-heading h1,
    .porto-u-heading .porto-u-main-heading h2,
    .porto-u-heading .porto-u-main-heading h3,
    .porto-u-heading .porto-u-main-heading h4,
    .porto-u-heading .porto-u-main-heading h5,
    .porto-u-heading .porto-u-main-heading h6 {
        margin: 0;
        padding: 0;
    }
    .wpb_single_image.vc_align_center {
        text-align: center;
    }
    .wpb_single_image .vc_single_image-wrapper {
        display: inline-block;
        vertical-align: top;
        max-width: 100%;
    }
    .home-slider {
        position: relative;
    }
    .home-slider:before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 61%;
        display: block;
        background: #f7f6f7;
    }
    .home-slider .btn,
    .porto-ultimate-content-box .btn {
        padding: 1.125em 4em;
    }
    .home-slider .pl-lg-5 {
        justify-content: center;
    }
    .home-slider .pl-lg-5 > .vc_column-inner {
        width: auto;
        flex: 0 0 auto !important;
    }
    .home-slider .slash-bg {
        background-position: left center !important;
    }
    .home-slider .vc_custom_heading b {
        display: inline-block;
        color: #b35827;
        font-size: 2em;
        position: relative;
        top: 0.08em;
        line-height: 1;
        vertical-align: middle;
    }
    .home-slider .vc_custom_heading b small {
        font-size: 50%;
        line-height: 1.6;
        vertical-align: top;
        font-weight: inherit;
    }
    @media (min-width: 576px) {
        .pull-sm-left {
            float: left;
        }
    }
</style>
<div class="home-slider porto-inner-container" style="margin-bottom: 35px; border-bottom: 1px solid #e7e7e7;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div id="banner-slider-demo-26" class="porto-carousel home-banner-slider owl-carousel mb-0 nav-pos-outside nav-style-4">
                        <div class="row no-padding">
                            <div class="py-5 pl-lg-5 col-md-12 col-lg-4 d-flex align-items-center">
                                <div class="wpb_wrapper vc_column-inner d-flex flex-column justify-content-center">
                                    <p style="font-size: 34px; color: #999999; line-height: 1; font-weight: 500;" class="vc_custom_heading mb-1 align-left text-uppercase">EXTRA</p>
                                    <h3 style="font-size: 69px; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-1 align-left text-uppercase">20% OFF</h3>
                                    <div class="vc_custom_heading mb-3 heading heading-border heading-dark heading-middle-border heading-middle-border-center heading-border-xl">
                                        <h3 style="font-size: 34px; line-height: 1; text-align: center; font-weight: 700; border-color: #222529;" class="heading-tag text-uppercase">BIKES</h3>
                                    </div>
                                    <h3 style="font-size: 39px; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading pb-4 mb-4 mb-lg-5 custom-font4 align-left">Summer Sale</h3>
                                    <div class="btn-container mb-0 d-inline"><button class="btn btn-xl btn-dark">SHOP ALL SALE</button></div>
                                </div>
                            </div>
                            <div
                                class="text-center text-lg-left pt-0 pt-lg-5 pb-5 slash-bg col-md-12 col-lg-8"
                                style="padding-left: 5%;
                          background: rgba(255, 255, 255, 0) url({{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_slide_bg.png}});
                          background-position: center;
                          background-repeat: no-repeat;
                          background-size: cover;"
                            >
                                <div class="wpb_wrapper vc_column-inner">
                                    <div class="wpb_single_image wpb_content_element vc_align_left mb-5 text-center text-lg-left">
                                        <div class="wpb_wrapper">
                                            <div class="vc_single_image-wrapper vc_box_border_grey">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_slide1.png}}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="porto-ultimate-content-box-container mb-0">
                                        <div class="porto-ultimate-content-box">
                                            <h3 style="font-size: 18px; font-weight: 700;" class="vc_custom_heading mb-2 pull-sm-left mx-sm-5 align-left heading-dark">
                                                ONLY <b><small>$</small>399<small>99</small></b>
                                            </h3>
                                            <div class="porto-u-heading mb-0 pl-lg-4 pull-sm-left">
                                                <div class="porto-u-main-heading">
                                                    <h2 style="font-weight: 500; font-size: 16px; line-height: 16px;">Start Shopping Right Now</h2>
                                                </div>
                                                <div class="porto-u-sub-heading" style="font-size: 11px;">* Get Plus Discount Buying Package</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row no-padding">
                            <div class="py-5 pl-lg-5 order-lg-2 col-md-12 col-lg-5 d-flex align-items-center">
                                <div class="wpb_wrapper vc_column-inner">
                                    <p style="font-size: 34px; color: #999999; line-height: 1; font-weight: 500;" class="vc_custom_heading mb-1 align-left text-uppercase">EXTRA</p>
                                    <h3 style="font-size: 69px; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-1 align-left text-uppercase">20% OFF</h3>
                                    <div class="vc_custom_heading mb-3 heading heading-border heading-dark heading-middle-border heading-middle-border-center heading-border-xl">
                                        <h3 style="font-size: 34px; line-height: 1; text-align: center; font-weight: 700; border-color: #222529;" class="heading-tag text-uppercase">BIKES</h3>
                                    </div>
                                    <h3 style="font-size: 39px; line-height: 1; font-weight: 700;" class="vc_custom_heading pb-4 mb-4 mb-lg-5 custom-font4 align-left">Summer Sale</h3>
                                    <div class="btn-container mb-0 d-inline-block"><button class="btn btn-xl btn-dark">SHOP ALL SALE</button></div>
                                </div>
                            </div>
                            <div class="pt-lg-5 pb-5 col-md-12 col-lg-7" style="padding-left: 5%;">
                                <div class="wpb_wrapper vc_column-inner">
                                    <div class="wpb_single_image wpb_content_element vc_align_left mb-5 text-center text-lg-right">
                                        <div class="wpb_wrapper">
                                            <div class="vc_single_image-wrapper vc_box_border_grey">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_slide2.png}}" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $("#banner-slider-demo-26").owlCarousel({
                                items: 1,
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                dots: false,
                                navRewind: true,
                                animateIn: "fadeIn",
                                animateOut: "fadeOut",
                                loop: false,
                                nav: true,
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="porto-inner-container">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div id="popular-products" class="porto-products wpb_content_element">
                        <h2 class="section-title text-center slider-title"><span class="inline-title">Most Popular Products</span><span class="line"></span></h2>
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="popular_product" extra_class="dots-style-1" product_count="7" product_type="1" aspect_ratio="0" image_width="350" image_height="350"
                            template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#popular-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <style>
                        .bg-gray {
                            background: #f4f4f4;
                        }
                        .bg-gray .porto-sicon-box {
                            background: #fff;
                            margin: 2px 0;
                            padding: 10px;
                            display: flex;
                            align-items: center;
                            justify-content: center;
                        }
                    </style>
                    <div class="sicon-carousel porto-carousel owl-carousel bg-gray m-b-xl">
                        <a class="porto-sicon-box-link" href="#">
                            <div class="porto-sicon-box style_1 default-icon">
                                <div class="porto-sicon-default">
                                    <div class="porto-just-icon-wrapper" style="text-align: center;">
                                        <div class="porto-sicon-img" style="display: inline-block; font-size: 60px;">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_icon1.png}}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="porto-sicon-header"><h3 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 20px;">BIKE SADDLES</h3></div>
                            </div>
                        </a>
                        <a class="porto-sicon-box-link" href="#">
                            <div class="porto-sicon-box style_1 default-icon">
                                <div class="porto-sicon-default">
                                    <div class="porto-just-icon-wrapper" style="text-align: center;">
                                        <div class="porto-sicon-img" style="display: inline-block; font-size: 60px;">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_icon2.png}}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="porto-sicon-header"><h3 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 20px;">BIKE PEDALS</h3></div>
                            </div>
                        </a>
                        <a class="porto-sicon-box-link" href="#">
                            <div class="porto-sicon-box style_1 default-icon">
                                <div class="porto-sicon-default">
                                    <div class="porto-just-icon-wrapper" style="text-align: center;">
                                        <div class="porto-sicon-img" style="display: inline-block; font-size: 60px;">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_icon3.png}}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="porto-sicon-header"><h3 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 20px;">BIKE FRAMES</h3></div>
                            </div>
                        </a>
                        <a class="porto-sicon-box-link" href="#">
                            <div class="porto-sicon-box style_1 default-icon">
                                <div class="porto-sicon-default">
                                    <div class="porto-just-icon-wrapper" style="text-align: center;">
                                        <div class="porto-sicon-img" style="display: inline-block; font-size: 60px;">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_icon4.png}}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="porto-sicon-header"><h3 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 20px;">BIKE CHAINS</h3></div>
                            </div>
                        </a>
                        <a class="porto-sicon-box-link" href="#">
                            <div class="porto-sicon-box style_1 default-icon">
                                <div class="porto-sicon-default">
                                    <div class="porto-just-icon-wrapper" style="text-align: center;">
                                        <div class="porto-sicon-img" style="display: inline-block; font-size: 60px;">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_icon5.png}}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="porto-sicon-header"><h3 class="porto-sicon-title" style="font-weight: 700; font-size: 16px; line-height: 20px;">BIKE TOOLS</h3></div>
                            </div>
                        </a>
                    </div>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".sicon-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: true,
                                navRewind: true,
                                lazyLoad: true,
                                stagePadding: 2,
                                margin: 2,
                                nav: false,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 2,
                                    },
                                    768: {
                                        items: 2,
                                    },
                                    992: {
                                        items: 3,
                                    },
                                    1200: {
                                        items: 5,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    body .row.column-gap-10 > .column_container {
        padding: 5px;
    }
    .h-100 > .porto-ultimate-content-box {
        height: 100%;
        font-size: 0.6666vw;
    }
    .h-100 > .porto-ultimate-content-box > * {
        vertical-align: middle;
    }
    @media (max-width: 991px) {
        .h-100 > .porto-ultimate-content-box .btn {
            font-size: 10px;
        }
    }
    @media (max-width: 767px) {
        .h-100 > .porto-ultimate-content-box {
            min-height: 50vw;
            font-size: 1vw;
        }
    }
</style>
<div class="row m-b-xl column-gap-10" style="margin-left: -5px; margin-right: -5px; padding-right: 0px; padding-left: 0px;">
    <div class="column_container col-md-4">
        <div class="wpb_wrapper vc_column-inner">
            <div class="wpb_single_image wpb_content_element vc_align_center mb-0">
                <div class="wpb_wrapper">
                    <div class="vc_single_image-wrapper vc_box_border_grey">
                        <img class="d-block" src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_banner1.jpg}}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="column_container col-md-8">
        <div class="wpb_wrapper vc_column-inner h-100">
            <div class="porto-ultimate-content-box-container h-100">
                <div
                    class="porto-ultimate-content-box"
                    style="padding-top: 2.5%;
                    background-size: cover;
                    background-repeat: no-repeat;
                    background-position: center center;
                    background-color: rgba(0, 0, 0, 0);
                    background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_banner2.jpg}}');
                    "
                >
                    <h3 style="font-size: 2.1875em; color: rgb(153, 153, 153); line-height: 1; margin-left: 37%;" class="vc_custom_heading mb-0 align-left">
                        GET READY
                    </h3>
                    <h2 style="font-size: 4.5em; line-height: 1; font-weight: 700; margin-left: 42%;" class="vc_custom_heading mb-2 mb-lg-3 mr-3 mr-lg-4 d-inline-block align-left text-uppercase heading-dark">
                        20% OFF
                    </h2>
                    <div class="btn-container mb-2 mb-lg-3 d-none d-sm-inline-block d-inline-block">
                        <button class="btn btn-md btn-dark">
                            SHOP ALL SALE
                        </button>
                    </div>
                    <div class="vc_custom_heading align-left heading heading-border heading-dark heading-middle-border heading-middle-border-center heading-border-xl">
                        <h2 style="font-size: 2.65em; line-height: 1; font-weight: 700; margin-right: 22%; margin-left: 46%; border-color: #222529;" class="heading-tag heading-dark text-uppercase">
                            BIKES
                        </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="porto-inner-container">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div id="trending-products" class="porto-products wpb_content_element">
                        <h2 class="section-title text-center slider-title"><span class="inline-title">Trending Accessories</span><span class="line"></span></h2>
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="popular_product" extra_class="dots-style-1" product_count="7" product_type="1" aspect_ratio="0" image_width="350" image_height="350"
                            template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#trending-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 2,
                                            },
                                            992: {
                                                items: 3,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row text-center" style="margin-bottom: 40px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xl-6">
                <div class="wpb_wrapper vc_column-inner h-100">
                    <div class="row py-4 py-sm-3 h-100" style="margin-right: 0px; margin-left: 0px; background-color: #f4f4f4;">
                        <div class="col-sm-4 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <h3 style="font-size: 27.5px; line-height: 1; text-align: center; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading custom-font4 mb-0 heading-dark">Summer Sale</h3>
                                <h2 style="font-size: 49px; line-height: 1; text-align: center; font-weight: 700;" class="vc_custom_heading mb-0 text-uppercase heading-dark">20% OFF</h2>
                            </div>
                        </div>
                        <div class="col-sm-4 py-3 py-sm-0 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_single_image wpb_content_element vc_align_center mb-0">
                                    <div class="wpb_wrapper">
                                        <div class="vc_single_image-wrapper vc_box_border_grey">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_banner3.jpg}}" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="btn-container mb-0 d-inline-block"><button class="btn btn-lg btn-dark">SHOP ALL SALE</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-xl-6">
                <div class="wpb_wrapper vc_column-inner h-100">
                    <div class="row py-4 py-sm-3 h-100" style="margin-right: 0px; margin-left: 0px; background-color: #4db7b3;">
                        <div class="col-sm-4 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <h3 style="font-size: 35px; line-height: 1; text-align: center; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading custom-font4 mb-0 heading-light">Flash Sale</h3>
                                <h2 style="font-size: 49px; line-height: 1; text-align: center; font-weight: 700;" class="vc_custom_heading mb-0 text-uppercase heading-light">30% OFF</h2>
                            </div>
                        </div>
                        <div class="col-sm-4 py-3 py-sm-0 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="wpb_single_image wpb_content_element vc_align_center mb-0">
                                    <div class="wpb_wrapper">
                                        <div class="vc_single_image-wrapper vc_box_border_grey">
                                            <img src="{{media url=wysiwyg/smartwave/porto/homepage/26/shop26_home_banner4.jpg}}" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-4 d-flex align-items-center justify-content-center">
                            <div class="wpb_wrapper vc_column-inner">
                                <div class="btn-container mb-0 d-inline-block"><button class="btn btn-lg btn-light">SHOP ALL SALE</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
