<div id="banner-slider-demo-4" class="porto-carousel home-banner-slider owl-carousel m-b-none home-banner-slider nav-pos-inside nav-style-4 show-nav-hover">
    <div class="porto-ultimate-content-box-container">
        <div
            class="porto-ultimate-content-box has-content-pos justify-content-center"
            style="background-color: #f4f4f4
                background-size: cover;
                background-repeat: no-repeat;
                background-position: center center;
                background-color: rgba(0, 0, 0, 0);
                min-height: 499px;
                background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/04/shop4_home_slider1.jpg}}');"
        >
            <div class="porto-container container first-banner">
                <h3 style="font-size: 1.9em; color: rgba(34, 37, 41, 0.7); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-80 mb-3 align-left">Find the Boundaries. Push Through!</h3>
                <h2 style="font-size: 5.3em; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading mb-0 align-left">Summer Sale</h2>
                <h3 style="font-size: 9.4em; line-height: 1;" class="vc_custom_heading mb-3 align-left">70% OFF</h3>
                <div class="row">
                    <div class="col-md-12">
                        <div class="wpb_wrapper vc_column-inner">
                            <h4 style="font-size: 1.2em; line-height: 1;" class="vc_custom_heading mr-3 pull-left p-t-sm ls-n-20 align-left text-uppercase">Starting At</h4>
                            <h4 style="font-size: 1.8em; line-height: 1;" class="vc_custom_heading coupon-sale-text d-inline-block mr-2 align-left">
                                <b><sup>$</sup>199<sup>99</sup></b>
                            </h4>
                            <div class="btn-container mb-0 d-inline-block" style="margin-left: -2px;"><button class="btn btn-modern btn-lg btn-dark">Shop Now!</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="porto-ultimate-content-box-container">
        <div
            class="porto-ultimate-content-box has-content-pos justify-content-center"
            style="background-color: #f4f4f4
                background-size: cover;
                background-repeat: no-repeat;
                background-position: center center;
                background-color: rgba(0, 0, 0, 0);
                min-height: 499px;
                background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/04/shop4_home_slider2.jpg}}');
                "
        >
            <div class="porto-container container d-flex justify-content-end">
                <div class="row justify-content-center col-8 col-md-7 col-lg-6">
                    <div class="col-auto col-md-12">
                        <div class="wpb_wrapper vc_column-inner">
                            <h4 style="font-size: 3.4em; color: #999999; line-height: 1; font-weight: 500;" class="vc_custom_heading mb-1 align-left">EXTRA</h4>
                            <h3 style="font-size: 6.9em; line-height: 1;" class="vc_custom_heading mb-2 align-left">20% OFF</h3>
                            <div class="vc_custom_heading mb-3 align-left heading heading-border heading-dark heading-middle-border heading-middle-border-center heading-border-xl">
                                <h4 style="font-size: 3.4em; line-height: 1;" class="heading-tag">ACCESSORIES</h4>
                            </div>
                            <h2 style="font-size: 4em; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading mb-4 align-left">Summer Sale</h2>
                            <div class="btn-container ls-150 mb-0 text-center"><button class="d-block btn btn-modern btn-xl btn-dark" style="letter-spacing: 0.15em; width: 100%;">SHOP ALL SALE</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .columns .column.main {
        padding-bottom: 0;
    }
    .home-banner-slider .container.first-banner > * {
        padding-left: 8% !important;
        padding-right: 40% !important;
    }
    @media (max-width: 991px) {
        .home-banner-slider .container.first-banner > * {
            padding-left: 0 !important;
        }
    }
    @media (max-width: 575px) {
        .home-banner-slider .container.first-banner > * {
            padding-right: 0 !important;
        }
    }
    .coupon-sale-text {
        transform: rotate(-2deg);
        letter-spacing: -0.01em;
        position: relative;
    }
    .coupon-sale-text b {
        display: inline-block;
        font-size: 1.6em;
        font-weight: 700;
        padding: 5px 8px;
        background-color: #ff7272;
        color: #fff;
    }
    .coupon-sale-text sup {
        font-size: 50%;
        top: -0.5em;
    }
    .coupon-sale-light-bg b {
        background: #fff;
        color: #222529;
    }
    .coupon-sale-text i {
        font-style: normal;
        position: absolute;
        left: -2.25em;
        top: 50%;
        transform: translateY(-50%) rotate(-90deg);
        font-size: 0.65em;
        opacity: 0.6;
        letter-spacing: 0;
    }
    html .heading.heading-dark .heading-tag {
        border-color: #222529;
    }
    .heading.heading-border.heading-border-xl .heading-tag:before,
    .heading.heading-border.heading-border-xl .heading-tag:after {
        border-top-width: 7px;
        margin-top: -3px;
    }
    .heading.heading-border.heading-border-xl .heading-tag:before,
    .heading.heading-border.heading-border-xl .heading-tag:after {
        border-top-width: 7px;
        margin-top: -3px;
    }
    .row-center .row {
        justify-content: center;
    }
    .post-item .read-more {
        display: none;
    }
</style>
<script type="text/javascript">
    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
        var banner_owl = $("#banner-slider-demo-4");
        banner_owl.owlCarousel({
            items: 1,
            autoplay: false,
            autoplayTimeout: 5000,
            autoplayHoverPause: true,
            dots: false,
            nav: true,
            navRewind: true,
            animateIn: "fadeIn",
            animateOut: "fadeOut",
            loop: true,
            lazyLoad: true,
        });
    });
</script>
<div class="home-bar no-padding porto-inner-container" style="margin-top: 20px; margin-bottom: 20px;">
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block1')->toHtml() ?>
    <style>
        .home-bar .porto-sicon-box {
            justify-content: center;
            padding: 1rem 0;
            margin: 0;
            border-right: 1px solid #e7e7e7;
            margin-right: -2px;
        }
    </style>
    <script type="text/javascript">
        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
            $(".home-bar .owl-carousel").owlCarousel({
                autoplay: false,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                loop: false,
                navRewind: true,
                lazyLoad: true,
                margin: 0,
                nav: false,
                dots: false,
                responsive: {
                    0: {
                        items: 1,
                    },
                    640: {
                        items: 3,
                    },
                    768: {
                        items: 3,
                    },
                    992: {
                        items: 3,
                    },
                    1200: {
                        items: 3,
                    },
                },
            });
        });
    </script>
</div>
<div class="home-ads porto-inner-container">
    <style>
        .home-ads .porto-ultimate-content-box {
            will-change: box-shadow;
            box-shadow: none;
        }
        .home-ads .porto-ultimate-content-box:hover {
            box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.1);
        }
    </style>
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block14')->toHtml() ?>
</div>
<div class="pt-5" style="background-color: #fbfbfb;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="featured-products" class="porto-products title-border-middle mb-3">
                    <h2 class="section-title slider-title text-center">
                        <span class="line-l"></span>
                        <span class="inline-title"><?= __('Featured Products') ?></span>
                        <span class="line-r"></span>
                    </h2>
                    <div class="slider-wrapper">
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="8" aspect_ratio="0"
                        image_width="350" image_height="350" template="owl_list.phtml"}}
                        <script type="text/javascript">
                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                $("#featured-products .owl-carousel").owlCarousel({
                                    autoplay: false,
                                    autoplayTimeout: 5000,
                                    autoplayHoverPause: true,
                                    loop: true,
                                    navRewind: true,
                                    lazyLoad: true,
                                    margin: 0,
                                    nav: true,
                                    dots: false,
                                    responsive: {
                                        0: {
                                            items: 2,
                                        },
                                        640: {
                                            items: 3,
                                        },
                                        768: {
                                            items: 3,
                                        },
                                        992: {
                                            items: 4,
                                        },
                                        1200: {
                                            items: 4,
                                        },
                                    },
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="latest-products" class="porto-products title-border-middle mb-3">
                    <h2 class="section-title slider-title text-center">
                        <span class="line-l"></span>
                        <span class="inline-title"><?= __('NEW ARRIVALS') ?></span>
                        <span class="line-r"></span>
                    </h2>
                    <div class="slider-wrapper">
                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="nav-center-images-only nav-pos-outside nav-style-4 show-nav-hover dots-style-1" product_count="8" aspect_ratio="0"
                        image_width="350" image_height="350" template="owl_list.phtml"}}
                        <script type="text/javascript">
                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                $("#latest-products .owl-carousel").owlCarousel({
                                    autoplay: false,
                                    autoplayTimeout: 5000,
                                    autoplayHoverPause: true,
                                    loop: true,
                                    navRewind: true,
                                    lazyLoad: true,
                                    margin: 0,
                                    nav: true,
                                    dots: false,
                                    responsive: {
                                        0: {
                                            items: 2,
                                        },
                                        640: {
                                            items: 2,
                                        },
                                        768: {
                                            items: 3,
                                        },
                                        992: {
                                            items: 4,
                                        },
                                        1200: {
                                            items: 5,
                                        },
                                    },
                                });
                            });
                        </script>
                    </div>
                </div>
                <div
                    class="row py-3 mb-5 align-items-center"
                    style="margin-right: 0;
                    margin-left: 0;
                    background-image: url('{{media url=wysiwyg/smartwave/porto/homepage/04/shop4_home_banner.jpg}}');
                    background-position: center;
                    background-repeat: no-repeat;
                    background-size: cover;
                    "
                >
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block15')->toHtml() ?>
                    <style>
                        .home-banner {
                            letter-spacing: -0.02em;
                        }
                        .home-banner strong {
                            position: relative;
                            z-index: 1;
                            display: inline-block;
                            padding: 0.4em 0.6em;
                            margin-right: 0.5em;
                        }
                        .home-banner strong:before {
                            content: "";
                            display: block;
                            background-color: #222529;
                            display: block;
                            position: absolute;
                            left: 0;
                            right: 0;
                            top: 0;
                            bottom: 0;
                            transform: rotate(-2deg);
                            z-index: -1;
                        }
                        .home-banner small {
                            font-size: 64%;
                            font-weight: 400;
                            opacity: 0.7;
                            vertical-align: middle;
                            margin-left: 0.8em;
                            color: inherit;
                        }
                    </style>
                </div>
                <div id="category-products" class="porto-products title-border-middle mb-3">
                    <style>
                        ul.products li.product-category .thumb-info h3 {
                            letter-spacing: 0;
                            font-family: Poppins;
                            text-transform: uppercase;
                        }
                        ul.category-color-dark li.product-category .thumb-info-title {
                            background: #fff;
                            padding: 0.75rem 0.5rem 1.25rem;
                        }
                        ul.products li.product-category .thumb-info-wrapper:after {
                            background: rgba(27, 27, 23, 0);
                        }
                        li.product-category .thumb-info,
                        li.product-category .thumb-info img,
                        li.product-category .thumb-info-wrapper:after {
                            border-radius: 50%;
                        }
                    </style>
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block16')->toHtml() ?>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $("#category-products .owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: true,
                                navRewind: true,
                                lazyLoad: true,
                                margin: 0,
                                nav: true,
                                dots: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 3,
                                    },
                                    768: {
                                        items: 3,
                                    },
                                    992: {
                                        items: 4,
                                    },
                                    1200: {
                                        items: 5,
                                    },
                                },
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt-5 pb-4" style="background-color: #f6f7f9;">
    <style>
        .top-icon .porto-sicon-header p {
            font-family: Poppins;
        }
    </style>
    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block17')->toHtml() ?>
</div>
<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block18')->toHtml() ?>
<div class="porto-inner-container" style="padding: 50px 0;">
    <div class="container">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block10')->toHtml() ?>
        <script type="text/javascript">
            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                $(".brand-carousel.owl-carousel").owlCarousel({
                    autoplay: false,
                    autoplayTimeout: 5000,
                    autoplayHoverPause: true,
                    loop: false,
                    navRewind: true,
                    lazyLoad: true,
                    margin: 0,
                    nav: false,
                    dots: false,
                    responsive: {
                        0: {
                            items: 2,
                        },
                        640: {
                            items: 3,
                        },
                        768: {
                            items: 3,
                        },
                        992: {
                            items: 4,
                        },
                        1200: {
                            items: 6,
                        },
                    },
                });
            });
        </script>
        <div class="porto-separator mt-5 mb-5"><hr class="separator-line align_center solid" /></div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element">
                        <div class="widget widget_products">
                            <h2 class="widgettitle"><?= __('Featured Products') ?></h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element">
                        <div class="widget widget_products">
                            <h2 class="widgettitle"><?= __('Best Selling Products') ?></h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\BestsellersList" name="bestsellers_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element">
                        <div class="widget widget_products">
                            <h2 class="widgettitle"><?= __('Lateset Products') ?></h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element">
                        <div class="widget widget_products">
                            <h2 class="widgettitle"><?= __('Top Rated Products') ?></h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="toprate_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>