<style>
    .columns .column.main {
        padding-bottom: 0;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .home-banner ul.products li.product-category .thumb-info {
        min-height: 3.375rem;
        background: #222529;
    }
    .porto-ibanner .porto-ibanner-desc .porto-ibanner-container {
        position: relative;
        height: 100%;
    }
    ul.products li.product-category .thumb-info h3 {
        text-transform: uppercase;
    }
    .coupon-sale-text {
        padding: 0.2em 0.4em;
        position: relative;
        letter-spacing: 0;
        transform: rotate(-1.5deg);
    }
    .coupon-sale-text b {
        display: inline-block;
        font-size: 1em;
        padding: 0;
    }
    .coupon-sale-text b sup {
        font-size: 54%;
    }
    .coupon-sale-text b sup {
        font-size: 54%;
    }
    .p-t {
        padding-top: 15px !important;
    }
    ul.products .product-col {
        margin-bottom: 1.4286em;
        position: relative;
    }
    sup {
        font-size: 54%;
    }
    @media (max-width: 575px) {
        .porto-ibanner-layer {
            font-size: 0.6rem;
        }
    }
</style>
<div class="row home-banner no-padding">
    <div class="col-md-12">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-ibanner mb-0" style="background: #f4f4f4; min-height: 100vh;">
                <img src="{{media url=wysiwyg/smartwave/porto/homepage/12/shop12_home_banner1.jpg}}" />
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="container">
                        <div class="porto-ibanner-container">
                            <div class="porto-ibanner-layer" style="left: 10%; top: 50%; transform: translateY(-50%);">
                                <h4 style="font-size: 1.4375em; color: rgba(34, 37, 41, 0.7); line-height: 1; font-weight: 500; letter-spacing: 0.08em;" class="vc_custom_heading mb-3 align-left">Find the Boundaries. Push Through!</h4>
                                <h2 style="font-size: 4.0625em; line-height: 1; font-weight: 700; letter-spacing: 0.005em;" class="vc_custom_heading mb-0 custom-font4 align-left">Summer Sale</h2>
                                <h3 style="font-size: 7.125em; line-height: 1; font-weight: 700;" class="vc_custom_heading mb-3 align-left">70% OFF</h3>
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="vc_column_container col-md-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h4 style="font-size: 1em; line-height: 1; letter-spacing: -0.02em;" class="vc_custom_heading mr-3 pull-left p-t align-left text-uppercase">Starting At</h4>
                                            <h4 style="font-size: 2em; line-height: 1;" class="vc_custom_heading coupon-sale-text d-inline-block mr-3 background-color-secondary align-left heading-light">
                                                <b><sup>$</sup>199<sup>99</sup></b>
                                            </h4>
                                            <div class="btn-container mb-0 d-inline-block" style="margin-left: -0.8%;"><button class="btn btn-modern btn-xl btn-dark">Shop Now!</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="porto-ibanner-layer" style="width: 100%; left: 0%; bottom: 5%;">
                                <div class="category-slider porto-products wpb_content_element mb-0 hide-count">
                                    <div class="slider-wrapper">
                                        <ul class="products products-container products-slider owl-carousel category-pos-middle category-text-center">
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Fashion</h3>
                                                                <span class="thumb-info-type"> <mark class="count">4</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Headphone</h3>
                                                                <span class="thumb-info-type"> <mark class="count">1</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Shoes</h3>
                                                                <span class="thumb-info-type"> <mark class="count">2</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Toys</h3>
                                                                <span class="thumb-info-type"> <mark class="count">1</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Trousers</h3>
                                                                <span class="thumb-info-type"> <mark class="count">1</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Watches</h3>
                                                                <span class="thumb-info-type"> <mark class="count">2</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Accessories</h3>
                                                                <span class="thumb-info-type"> <mark class="count">6</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Caps</h3>
                                                                <span class="thumb-info-type"> <mark class="count">1</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Dress</h3>
                                                                <span class="thumb-info-type"> <mark class="count">3</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="product-category product-col">
                                                <a href="#">
                                                    <span class="thumb-info align-center">
                                                        <span class="thumb-info-wrap">
                                                            <span class="thumb-info-title">
                                                                <h3 class="sub-title thumb-info-inner">Electronics</h3>
                                                                <span class="thumb-info-type"> <mark class="count">3</mark> Products </span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                        <script type="text/javascript">
                                            require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                                $(".category-slider .owl-carousel").owlCarousel({
                                                    autoplay: false,
                                                    autoplayTimeout: 5000,
                                                    autoplayHoverPause: true,
                                                    loop: true,
                                                    navRewind: true,
                                                    lazyLoad: true,
                                                    margin: 0,
                                                    nav: false,
                                                    dots: false,
                                                    responsive: {
                                                        0: {
                                                            items: 2,
                                                        },
                                                        640: {
                                                            items: 2,
                                                        },
                                                        768: {
                                                            items: 3,
                                                        },
                                                        992: {
                                                            items: 4,
                                                        },
                                                        1200: {
                                                            items: 6,
                                                        },
                                                    },
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-0 home-banners no-padding">
    <div class="col-md-12" style="padding: 0.375rem 0.375rem 0 0.375rem;">
        <div class="wpb_wrapper vc_column-inner">
            <div class="porto-grid-container">
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block36')->toHtml() ?>
                <style scope="scope">
                    .container .container {
                        width: 100%;
                        padding-left: 0;
                        padding-right: 0;
                    }
                    .porto-banner-layout {
                        opacity: 0;
                    }
                    .home-banners {
                        font-size: 0.83333vw;
                    }
                    @media (max-width: 767px) {
                        .home-banners {
                            font-size: 2vw;
                        }
                    }
                    .home-banners .porto-ibanner-layer {
                        font-size: inherit;
                    }
                    .porto-grid-container .porto-grid-item {
                        float: left;
                        max-width: 100%;
                    }
                    .home-banners .porto-ibanner > img {
                        position: absolute;
                        min-height: auto;
                        height: 100%;
                        left: 0;
                        top: 0;
                    }
                    .porto-ultimate-content-box {
                        font-size: inherit;
                    }
                    .bg-gray {
                        background-color: #e8e3e1;
                    }
                    .coupon-sale-text.heading-dark i,
                    .coupon-sale-text.heading-dark sub {
                        color: #fff;
                    }
                    .coupon-sale-text.heading-light i,
                    .coupon-sale-text.heading-light sub {
                        color: #222529;
                    }
                    .coupon-sale-text i {
                        font-style: normal;
                        position: absolute;
                        left: -2.25em;
                        top: 50%;
                        transform: translateY(-50%) rotate(-90deg);
                        font-size: 0.4em;
                        opacity: 0.6;
                        letter-spacing: 0;
                    }
                    .coupon-sale-text sub {
                        position: absolute;
                        left: 100%;
                        margin-left: 0.25rem;
                        bottom: 0.3em;
                        font-size: 70%;
                        line-height: 1;
                    }
                    .text-sale small {
                        display: inline-block !important;
                        font-size: 27% !important;
                        word-break: break-all;
                        width: 1em;
                        text-align: center;
                        font-weight: inherit;
                        white-space: normal;
                    }
                    .porto-ultimate-content-box .btn-container {
                        font-size: inherit;
                    }

                    .porto-ibanner .btn-modern.btn-xl {
                        font-size: 1.125em;
                        padding: 1.05em 3.125em;
                    }
                    .porto-ibanner .btn-modern.btn-lg {
                        font-size: 1em;
                        padding: 1em 3em;
                    }
                    .porto-ibanner .btn-modern.btn-md {
                        font-size: 0.8125em;
                        padding: 0.875em 2.25em;
                    }
                    .porto-ibanner .btn-md.vc_btn3-block {
                        padding-top: 1em;
                        padding-bottom: 1em;
                    }
                    .porto-ibanner .btn-sale .btn-modern {
                        padding: 1.375em 4.5em;
                        max-width: 100%;
                    }
                    .porto-ibanner-layer > *:last-child {
                        margin-bottom: 0;
                    }
                    .porto-grid-item .btn-modern.btn-xl {
                        padding: 1.05em 2.25em;
                    }
                    .heading.heading-border .heading-tag {
                        border-top-color: #dbdbdb;
                        border-bottom-color: #dbdbdb;
                    }
                    .porto-ibanner .porto-ibanner-desc {
                        color: inherit;
                    }
                    .home-banners .sale-label {
                        border-radius: 50%;
                        width: 2.25em;
                        height: 2.25em;
                        padding-top: calc(1.125em - 0.5em);
                        letter-spacing: -0.08em;
                        line-height: 1;
                        text-align: center;
                    }
                    .home-banners .sale-label small {
                        letter-spacing: -0.025em;
                        font-size: 70%;
                        display: inline-block;
                        font-weight: inherit;
                    }
                    .home-banners .sale-label sup {
                        position: static;
                        font-size: 75%;
                    }
                    .home-banners .sale-label sub {
                        display: block;
                        font-size: 36%;
                        line-height: 1;
                        position: static;
                        font-weight: 400;
                        letter-spacing: 0;
                        padding-left: 0.1em;
                        letter-spacing: -0.025em;
                        opacity: 0.5;
                    }
                    .fs-875 > .btn {
                        font-size: 0.875em !important;
                    }
                    .brands-section .wpb_single_image img {
                        filter: brightness(0) invert(1);
                        display: block;
                    }
                    #banner-masonry-demo-12 .porto-grid-item {
                        padding: 0.1875em;
                    }
                    #banner-masonry-demo-12 {
                        margin: -0.1875em -0.1875em 0.1875em;
                    }
                    @media (max-width: 767px) {
                        #banner-masonry-demo-12 {
                            height: auto !important;
                        }
                        #banner-masonry-demo-12 .porto-grid-item:first-child {
                            margin-top: 0;
                        }
                        #banner-masonry-demo-12 .porto-grid-item {
                            width: 100% !important;
                            position: static !important;
                            float: none;
                        }
                    }
                </style>
            </div>
            <script type="text/javascript">
                require(["jquery", "packery"], function ($, Packery) {
                    $.bridget("packery", Packery);
                    var $container = $("#banner-masonry-demo-12");
                    $container.css("opacity", 0);
                    if ($container.length > 0) {
                        $container.imagesLoaded(function () {
                            $container.packery({
                                itemSelector: ".porto-grid-item",
                                columnWidth: ".grid-col-sizer",
                                percentPosition: true,
                            });
                        });
                        setTimeout(function () {
                            $container.animate(
                                {
                                    opacity: 1,
                                },
                                200
                            );
                        }, 500);
                    }
                });
            </script>
        </div>
    </div>
</div>
<div class="porto-inner-container p-b" style="margin-bottom: 20px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner py-5">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vendor_theme_block10')->toHtml() ?>
                    <script type="text/javascript">
                        require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                            $(".brand-carousel.owl-carousel").owlCarousel({
                                autoplay: false,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                nav: false,
                                dots: false,
                                loop: false,
                                responsive: {
                                    0: {
                                        items: 2,
                                    },
                                    640: {
                                        items: 3,
                                    },
                                    768: {
                                        items: 4,
                                    },
                                    992: {
                                        items: 5,
                                    },
                                    1200: {
                                        items: 6,
                                    },
                                },
                            });
                        });
                    </script>
                    <div class="porto-separator mb-5 mt-5"><hr class="separator-line align_center solid" style="background-color: #e7e7e7;" /></div>
                    <h2 style="font-size: 1.125rem; line-height: 1.2; text-align: center;" class="vc_custom_heading mb-3 text-uppercase"><?= __('top brands collection') ?></h2>
                    <div id="featured-products" class="porto-products wpb_content_element custom-product-space">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" extra_class="nav-center-images-only nav-style-4 show-nav-hover show-dots-title-right dots-style-1" product_count="8"
                            product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#featured-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 3,
                                            },
                                            768: {
                                                items: 3,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="porto-separator mb-5"><hr class="separator-line align_center solid" style="background-color: #e7e7e7;" /></div>
                    <h2 style="font-size: 1.125rem; line-height: 1.2; text-align: center;" class="vc_custom_heading mb-3 text-uppercase"><?= __('summer Sale') ?></h2>
                    <div id="sale-products" class="porto-products wpb_content_element custom-product-space">
                        <div class="slider-wrapper">
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" extra_class="nav-center-images-only nav-style-4 show-nav-hover show-dots-title-right dots-style-1" product_count="8"
                            product_type="1" aspect_ratio="0" image_width="350" image_height="350" template="owl_list.phtml"}}
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $("#sale-products .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: false,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: false,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 3,
                                            },
                                            768: {
                                                items: 3,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 5,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <style>
                        .custom-product-space .slider-wrapper {
                            margin-left: -1px;
                            margin-right: -1px;
                        }
                        .custom-product-space .products .product-item {
                            padding-left: 1px;
                            padding-right: 1px;
                            margin-bottom: 2px;
                        }
                    </style>
                    <div class="porto-separator mb-5"><hr class="separator-line align_center solid" style="background-color: #e7e7e7;" /></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products"><h2 class="widgettitle"><?= __('FEATURED PRODUCTS') ?></h2></div>
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products"><h2 class="widgettitle"><?= __('BEST SELLING PRODUCTS') ?></h2></div>
                        {{block class="Smartwave\Filterproducts\Block\Home\BestsellersList" name="bestseller_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_products wpb_content_element">
                        <div class="widget woocommerce widget_products"><h2 class="widgettitle"><?= __('LATEST PRODUCTS') ?></h2></div>
                        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_widget_woo_top_rated_products wpb_content_element">
                        <div class="widget woocommerce widget_top_rated_products"><h2 class="widgettitle"><?= __('Top Rated Products') ?></h2></div>
                        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="top_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
