<style>
    .columns .column.main {
        padding-bottom: 0;
    }
    .porto-ibanner-layer {
        position: absolute;
        z-index: 10;
    }
    .porto-ibanner .btn-borders.btn-xl {
        font-size: 1.125em;
        border-width: 4px;
    }
    .ls-150,
    .ls-150 > *,
    .ls-150 > .btn {
        letter-spacing: 0.15em;
    }
    .ls-30 {
        letter-spacing: 0.03em;
    }
    .ls-n-40 {
        letter-spacing: -0.04em;
    }
    .porto-carousel sup {
        font-size: 50%;
        top: -0.6em;
    }
    .vc_btn3-block {
        display: block;
        width: 100%;
    }
    .section {
        background-color: #f4f4f4;
        padding: 50px 0;
    }
    sup {
        top: -0.2em;
        font-size: 75%;
    }
    .porto-ibanner strong {
        font-weight: 800;
    }
    @media (max-width: 575px) {
        .porto-ibanner-layer {
            font-size: 0.6875rem;
        }
    }
    @media (max-width: 480px) {
        .home-slider .porto-ibanner-layer {
            font-size: 2.2vw;
        }
    }
</style>
<div class="porto-wrap-container container">
    <div class="row">
        <div class="vc_column_container col-md-12">
            <div class="wpb_wrapper vc_column-inner">
                <div id="banner-slider-demo-31" class="porto-carousel home-banner-slider owl-carousel mb-0 home-slider nav-pos-outside nav-style-4 show-nav-hover">
                    <div class="porto-ibanner text-left mb-0" style="min-height: 474px; background-color: #f4f4f4;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_slide1.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="left: 8%; top: 50%; transform: translateY(-50%);">
                                <h3 style="font-size: 2.5em; color: rgb(119, 119, 119); line-height: 1; font-weight: 500;" class="vc_custom_heading ls-n-20 mb-2 align-left">
                                    Spring / Summer Season
                                </h3>
                                <h3 style="font-size: 2.875em; line-height: 1; text-align: center;" class="vc_custom_heading mr-2 d-inline-block">
                                    up<br />
                                    to
                                </h3>
                                <h3 style="font-size: 6.125em; line-height: 1; animation-delay: 500ms;" class="vc_custom_heading ls-30 mb-4 d-inline-block align-left">
                                    50% OFF
                                </h3>
                                <div class="vc_row wpb_row vc_inner row">
                                    <div class="vc_column_container col-md-12">
                                        <div class="wpb_wrapper vc_column-inner">
                                            <h4 style="font-size: 1.125em; line-height: 1;" class="vc_custom_heading ls-n-20 pull-left mr-3 align-left">STARTING AT</h4>
                                            <h5 style="font-size: 2.5em; line-height: 0.75;" class="vc_custom_heading pull-left mr-4 mr-xl-5 pr-lg-2 align-left heading-primary"><sup>$</sup>19<sup>99</sup></h5>
                                            <div class="btn-container mb-0 d-inline-block"><button class="vc_btn3 vc_btn3-shape-default btn btn-borders btn-xl btn-dark">SHOP NOW</button></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="porto-ibanner text-left mb-0" style="min-height: 474px; background-color: #f4f4f4;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_slide2.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="right: 8%; top: 50%; transform: translateY(-50%);">
                                <h3 style="font-size: 2.125em; color: #777777; line-height: 1; font-weight: 500;" class="vc_custom_heading mb-0 align-left">EXTRA</h3>
                                <h3 style="font-size: 4.3125em; line-height: 1;" class="vc_custom_heading mb-2 align-left">20% OFF</h3>
                                <h3 style="font-size: 2.125em; line-height: 1;" class="vc_custom_heading ls-150 mb-3 pb-1 align-left">ACCESSORIES</h3>
                                <div class="btn-container mb-0 ls-150 text-center">
                                    <button class="vc_btn3 vc_btn3-shape-default vc_btn3-block btn btn-modern btn-xl btn-dark">Shop All Sale</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                        $("#banner-slider-demo-31").owlCarousel({
                            items: 1,
                            autoplay: false,
                            autoplayTimeout: 5000,
                            autoplayHoverPause: true,
                            dots: false,
                            navRewind: true,
                            animateIn: "fadeIn",
                            animateOut: "fadeOut",
                            loop: true,
                            nav: true,
                        });
                    });
                </script>
                <div class="porto-carousel brand-carousel owl-carousel mb-0 py-4">
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand1.png}}" alt="" /></div>
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand2.png}}" alt="" /></div>
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand3.png}}" alt="" /></div>
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand4.png}}" alt="" /></div>
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand5.png}}" alt="" /></div>
                    <div class="item"><img src="{{media url=wysiwyg/smartwave/porto/brands/new_brand6.png}}" alt="" /></div>
                </div>
                <script type="text/javascript">
                    require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                        $(".brand-carousel.owl-carousel").owlCarousel({
                            autoplay: true,
                            autoplayTimeout: 5000,
                            autoplayHoverPause: true,
                            nav: false,
                            dots: false,
                            loop: true,
                            responsive: {
                                0: {
                                    items: 2,
                                },
                                640: {
                                    items: 3,
                                },
                                768: {
                                    items: 4,
                                },
                                992: {
                                    items: 5,
                                },
                                1200: {
                                    items: 5,
                                },
                            },
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row home-ads section section-default mt-0 mb-0 section-no-borders porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-ibanner porto-ibe-boxshadow mb-4 mb-md-0">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_banner1.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="left: 6%; top: 7%;">
                                <h3 style="font-size: 1.375em; line-height: 1.2;" class="vc_custom_heading mb-1 align-left">Women's Bags & Purses</h3>
                                <h4 style="font-size: 1.75em; line-height: 1;" class="vc_custom_heading mb-0 align-left heading-primary">
                                    <sup><del>20%</del></sup><strong>30%</strong>
                                </h4>
                            </div>
                            <div class="porto-ibanner-layer" style="left: 5%; bottom: 5%;">
                                <div class="btn-container mb-0 d-inline-block">
                                    <button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark">Shop Now</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-ibanner porto-ibe-boxshadow mb-4 mb-md-0">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_banner2.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="width: 100%; left: 50%; transform: translateX(-50%); top: 7%;">
                                <h3 style="font-size: 1.375em; line-height: 1.2; text-align: center;" class="vc_custom_heading mb-1">Women's Shoes</h3>
                            </div>
                            <div class="porto-ibanner-layer" style="left: 50%; transform: translateX(-50%); bottom: 5%;">
                                <div class="btn-container mb-0 d-inline-block">
                                    <button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark">Shop Now</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_column_container col-md-4">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="porto-ibanner porto-ibe-boxshadow mb-4 mb-md-0">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_banner3.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="right: 6%; top: 7%;">
                                <h3 style="font-size: 1.375em; line-height: 1.2;" class="vc_custom_heading mb-1 align-right">Men's Leather Belt</h3>
                                <h4 style="font-size: 1.75em; line-height: 1;" class="vc_custom_heading mb-0 align-right heading-primary">
                                    <sup><del>30%</del></sup><strong>50%</strong>
                                </h4>
                            </div>
                            <div class="porto-ibanner-layer" style="right: 5%; bottom: 5%;">
                                <div class="btn-container mb-0 d-inline-block">
                                    <button class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-lg btn-dark">Shop Now</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row porto-inner-container" style="padding-top: 50px; padding-bottom: 16px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="vc_column_container col-md-12">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="vc_custom_heading align-left heading heading-border heading-bottom-border heading-border-xs">
                        <h2 style="font-size: 1rem; line-height: 1.4;" class="heading-tag text-uppercase">
                            Browse By Category
                        </h2>
                    </div>
                    <style>
                        ul.products li.product-category .thumb-info-wrapper:after {
                            background-color: transparent;
                        }
                        ul.products li.product-category:hover .thumb-info-wrapper:after {
                            background-color: rgba(27, 27, 23, 0.6);
                        }
                        ul.products li.product-category {
                            margin-bottom: 1.4286em;
                        }
                    </style>
                    <div class="category-slider porto-products hide-count wpb_content_element mb-3">
                        <div class="slider-wrapper">
                            <ul class="products products-container products-slider owl-carousel category-pos-middle category-text-center nav-pos-outside nav-style-4 show-nav-hover">
                                <li class="product-category product-col">
                                    <a href="#">
                                        <div class="thumb-info align-center">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_cat1.jpg}}" />
                                            </div>
                                            <div class="thumb-info-wrap">
                                                <div class="thumb-info-title">
                                                    <h3 class="sub-title thumb-info-inner">Sunglasses</h3>
                                                    <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="product-category product-col">
                                    <a href="#">
                                        <div class="thumb-info align-center">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_cat2.jpg}}" />
                                            </div>
                                            <div class="thumb-info-wrap">
                                                <div class="thumb-info-title">
                                                    <h3 class="sub-title thumb-info-inner">Bags</h3>
                                                    <span class="thumb-info-type"><mark class="count">3</mark> Products </span>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="product-category product-col">
                                    <a href="#">
                                        <div class="thumb-info align-center">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_cat3.jpg}}" />
                                            </div>
                                            <div class="thumb-info-wrap">
                                                <div class="thumb-info-title">
                                                    <h3 class="sub-title thumb-info-inner">Shoes</h3>
                                                    <span class="thumb-info-type"><mark class="count">1</mark> Products </span>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="product-category product-col">
                                    <a href="#">
                                        <div class="thumb-info align-center">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_cat4.jpg}}" />
                                            </div>
                                            <div class="thumb-info-wrap">
                                                <div class="thumb-info-title">
                                                    <h3 class="sub-title thumb-info-inner">Accessories</h3>
                                                    <span class="thumb-info-type"><mark class="count">7</mark> Products </span>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="product-category product-col">
                                    <a href="#">
                                        <div class="thumb-info align-center">
                                            <div class="thumb-info-wrapper tf-none">
                                                <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_cat5.jpg}}" />
                                            </div>
                                            <div class="thumb-info-wrap">
                                                <div class="thumb-info-title">
                                                    <h3 class="sub-title thumb-info-inner">Clothes</h3>
                                                    <span class="thumb-info-type"><mark class="count">3</mark> Products </span>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            <script type="text/javascript">
                                require(["jquery", "owl.carousel/owl.carousel.min"], function ($) {
                                    $(".category-slider .owl-carousel").owlCarousel({
                                        autoplay: false,
                                        autoplayTimeout: 5000,
                                        autoplayHoverPause: true,
                                        loop: true,
                                        navRewind: true,
                                        lazyLoad: true,
                                        margin: 0,
                                        nav: true,
                                        dots: false,
                                        responsive: {
                                            0: {
                                                items: 2,
                                            },
                                            640: {
                                                items: 2,
                                            },
                                            768: {
                                                items: 3,
                                            },
                                            992: {
                                                items: 4,
                                            },
                                            1200: {
                                                items: 4,
                                            },
                                        },
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="porto-products wpb_content_element title-border-bottom mb-0">
                        <h2 class="section-title"><span class="inline-title">Featured Products Grid</span><span class="line"></span></h2>
                        <div style="margin: 0 0 1em; padding-bottom: 20px;">
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="masonry_3" product_count="10" aspect_ratio="0" image_width="500" image_height="500" masonry_layout="3" product_type="3" gap_width="20"
                            grid_height="600" template="masonry_grid.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row section section-default mt-0 mb-0 section-no-borders porto-inner-container" style="padding-bottom: 20px;">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="col-sm-6 vc_column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element mb-0">
                        <div class="widget widget_products">
                            <h2 class="widgettitle">Top Rated Products</h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\SaleList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 vc_column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element mb-0">
                        <div class="widget widget_products">
                            <h2 class="widgettitle">Best Selling Products</h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 vc_column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_content_element mb-0">
                        <div class="widget widget_products">
                            <h2 class="widgettitle">Latest Products</h2>
                            {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="featured_product" product_count="3" aspect_ratio="0" image_width="150" image_height="150" template="small_list.phtml"}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 d-flex align-items-end vc_column_container col-md-6 col-lg-3">
                <div class="wpb_wrapper vc_column-inner w-100">
                    <div class="porto-ibanner m-b-lg" style="background-color: #2f2d33;">
                        <img src="{{media url=wysiwyg/smartwave/porto/homepage/31/shop31_home_banner4.jpg}}" />
                        <div class="porto-ibanner-desc no-padding d-flex">
                            <div class="porto-ibanner-layer" style="width: 100%; left: 0%; top: 50%; transform: translateY(-50%);">
                                <h3 style="font-size: 2em; line-height: 1; text-align: center;" class="vc_custom_heading mb-2 heading-light">Top Shoes</h3>
                                <h4 style="font-size: 1.375em; line-height: 1; text-align: center; font-weight: 600;" class="vc_custom_heading ls-n-40 mb-3 heading-primary">Summer Sale</h4>
                                <div class="btn-container mb-0 text-center"><button class="vc_btn3 vc_btn3-shape-default btn btn-borders btn-md btn-light">SHOP NOW</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row section section-parallax mt-0 mb-0 section-no-borders porto-inner-container">
    <div class="porto-wrap-container container">
        <div class="row">
            <div class="mb-5 vc_column_container col-md-12">
                <style>
                    .follow-instagram {
                        position: absolute;
                        top: 50%;
                        left: 50%;
                        transform: translate(-50%, -50%);
                    }
                    .follow-instagram .porto-sicon-read {
                        display: inline-block;
                        color: #fff;
                        border: 2px solid;
                        font-size: 0.8125rem;
                        font-weight: 600;
                        letter-spacing: 0.05em;
                        padding: 0.75em 2em;
                        text-decoration: none;
                        margin-top: 0.25rem;
                    }
                    .single-subscribe .newsletter input {
                        padding-left: 1.5rem;
                        font-family: Poppins;
                        font-size: 0.75rem;
                        font-style: italic;
                    }
                    .single-subscribe .newsletter .action {
                        background: #343437;
                        border: none;
                        padding: 0 2rem 0 1.5rem;
                    }
                </style>
                <div class="wpb_wrapper vc_column-inner">
                    <div class="wpb_text_column wpb_content_element mb-0">
                        <div class="wpb_wrapper">
                            {{block class="Smartwave\Porto\Block\Template" name="instagram" padding_item="0" template="Smartwave_SocialFeed::instagramphotos.phtml"}}
                        </div>
                    </div>
                </div>
                <div class="porto-sicon-box mb-0 follow-instagram style_1 top-icon" style="padding-top: 2.25rem; padding-right: 2.75rem; padding-bottom: 2.25rem; padding-left: 2.75rem; background-color: #0e0e0e;">
                    <div class="porto-sicon-top">
                        <div class="porto-just-icon-wrapper porto-icon none" style="color: #ffffff; font-size: 28px;"><i class="fab fa-instagram"></i></div>
                    </div>
                    <div class="porto-sicon-header">
                        <h3 class="porto-sicon-title" style="font-weight: 700; font-size: 1.875rem; line-height: 1; color: #ffffff;">INSTAGRAM</h3>
                        <p style="line-height: 1.4; color: #f4f4f4;">@portoecommerce</p>
                    </div>
                    <div class="porto-sicon-description" style="">
                        <a class="porto-sicon-read xx" href="#">FOLLOW</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="vc_column_container col-md-10 offset-xl-3 col-xl-6 offset-lg-2 col-lg-8 offset-md-1">
            <div class="wpb_wrapper vc_column-inner">
                <div class="porto-sicon-box style_1 top-icon">
                    <div class="porto-sicon-top">
                        <div class="porto-just-icon-wrapper porto-icon none" style="color: #222529; font-size: 30px;"><i class="far fa-envelope"></i></div>
                    </div>
                    <div class="porto-sicon-header">
                        <h3 class="porto-sicon-title" style="font-weight: 600; font-size: 1.5rem; line-height: 1.2;">Subscribe to Our Newsletter</h3>
                        <p style="font-size: 13px; line-height: 1.2;">Get all the latest information on Events, Sales and Offers.</p>
                    </div>
                </div>
                {{block class="Magento\Newsletter\Block\Subscribe" name="home.newsletter" template="subscribe_form.phtml"}}
            </div>
        </div>
    </div>
</div>
