<?php
$_cssWidget = '
.cms-index-index .amp-page-main {
	padding: 0;
}
.frame, .frame.no-padding {
    padding: 0 15px;
}
.no-padding-col .frame, 
.no-padding-col .line div[class*=col-des], 
.no-padding-col .line div[class*=col-tb], 
.no-padding-col .line div[class*=col-mb] {
    padding-left: 0;
    padding-right: 0;
}
.no-padding-col .line {
    margin-left: 0;
    margin-right: 0;
}
';
?>
<?php
// *
// Grid Layout 
// *****
$_cssWidget .= '
.line {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-right: calc(-15px/2);
    margin-left: calc(-15px/2);
}
*:not(td):not(th).col, .col-1, .col-10, .col-11, .col-12, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-auto, .col-des, .col-des-1, .col-des-10, .col-des-11, .col-des-12, .col-des-2, .col-des-3, .col-des-4, .col-des-5, .col-des-6, .col-des-7, .col-des-8, .col-des-9, .col-des-auto {
    position: relative;
    width: 100%;
    min-height: 1px;
    padding-right: calc(15px/2);
    padding-left: calc(15px/2);
}
.row-1 .col, .col-12, .col-des-12, .col-mb-12, .col-tb-12 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 100%;
    flex: 0 1 100%;
    max-width: 100%;
}
.col-11, .col-des-11, .col-mb-11, .col-tb-11 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 91.666667%;
    flex: 0 1 91.666667%;
    max-width: 91.666667%;
}
.col-10, .col-des-10, .col-mb-10, .col-tb-10 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 83.333333%;
    flex: 0 1 83.333333%;
    max-width: 83.333333%;
}
.col-9, .col-des-9, .col-mb-9, .col-tb-9 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 75%;
    flex: 0 1 75%;
    max-width: 75%;
}
.col-8, .col-des-8, .col-mb-8, .col-tb-8 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 66.666667%;
    flex: 0 1 66.666667%;
    max-width: 66.666667%;
}
.col-7, .col-des-7, .col-mb-7, .col-tb-7 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 58.333333%;
    flex: 0 1 58.333333%;
    max-width: 58.333333%;
}
.row-2 .col, .col-6, .col-des-6, .col-mb-6, .col-tb-6 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 50%;
    flex: 0 1 50%;
    max-width: 50%;
}
.col-5, .col-des-5, .col-mb-5, .col-tb-5 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 41.666667%;
    flex: 0 1 41.666667%;
    max-width: 41.666667%;
}
.row-3 .col, .col-4, .col-des-4, .col-mb-4, .col-tb-4 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 33.333333%;
    flex: 0 1 33.333333%;
    max-width: 33.333333%;
}
.row-4 .col, .col-3, .col-des-3, .col-mb-3, .col-tb-3 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 25%;
    flex: 0 1 25%;
    max-width: 25%;
}
.col-2, .col-des-2, .col-mb-2, .col-tb-2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 16.666667%;
    flex: 0 1 16.666667%;
    max-width: 16.666667%;
}
.col-1, .col-des-1, .col-mb-1, .col-tb-1 {
    -webkit-box-flex: 0;
    -ms-flex: 0 1 8.333333%;
    flex: 0 1 8.333333%;
    max-width: 8.333333%;
}
';
?>
<?php
// *
// PromoBanner
// *****
$_cssWidget .= '
.mgs-promobanner {
    display: block;
	position: relative;
}
.mgs-promobanner > .text {
    position: absolute;
    padding: 20px;
    z-index: 1;
    color: #1a1a1a;
    font-size: 15px
}
.mgs-promobanner .text-center {
    text-align: center;
}
.mgs-promobanner > .text.top-left,
.mgs-promobanner > .text.top-middle,
.mgs-promobanner > .text.top-right {
    top: 0
}
.mgs-promobanner > .text.top-left {
    left: 0
}
.mgs-promobanner > .text.top-middle {
    left: 50%;
    transform: translateX(-50%);
    -webkit-transform: translateX(-50%);
    -moz-transform: translateX(-50%);
    -o-transform: translateX(-50%)
}
.mgs-promobanner > .text.top-right {
    right: 0
}
.mgs-promobanner > .text.middle-left,
.mgs-promobanner > .text.middle-center,
.mgs-promobanner > .text.middle-right {
    top: 50%;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -moz-transform: translateY(-50%);
    -o-transform: translateY(-50%)
}
.mgs-promobanner > .text.middle-left {
    left: 0
}
.mgs-promobanner > .text.middle-center {
    left: 50%;
    transform: translate(-50%, -50%);
    -webkit-transform: translate(-50%, -50%);
    -moz-transform: translate(-50%, -50%);
    -o-transform: translate(-50%, -50%)
}
.mgs-promobanner > .text.middle-right {
    right: 0
}
.mgs-promobanner > .text.bottom-left,
.mgs-promobanner > .text.bottom-center,
.mgs-promobanner > .text.bottom-right {
    bottom: 0
}
.mgs-promobanner > .text.bottom-left {
    left: 0
}
.mgs-promobanner > .text.bottom-center {
    left: 50%;
    transform: translateX(-50%);
    -webkit-transform: translateX(-50%);
    -moz-transform: translateX(-50%);
    -o-transform: translateX(-50%)
}
.mgs-promobanner > .text.bottom-right {
    right: 0
}
.mgs-promobanner .banner-text .sub-title {
    font-size: .75rem;
    letter-spacing: .01em;
    display: block;
    margin-bottom: 2px;
}
.mgs-promobanner .banner-text .title {
    font-size: 1.875rem;
    font-weight: 700;
    white-space: nowrap;
}
.section-title {
    text-align: center;
    margin-bottom: 2rem;
}
.section-title .title {
    font-weight: 600;
    margin: 0;
}
';
?>
<?php
// *
// OWL SLIDER
// *****
$_cssWidget .= '
.item-image {
	position: relative;
}
.slider_mgs_carousel .slide-text {
    opacity: 1;
    visibility: visible;
    padding: 15px;
    position: absolute;
    left: 0;
    right: 0;
    margin: 0 auto;
}
.slider_mgs_carousel .slide-text.middle_left {
    top: 50%;
    bottom: auto;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -moz-transform: translateY(-50%);
    -o-transform: translateY(-50%);
}
.slider_mgs_carousel .slide-text.middle {
    top: 50%;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -moz-transform: translateY(-50%);
    -o-transform: translateY(-50%);
}
.slider_mgs_carousel .slide-text.middle_right {
    top: 50%;
    bottom: auto;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -moz-transform: translateY(-50%);
    -o-transform: translateY(-50%);
}
.slider_mgs_carousel .slide-text.top_right {
    top: 0;
    bottom: auto;
}
.slider_mgs_carousel .slide-text.top_center {
    top: 0;
    bottom: auto;
}
.slider_mgs_carousel .slide-text.top_left {
    top: 0;
    bottom: auto;
}
.slider_mgs_carousel .inner-text .sub-title {
    text-transform: uppercase;
    font-size: .85rem;
    font-weight: 600;
    color: #f68872;
}
.slider_mgs_carousel .inner-text .title {
    font-size: 2.5rem;
    font-weight: 700;
    line-height: 1.05;
    color: #222;
    margin-bottom: 10px;
}
';
?>
<?php
// *
// OWL SLIDER
// *****
$_cssWidget .= '
.form.subscribe.newsletter {
	position: relative;
}
.form.subscribe.newsletter input {
	padding-right: 40px;
	border-width: 2px;
}
.form.subscribe.newsletter .action.subscribe {
	position: absolute;
    right: 0;
    top: 0;
	background: 0 0;
    border: none;
    box-shadow: none;
    height: 46px;
    width: 40px;
    color: #8b8b8b;
    padding: 0;
    font-size: 20px;
	cursor: pointer;
}
.form.subscribe.newsletter .action.subscribe:after {
    content: "\e696";
    font-family: Linearicons;
}
';
?>
<?= $_cssWidget ?>