<?php $cssMenuSidebar = '
    .site_menu[side=left] {
        width: 100%;
    }
    .amp-menu {
        clear: both;
    }
    .amp-menu h6,
    .amp-menu a {
        padding: 10px;
        display: block;
        border-right: none;
        border-left: none;
        position: relative;
    }
    .amp-menu ul h6,
    .amp-menu ul a:first-child {
        border-top: none;
    }
    .amp-menu ul.level0 h6,
    .amp-menu ul.level0 a{
        padding-left: 25px;
    }
    .amp-menu ul.level1 h6,
    .amp-menu ul.level1 a{
        padding-left: 35px;
    }
    .amp-menu ul.level2 h6,
    .amp-menu ul.level2 a{
        padding-left: 45px;
    }
    .amp-menu ul.level3 h6,
    .amp-menu ul.level3 a{
        padding-left: 55px;
    }
    .amp-menu h6:after {
        content: "+";
        position: absolute;
        display: block;
        right: 0;
        width: 41px;
        height: 41px;
        line-height: 41px;
        text-align: center;
        top: 0;
    }
    .amp-menu h6[aria-expanded="true"]:after {
        content: "-";
    }
    .close-menu-site {
        float: right;
        width: 40px;
        height: 40px;
        background: none;
        border: none;
        box-shadow: none;
    }
    .close-menu-site:after {
        content: "\e935";
        font-size: 1rem;
        font-family: Linearicons;
        line-height: 30px;
        font-size: 20px;
    }
';
?>
<?= $cssMenuSidebar ?>


