<?php $megaMenu = $block->getMegamenuItems(); ?>
<?php $helper = $this->helper('MGS\Mmegamenu\Helper\Data') ?>
<?php $menuSize = $megaMenu->getSize() ?>
<?php if($menuSize>0 || $helper->getStoreConfig('megamenu/general/home')):?>
	<nav class="navigation mgs-megamenu--main" role="navigation">
        <ul class="nav nav-main nav-main-menu">
            <?php if($helper->getStoreConfig('megamenu/general/home')): ?>
                <li class="mega-menu-item level0">
                    <a href="<?php echo $this->getUrl() ?>" class="level0">
                        <?php echo $helper->getStoreConfig('megamenu/general/hometext') ?>
                    </a>
                </li>
            <?php endif ?>
            <?php if($menuSize>0) echo $block->getMenuHtml() ?>
        </ul>
	</nav>
<?php endif ?>
