<?php $portfolio = $this->getPortfolio(); ?>
<?php $portfolioHelper = $this->helper('MGS\Portfolio\Helper\Data'); ?>
<?php 
	$portfolios = $this->getCurrentPortfolios();
	$galleryArray = $this->getBaseImage($portfolio);
?>
<div class="portfolio-view">
	<h1 class="title"><?php echo $portfolio->getName();?></h1>
</div>

<div class="frame">
	<div class="line portfolio-details">
		<div class="col-12">
			<div class="portfolio-detail--image">
				<div class="portfolio-image">
					<?php if($galleryArray): ?>
						<div id="portfolio_galley_carousel" class="owl-carousel portfolio_galley_carousel">
							<?php $i=0; foreach($galleryArray as $_img): $i++; ?>
								<div class="image-item">
									<a href="<?php echo $_img; ?>" style="background-image: url('<?php echo $_img ?>');">
										<img src="<?php echo $_img; ?>" alt="" class="img-fluid"/>
									</a>
								</div>							
							<?php endforeach ?>
						</div>
						
						<script type="text/javascript">
							require([
								'jquery',
								'mgsowlcarousel',
								'magnificPopup'
							], function($){
								$("#portfolio_galley_carousel").owlCarousel({
									items: 1,
									nav: false,
									dots: true,
									loop:true,
									autoplay: true,
									rtl: $_rtlConfig,
									autoHeight: true,
									navText: ["<span class='fa fa-angle-left'></span>","<span class='fa fa-angle-right'></span>"]
								});
								$('#portfolio_galley_carousel').magnificPopup({
									delegate: '.owl-item:not(.cloned) a',
									type: 'image',
									tLoading: 'Loading image #%curr%...',
									mainClass: 'mfp-img-gallery',
									fixedContentPos: true,
									gallery: {
										enabled: true,
										navigateByImgClick: true,
										preload: [0,1]
									},
									image: {
										tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
										titleSrc: function(item) {
										return item.el.attr('title');
										}
									}
								});
							});
						</script>
					<?php endif ?>
				</div>
			</div>
		</div>
		<div class="portfolio-view-content col-12">
			<div class="portfolio-info">
				<div class="portfolio-datetime">
					<div class="date">
						<?php $date = $portfolio->getPortfolioDate() ?>
						<?php if($date != ''): ?>
							<span><?php echo date('F d, Y', strtotime($date))?></span>
						<?php endif ?>
					</div>
					<div class="category">
						<?php $categoryLinks = $this->getCategoriesLink($portfolio) ?>
						<?php if($categoryLinks != ''): ?>
							<span><?php echo $categoryLinks ?></span>
						<?php endif ?>
					</div>
				</div>
				<div class="sharethis">
					<span class="text-color"><?php echo __('Share:')?></span><span><?php echo $block->getChildHtml('sharethis.html');?></span>
				</div>
			</div>
			<div class="description">
				<?php echo $portfolioHelper->generateContentFilter($portfolio->getDescription()) ?>
			</div>
		</div>
	</div>
</div>
<?php // Related Portfolio ?>
<?php $relatedPortfolio = $this->getRelatedPortfolio($portfolio) ?>
<?php if (count($relatedPortfolio) > 0): ?>
	<div class="portfolio-related detail-page-grid-products">
		<div class="content-heading">
			<h3 class="title"><?php echo __('Related Works') ?></h3>
		</div>
		<div class="row-owl-carousel portfolio-grid">
			<div class="owl-carousel portfolio-widget portfolio-carousel one-row" id="portfolio_carousel">
				<?php foreach ($relatedPortfolio as $_portfolio): ?>
					<div class="item">
						<div class="portfolio-top-content">
							<?php $thumbnailUrl = $this->getThumbnailSrc($_portfolio) ?>
							<?php $portfolioUrl = $this->getPortfolioAddress($_portfolio) ?>
							<?php if($thumbnailUrl): ?>
								<a style="background-image: url('<?= $thumbnailUrl ?>');" href="<?= $portfolioUrl; ?>" class="portfolio-item-link port-thumbnail-image">	
									<img src="<?= $thumbnailUrl ?>" alt="<?= $_portfolio->getName() ?>"/>
								</a>
							<?php endif ?>
						</div>
						<div class="portfolio-bottom-content">
							<h4 class="port-title"><a href="<?= $portfolioUrl ?>"><?= $_portfolio->getName() ?></a></h4>
						</div>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		require([
			'jquery',
			'mgsowlcarousel'
		], function ($) {
			$("#portfolio_carousel").owlCarousel({
				items: 1,
				margin: 30 ,
				autoplay: true,
				autoplayHoverPause: true,
				nav: false,
				dots: false,
				loop: true,
				rtl: $_rtlConfig,
				navText: ["<i class='ti-arrow-left'></i>","<i class='ti-arrow-right'></i>"]
			});
		});
</script>
<?php endif ?>