<?php
declare(strict_types=1);

namespace MagentoEgypt\AlgoliaVendor\Model;

use Magento\Framework\Indexer\SaveHandler\IndexerInterface;
use Psr\Log\LoggerInterface;

/**
 * catalogsearch_fulltext handler while the engine is `algolia`: runs Algolia's
 * handler (a no-op — Algolia indexes through its own indexers) and ALSO keeps
 * the OpenSearch index current, so the fallback and the Luma storefront never
 * read a stale index. OpenSearch failures are logged, never thrown.
 *
 * The documents Magento hands this handler are USELESS for OpenSearch: they
 * are generated by the current engine's resource model, and Algolia's
 * (Algolia\SearchAdapter\Model\ResourceModel\Engine) reports no allowed
 * visibility, so the generator yields nothing. Saving them emptied OpenSearch
 * documents (measured 2026-09-24). Instead the product IDs are remembered —
 * from deleteIndex() on a partial reindex, "all" after cleanIndex() on a full
 * one — and saveIndex() regenerates the documents with OpenSearch's engine
 * ($documentsFor, built by Plugin\FulltextIndexerMirror).
 */
class OpenSearchMirrorIndexerHandler implements IndexerInterface
{
    /** @var array<int|string, int[]|null> store id => product ids (null = whole store) */
    private array $pending = [];

    /**
     * @param callable(int, ?array): \Traversable $documentsFor store id, product ids|null
     * @param callable(mixed): int $storeIdOf dimensions => store id
     */
    public function __construct(
        private readonly IndexerInterface $primary,
        private readonly IndexerInterface $openSearch,
        private readonly LoggerInterface $logger,
        private $documentsFor,
        private $storeIdOf
    ) {
    }

    public function saveIndex($dimensions, \Traversable $documents)
    {
        $this->primary->saveIndex($dimensions, $documents);

        $this->mirror('saveIndex', function () use ($dimensions) {
            $storeId = ($this->storeIdOf)($dimensions);
            $ids = array_key_exists($storeId, $this->pending) ? $this->pending[$storeId] : null;
            unset($this->pending[$storeId]);
            $this->openSearch->saveIndex($dimensions, ($this->documentsFor)($storeId, $ids));
        });

        return $this;
    }

    public function deleteIndex($dimensions, \Traversable $documents)
    {
        $ids = array_map('intval', array_values(iterator_to_array($documents)));
        $this->primary->deleteIndex($dimensions, new \ArrayIterator($ids));

        $this->mirror('deleteIndex', function () use ($dimensions, $ids) {
            $storeId = ($this->storeIdOf)($dimensions);
            $this->pending[$storeId] = array_values(array_unique(array_merge($this->pending[$storeId] ?? [], $ids)));
            $this->openSearch->deleteIndex($dimensions, new \ArrayIterator($ids));
        });

        return $this;
    }

    public function cleanIndex($dimensions)
    {
        $this->primary->cleanIndex($dimensions);

        $this->mirror('cleanIndex', function () use ($dimensions) {
            $this->pending[($this->storeIdOf)($dimensions)] = null; // full rebuild of this store
            $this->openSearch->cleanIndex($dimensions);
        });

        return $this;
    }

    public function isAvailable($dimensions = [])
    {
        return $this->primary->isAvailable($dimensions);
    }

    private function mirror(string $method, callable $fn): void
    {
        try {
            EngineOverride::run('opensearch', $fn);
        } catch (\Throwable $e) {
            $this->logger->warning(sprintf('OpenSearch mirror %s failed: %s', $method, $e->getMessage()));
        }
    }
}
