<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Vnecoms\VendorsSearch\Block\Search */
/** @var $helper \Vnecoms\VendorsSearch\Helper\Data */
$helper = $this->helper('Vnecoms\VendorsSearch\Helper\Data');
?>
<div class="block-search-by-vendor">
    <div class="block-content">
        <form class="form minisearch-vendor" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="search_by_vendor_form-mobile" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="search-label label" for="vendor-search-mobile" data-role="minisearch-vendor-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input id="vendor-search-mobile"
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search %1 products here...', $block->getVendorName()); ?>"
                           class="minisearch-vendor-input input-text"
                           data-validate="{required:true, 'validate-no-empty':true}"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="vendor_search_autocomplete-mobile" class="vendor-search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search-icon">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>