<?php 
$_product = $this->getLoadedProduct();
$_productImage = $block->getImage($_product, 'amp_category_page_grid')->setCustomAttributes('layout="responsive"')->setTemplate('MGS_Amp::Magento_Catalog/product/image.phtml'); 
$_productName = $block->escapeHtml($_product->getName());
$_productUrl = $block->getProductUrl($_product);
?>
<div class="product-item-info">
	<a class="product photo product-item-photo" href="<?= $_productUrl ?>" title="<?= $_productName ?></a>">
		<?= $_productImage->toHtml() ?>
	</a>
	<div class="product details product-item-details">
		<strong class="product name product-item-name">
			<a class="product-item-link" href="<?= $_productUrl ?>"><?= $_productName ?></a>
		</strong>
		
		<?= $block->getProductPrice($_product); ?>
		
		<div class="product actions product-item-actions">
			<div class="actions-primary">
				<a href="<?= $_productUrl ?>" class="action tocart"><span><?= __('View Detail'); ?></span></a>
			</div>
		</div>
	</div>
</div>